import { ARTIFACT_DEFINITIONS } from '../artifacts/artifacts.js';
import { CARD_DEFINITIONS, CARD_TABLES } from '../cards/cardGame.js';
import { FISH_DEFINITIONS } from '../fishing/fishDefinitions.js';
import { EQUIPMENT_SLOTS } from '../inventory/item.js';
import type {
  AchievementDefinition,
  AchievementIconSpec,
  AchievementNumericSnapshotField,
} from './achievementTypes.js';

const ap = { enabledByDefault: true } as const;
const icon = (
  kind: AchievementIconSpec['kind'],
  fallbackGlyph: string,
  variant?: string,
): AchievementIconSpec => ({ kind, fallbackGlyph, variant });
const event = (
  eventType: Extract<AchievementDefinition['criterion'], { kind: 'event' }>['eventType'],
  match?: Record<string, string | number>,
) => ({ kind: 'event', eventType, ...(match ? { match } : {}) }) as const;
const snap = (field: AchievementNumericSnapshotField, target: number) =>
  ({ kind: 'snapshot', field, target }) as const;
const p = (target: number, label: string) => ({ target, label });
const d = (definition: AchievementDefinition): AchievementDefinition => definition;

export const DISCOVERABLE_BIOME_IDS = [
  'verdigris-basin',
  'ember-waste',
  'moonlit-parish',
  'sable-depths',
  'gloam-garden',
  'elderwood-maze',
  'sunken-ocean',
  'jade-peak-province',
  'liberty-badlands',
  'provence-valley',
] as const;
export const TOTAL_FISH_COUNT = new Set(FISH_DEFINITIONS.map((fish) => fish.typeId)).size;
export const TOTAL_ARTIFACT_COUNT = ARTIFACT_DEFINITIONS.length;
export const TOTAL_CARD_COUNT = CARD_DEFINITIONS.length;
export const PRACTICAL_RESISTANCE_THRESHOLD = 0.85;
export const HAZARD_SURVIVAL_TARGET_MS = 60_000;

export const ACHIEVEMENT_DEFINITIONS = [
  d({
    id: 'core.firstApple',
    name: 'A Classic',
    description: 'Eat your first apple.',
    category: 'core',
    difficulty: 'tutorial',
    scoreReward: 0,
    tree: { x: 0, y: 0, section: 'The Snake' },
    icon: icon('apple', 'A'),
    criterion: event('apple:eaten'),
    archipelago: ap,
  }),
  d({
    id: 'core.bigBite',
    name: 'Big Bite',
    description: 'Eat or defeat your first enemy.',
    category: 'core',
    difficulty: 'easy',
    prerequisites: ['core.firstApple'],
    tree: { x: 140, y: 0, section: 'The Snake' },
    icon: icon('enemy', 'E'),
    criterion: event('enemy:defeated'),
    archipelago: ap,
  }),
  d({
    id: 'arcade.snakeception',
    name: 'Snakeception',
    description: 'Play Snake for the Modern Snake.',
    category: 'core',
    difficulty: 'easy',
    prerequisites: ['core.firstApple'],
    tree: { x: 140, y: -360, section: 'Arcade' },
    icon: icon('arcadeCabinet', 'ARCADE'),
    criterion: event('arcade:played'),
    archipelago: ap,
  }),
  d({
    id: 'arcade.blueScreen',
    name: 'Blue Snake of Death',
    description: 'Trigger a blue screen in Snake for the Modern Snake.',
    category: 'core',
    difficulty: 'secret',
    prerequisites: ['arcade.snakeception'],
    tree: { x: 280, y: -360, section: 'Arcade' },
    icon: icon('blueScreen', ':('),
    criterion: event('arcade:blueScreen'),
    archipelago: ap,
    secret: true,
  }),
  d({
    id: 'stats.score500',
    name: 'Making Points',
    description: 'Reach 500 score.',
    category: 'stats',
    difficulty: 'easy',
    prerequisites: ['core.firstApple'],
    tree: { x: 140, y: -120, section: 'Growth' },
    icon: icon('snake', '500'),
    criterion: snap('score', 500),
    progress: p(500, 'score'),
    archipelago: ap,
  }),
  d({
    id: 'stats.special10',
    name: 'Perfectly S.P.E.C.I.A.L.',
    description: 'Raise any SPECIAL stat to 10.',
    category: 'stats',
    difficulty: 'hard',
    prerequisites: ['stats.score500'],
    tree: { x: 280, y: -240, section: 'Growth' },
    icon: icon('specialStat', '10'),
    criterion: snap('maxSpecialStat', 10),
    progress: p(10, 'SPECIAL'),
    archipelago: ap,
  }),
  d({
    id: 'stats.score1000',
    name: 'Four Digits',
    description: 'Reach 1,000 score.',
    category: 'stats',
    difficulty: 'medium',
    prerequisites: ['stats.score500'],
    tree: { x: 280, y: -120, section: 'Growth' },
    icon: icon('snake', '1K'),
    criterion: snap('score', 1000),
    progress: p(1000, 'score'),
    archipelago: ap,
  }),
  d({
    id: 'stats.score10000',
    name: 'Score Lord',
    description: 'Reach 10,000 score.',
    category: 'stats',
    difficulty: 'legendary',
    prerequisites: ['stats.score1000'],
    tree: { x: 420, y: -120, section: 'Growth' },
    icon: icon('snake', '10K'),
    criterion: snap('score', 10000),
    progress: p(10000, 'score'),
    archipelago: ap,
  }),
  d({
    id: 'stats.length100',
    name: 'Long Snake',
    description: 'Reach length 100.',
    category: 'stats',
    difficulty: 'medium',
    prerequisites: ['core.bigBite'],
    tree: { x: 280, y: 0, section: 'Growth' },
    icon: icon('snake', '100'),
    criterion: snap('length', 100),
    progress: p(100, 'length'),
    archipelago: ap,
  }),
  d({
    id: 'stats.length250',
    name: 'Legendary Length',
    description: 'Reach length 250.',
    category: 'stats',
    difficulty: 'hard',
    prerequisites: ['stats.length100'],
    tree: { x: 420, y: 0, section: 'Growth' },
    icon: icon('snake', '250'),
    criterion: snap('length', 250),
    progress: p(250, 'length'),
    archipelago: ap,
  }),
  d({
    id: 'stats.length1000',
    name: 'World Serpent',
    description: 'Reach length 1,000.',
    category: 'stats',
    difficulty: 'legendary',
    prerequisites: ['stats.length250'],
    tree: { x: 560, y: 0, section: 'Growth' },
    icon: icon('snake', '1K'),
    criterion: snap('length', 1000),
    progress: p(1000, 'length'),
    archipelago: ap,
  }),
  d({
    id: 'exploration.rooms25',
    name: 'Road Trip',
    description: 'Visit 25 rooms.',
    category: 'exploration',
    difficulty: 'easy',
    prerequisites: ['core.firstApple'],
    tree: { x: -140, y: -120, section: 'World' },
    icon: icon('biome', '25'),
    criterion: snap('roomsVisited', 25),
    progress: p(25, 'rooms'),
    archipelago: ap,
  }),
  d({
    id: 'equipment.swim25',
    name: 'Olympic Swimmer',
    description: 'Swim across 25 water tiles.',
    category: 'equipment',
    difficulty: 'medium',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 0, section: 'World' },
    icon: icon('water', 'W'),
    criterion: snap('waterTilesSwum', 25),
    progress: p(25, 'water tiles'),
    archipelago: ap,
  }),
  d({
    id: 'biomes.discoverAll',
    name: 'World Tour',
    description: 'Discover every overworld biome.',
    category: 'exploration',
    difficulty: 'hard',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: -240, section: 'World' },
    icon: icon('biome', 'ALL'),
    criterion: snap('discoveredBiomeCount', DISCOVERABLE_BIOME_IDS.length),
    progress: p(DISCOVERABLE_BIOME_IDS.length, 'biomes'),
    archipelago: ap,
  }),
  d({
    id: 'towns.openGate',
    name: 'City Limits',
    description: 'Open a town gate.',
    category: 'towns',
    difficulty: 'easy',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: -120, section: 'World' },
    icon: icon('town', 'G'),
    criterion: event('town:gateOpened'),
    archipelago: ap,
  }),
  d({
    id: 'guild.enterHideout',
    name: 'Down the Grate',
    description: 'Enter a Thieves Guild hideout.',
    category: 'guild',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: -120, section: 'Society' },
    icon: icon('guild', 'TG', 'hideout'),
    criterion: event('guild:enteredHideout'),
    archipelago: ap,
  }),
  d({
    id: 'hazards.hotSurvival',
    name: 'Heat Wave',
    description: 'Survive 60 seconds in a hot biome.',
    category: 'hazards',
    difficulty: 'medium',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 240, section: 'Hazards' },
    icon: icon('hazardHot', 'H'),
    criterion: snap('hotSurvivalMs', HAZARD_SURVIVAL_TARGET_MS),
    progress: p(HAZARD_SURVIVAL_TARGET_MS, 'ms'),
    archipelago: ap,
  }),
  d({
    id: 'hazards.coldSurvival',
    name: 'Cold Snap',
    description: 'Survive 60 seconds in a cold biome.',
    category: 'hazards',
    difficulty: 'medium',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 360, section: 'Hazards' },
    icon: icon('hazardCold', 'C'),
    criterion: snap('coldSurvivalMs', HAZARD_SURVIVAL_TARGET_MS),
    progress: p(HAZARD_SURVIVAL_TARGET_MS, 'ms'),
    archipelago: ap,
  }),
  d({
    id: 'hazards.heatResistance',
    name: 'Fireproof',
    description: 'Reach practical full heat resistance.',
    category: 'hazards',
    difficulty: 'hard',
    prerequisites: ['hazards.hotSurvival'],
    tree: { x: -420, y: 240, section: 'Hazards' },
    icon: icon('hazardHot', 'R'),
    criterion: snap('heatResistance', PRACTICAL_RESISTANCE_THRESHOLD),
    progress: p(PRACTICAL_RESISTANCE_THRESHOLD, 'resistance'),
    archipelago: ap,
  }),
  d({
    id: 'hazards.coldResistance',
    name: 'Winterized',
    description: 'Reach practical full cold resistance.',
    category: 'hazards',
    difficulty: 'hard',
    prerequisites: ['hazards.coldSurvival'],
    tree: { x: -420, y: 360, section: 'Hazards' },
    icon: icon('hazardCold', 'R'),
    criterion: snap('coldResistance', PRACTICAL_RESISTANCE_THRESHOLD),
    progress: p(PRACTICAL_RESISTANCE_THRESHOLD, 'resistance'),
    archipelago: ap,
  }),
  d({
    id: 'towns.wanted5',
    name: 'Public Enemy',
    description: 'Reach wanted level 5.',
    category: 'towns',
    difficulty: 'hard',
    prerequisites: ['guild.enterHideout'],
    tree: { x: -560, y: -120, section: 'Society' },
    icon: icon('wanted', '5'),
    criterion: snap('wantedLevel', 5),
    progress: p(5, 'wanted'),
    archipelago: ap,
  }),
  d({
    id: 'guild.initiation',
    name: 'In the Guild',
    description: 'Complete Thieves Guild initiation.',
    category: 'guild',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: 0, section: 'Society' },
    icon: icon('guild', 'TG'),
    criterion: event('guild:initiationCompleted'),
    archipelago: ap,
  }),
  d({
    id: 'towns.bigIron',
    name: 'Big Iron',
    description: 'Enter a town wearing a cowboy hat with a gun equipped.',
    category: 'towns',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -560, y: 0, section: 'Society' },
    icon: icon('bigIron', 'BI'),
    criterion: event('town:enteredBigIron'),
    archipelago: ap,
  }),
  d({
    id: 'house.expansion',
    name: 'Room to Grow',
    description: 'Complete a house expansion.',
    category: 'house',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: -360, section: 'Home' },
    icon: icon('house', '+'),
    criterion: event('house:expanded'),
    archipelago: ap,
  }),
  d({
    id: 'quests.first',
    name: 'Helpful Snake',
    description: 'Complete one quest.',
    category: 'quests',
    difficulty: 'easy',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -420, y: -480, section: 'Quests' },
    icon: icon('quest', '1'),
    criterion: snap('questsCompleted', 1),
    progress: p(1, 'quests'),
    archipelago: ap,
  }),
  d({
    id: 'quests.five',
    name: 'Errand Coil',
    description: 'Complete five quests.',
    category: 'quests',
    difficulty: 'hard',
    prerequisites: ['quests.first'],
    tree: { x: -560, y: -480, section: 'Quests' },
    icon: icon('quest', '5'),
    criterion: snap('questsCompleted', 5),
    progress: p(5, 'quests'),
    archipelago: ap,
  }),
  d({
    id: 'treasure.first',
    name: 'Treasure Hunter',
    description: 'Collect your first room treasure or cache.',
    category: 'treasure',
    difficulty: 'easy',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -420, y: -600, section: 'Treasure' },
    icon: icon('treasure', '1'),
    criterion: snap('treasuresCollected', 1),
    progress: p(1, 'treasures'),
    archipelago: ap,
  }),
  d({
    id: 'treasure.five',
    name: 'Cache Collector',
    description: 'Collect five room treasures or caches.',
    category: 'treasure',
    difficulty: 'medium',
    prerequisites: ['treasure.first'],
    tree: { x: -560, y: -600, section: 'Treasure' },
    icon: icon('treasure', '5'),
    criterion: snap('treasuresCollected', 5),
    progress: p(5, 'treasures'),
    archipelago: ap,
  }),
  d({
    id: 'relationships.firstDate',
    name: 'First Date',
    description: 'Start dating someone.',
    category: 'relationships',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: 480, section: 'Relationships' },
    icon: icon('heart', '<3'),
    criterion: event('relationship:dated'),
    archipelago: ap,
  }),
  d({
    id: 'relationships.married',
    name: 'Till Death',
    description: 'Marry an NPC.',
    category: 'relationships',
    difficulty: 'hard',
    prerequisites: ['relationships.firstDate'],
    tree: { x: -560, y: 480, section: 'Relationships' },
    icon: icon('heart', 'R'),
    criterion: event('relationship:married'),
    archipelago: ap,
  }),
  d({
    id: 'relationships.child',
    name: 'Family Expansion',
    description: 'Have or adopt a child.',
    category: 'relationships',
    difficulty: 'hard',
    prerequisites: ['relationships.married'],
    tree: { x: -700, y: 420, section: 'Relationships' },
    icon: icon('baby', 'B'),
    criterion: event('relationship:child'),
    archipelago: ap,
  }),
  d({
    id: 'relationships.motherLove',
    name: "Knowing a Mother's Love",
    description: 'Hold your child close and feel the world soften.',
    category: 'relationships',
    difficulty: 'hard',
    prerequisites: ['relationships.child'],
    tree: { x: -700, y: 480, section: 'Relationships' },
    icon: icon('baby', 'M'),
    criterion: event('relationship:motherLove'),
    archipelago: ap,
  }),
  d({
    id: 'relationships.divorced',
    name: 'Record Closed',
    description: 'Divorce an NPC.',
    category: 'relationships',
    difficulty: 'hard',
    prerequisites: ['relationships.married'],
    tree: { x: -700, y: 540, section: 'Relationships' },
    icon: icon('divorce', 'X'),
    criterion: event('relationship:divorced'),
    archipelago: ap,
  }),
  d({
    id: 'fishing.firstCatch',
    name: "Gone Fishin'",
    description: 'Catch a fish.',
    category: 'fishing',
    difficulty: 'easy',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 600, section: 'Fishing' },
    icon: icon('fish', 'F'),
    criterion: event('fishing:caught'),
    archipelago: ap,
  }),
  d({
    id: 'fishing.rare',
    name: 'Rare Bite',
    description: 'Catch a rare fish.',
    category: 'fishing',
    difficulty: 'medium',
    prerequisites: ['fishing.firstCatch'],
    tree: { x: -420, y: 720, section: 'Fishing' },
    icon: icon('fish', 'R', 'rare'),
    criterion: event('fishing:caught', { rarity: 'rare' }),
    archipelago: ap,
  }),
  d({
    id: 'fishing.legendary',
    name: 'Legend of the Lake',
    description: 'Catch a legendary fish.',
    category: 'fishing',
    difficulty: 'legendary',
    prerequisites: ['fishing.rare'],
    tree: { x: -560, y: 720, section: 'Fishing' },
    icon: icon('fish', 'L', 'legendary'),
    criterion: event('fishing:caught', { rarity: 'legendary' }),
    archipelago: ap,
  }),
  d({
    id: 'fishing.completeJournal',
    name: 'Complete Catch Journal',
    description: 'Catch every fish type.',
    category: 'fishing',
    difficulty: 'legendary',
    prerequisites: ['fishing.legendary'],
    tree: { x: -700, y: 720, section: 'Fishing' },
    icon: icon('fishJournal', 'ALL'),
    criterion: snap('fishTypesCaught', TOTAL_FISH_COUNT),
    progress: p(TOTAL_FISH_COUNT, 'fish'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.firstArtifact',
    name: 'Dusty Treasure',
    description: 'Recover an artifact.',
    category: 'archaeology',
    difficulty: 'easy',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 840, section: 'Archaeology' },
    icon: icon('artifact', 'AR'),
    criterion: event('archaeology:artifactRecovered'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.chain3',
    name: 'Chain Reaction',
    description: 'Reach archaeology chain 3.',
    category: 'archaeology',
    difficulty: 'medium',
    prerequisites: ['archaeology.firstArtifact'],
    tree: { x: -420, y: 840, section: 'Archaeology' },
    icon: icon('artifact', 'x3'),
    criterion: event('archaeology:chainReached'),
    progress: p(3, 'chain'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.chain5',
    name: 'Excavation Combo',
    description: 'Reach archaeology chain 5.',
    category: 'archaeology',
    difficulty: 'hard',
    prerequisites: ['archaeology.chain3'],
    tree: { x: -560, y: 840, section: 'Archaeology' },
    icon: icon('artifact', 'x5'),
    criterion: event('archaeology:chainReached'),
    progress: p(5, 'chain'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.depth25',
    name: 'Deep Dig',
    description: 'Reach archaeology depth 25.',
    category: 'archaeology',
    difficulty: 'medium',
    prerequisites: ['archaeology.firstArtifact'],
    tree: { x: -420, y: 960, section: 'Archaeology' },
    icon: icon('artifact', '25'),
    criterion: event('archaeology:depthReached'),
    progress: p(25, 'depth'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.depth50',
    name: 'Too Deep',
    description: 'Reach archaeology depth 50.',
    category: 'archaeology',
    difficulty: 'hard',
    prerequisites: ['archaeology.depth25'],
    tree: { x: -560, y: 960, section: 'Archaeology' },
    icon: icon('artifact', '50'),
    criterion: event('archaeology:depthReached'),
    progress: p(50, 'depth'),
    archipelago: ap,
  }),
  d({
    id: 'archaeology.allArtifacts',
    name: 'Museum Wing',
    description: 'Recover every artifact.',
    category: 'archaeology',
    difficulty: 'legendary',
    prerequisites: ['archaeology.firstArtifact'],
    tree: { x: -700, y: 900, section: 'Archaeology' },
    icon: icon('artifactCollection', 'ALL'),
    criterion: snap('artifactsOwned', TOTAL_ARTIFACT_COUNT),
    progress: p(TOTAL_ARTIFACT_COUNT, 'artifacts'),
    archipelago: ap,
  }),
  d({
    id: 'equipment.equipFirst',
    name: 'Dress for the Job',
    description: 'Equip any equipment item.',
    category: 'equipment',
    difficulty: 'easy',
    prerequisites: ['core.firstApple'],
    tree: { x: 140, y: 120, section: 'Equipment' },
    icon: icon('equipment', 'E'),
    criterion: event('equipment:equipped'),
    archipelago: ap,
  }),
  d({
    id: 'equipment.fullLoadout',
    name: 'Full Loadout',
    description: 'Fill every equipment slot.',
    category: 'equipment',
    difficulty: 'hard',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 280, y: 120, section: 'Equipment' },
    icon: icon('loadout', 'ALL'),
    criterion: snap('equippedSlotCount', EQUIPMENT_SLOTS.length),
    progress: p(EQUIPMENT_SLOTS.length, 'slots'),
    archipelago: ap,
  }),
  d({
    id: 'equipment.secondChance',
    name: 'Second Chances',
    description: 'Gain an extra life after the run starts.',
    category: 'equipment',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 280, y: 240, section: 'Equipment' },
    icon: icon('heart', '+1'),
    criterion: event('extraLife:gained'),
    archipelago: ap,
  }),
  d({
    id: 'combat.gunKill',
    name: 'Formal Disagreement',
    description: 'Kill an enemy or NPC with a gun.',
    category: 'combat',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 420, y: 120, section: 'Combat' },
    icon: icon('gun', 'G'),
    criterion: event('combat:gunKill'),
    archipelago: ap,
  }),
  d({
    id: 'combat.katanaSmite',
    name: 'Cut Through Bureaucracy',
    description: 'Use the Jade Katana to smite a wall.',
    category: 'combat',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 420, y: 240, section: 'Combat' },
    icon: icon('katana', 'K'),
    criterion: event('combat:jadeKatanaWallSmite'),
    archipelago: ap,
  }),
  d({
    id: 'food.drunk',
    name: 'Get Drunk',
    description: 'Drink beer or wine.',
    category: 'equipment',
    difficulty: 'easy',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 280, y: 360, section: 'Items' },
    icon: icon('drink', 'D'),
    criterion: event('item:consumed', { itemId: 'beer|wine' }),
    archipelago: ap,
  }),
  d({
    id: 'food.comboMeal',
    name: 'Combo Meal',
    description: 'Eat a Snake Burger, Snake Fries, and Snake Nuggets in one run.',
    category: 'equipment',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 420, y: 360, section: 'Items' },
    icon: icon('fastFood', 'M'),
    criterion: event('item:consumed', {
      itemId: 'food-snake-burger|food-snake-fries|food-snake-nuggets',
    }),
    progress: p(3, 'meal items'),
    archipelago: ap,
  }),
  d({
    id: 'boss.defeatFreakDennis',
    name: 'Freak Off',
    description: 'Defeat Freak Dennis.',
    category: 'bosses',
    difficulty: 'hard',
    prerequisites: ['stats.score1000'],
    tree: { x: 420, y: -240, section: 'Bosses' },
    icon: icon('boss', 'FD'),
    criterion: event('boss:defeated', { bossKind: 'freak-dennis' }),
    archipelago: ap,
  }),
  d({
    id: 'boss.defeatFreakerDennis',
    name: 'Freakier Friday',
    description: 'Defeat Freaker Dennis.',
    category: 'bosses',
    difficulty: 'legendary',
    prerequisites: ['boss.defeatFreakDennis'],
    tree: { x: 560, y: -240, section: 'Bosses' },
    icon: icon('boss', 'F2'),
    criterion: event('boss:defeated', { bossKind: 'freaker-dennis' }),
    archipelago: ap,
  }),
  d({
    id: 'boss.damageJasonVulnerable',
    name: "Now He's Vulnerable",
    description: 'Hurt Jason Statham while vulnerable.',
    category: 'bosses',
    difficulty: 'hard',
    prerequisites: ['boss.defeatFreakDennis'],
    tree: { x: 560, y: -360, section: 'Bosses' },
    icon: icon('boss', 'JV'),
    criterion: event('boss:jasonVulnerableDamaged'),
    archipelago: ap,
  }),
  d({
    id: 'boss.defeatJasonStatham',
    name: 'Statham Must Fall',
    description: 'Defeat Jason Statham.',
    category: 'bosses',
    difficulty: 'legendary',
    prerequisites: ['boss.damageJasonVulnerable'],
    tree: { x: 700, y: -360, section: 'Bosses' },
    icon: icon('boss', 'JS'),
    criterion: event('boss:defeated', { bossKind: 'jason-statham' }),
    archipelago: ap,
  }),
  d({
    id: 'divine.meetAngel',
    name: 'Meet the Angel',
    description: 'Encounter the normal Angel death route.',
    category: 'bosses',
    difficulty: 'medium',
    prerequisites: ['equipment.secondChance'],
    tree: { x: 560, y: 240, section: 'Divine' },
    icon: icon('angel', 'A', 'normal'),
    criterion: event('divine:angelEncountered', { angelKind: 'normal' }),
    archipelago: ap,
  }),
  d({
    id: 'divine.meetGoblinAngel',
    name: 'Meet the Goblin Angel',
    description: 'Encounter the Goblin Angel rescue route.',
    category: 'bosses',
    difficulty: 'hard',
    prerequisites: ['divine.meetAngel'],
    tree: { x: 700, y: 240, section: 'Divine' },
    icon: icon('angel', 'GA', 'goblin'),
    criterion: event('divine:angelEncountered', { angelKind: 'goblin' }),
    archipelago: ap,
  }),
  d({
    id: 'divine.snakeOutOfHell',
    name: 'Like a Snake Out of Hell',
    description: 'Escape Hell.',
    category: 'bosses',
    difficulty: 'legendary',
    prerequisites: ['divine.meetAngel'],
    tree: { x: 840, y: 240, section: 'Divine' },
    icon: icon('angel', 'HELL', 'demon'),
    criterion: event('divine:escapedHell', { itemId: 'get-out-of-hell-free-card' }),
    archipelago: ap,
  }),
  d({
    id: 'rivals.length25',
    name: 'Let Them Cook',
    description: 'Let a rival or roaming snake reach length 25.',
    category: 'rivals',
    difficulty: 'medium',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -280, y: 120, section: 'World' },
    icon: icon('snake', 'R25'),
    criterion: event('rivalSnake:lengthReached'),
    progress: p(25, 'rival length'),
    archipelago: ap,
  }),
  d({
    id: 'skillTree.oneBranch',
    name: 'Specialist',
    description: 'Complete one skill-tree branch.',
    category: 'skillTree',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 420, y: 480, section: 'Skills' },
    icon: icon('skillTree', '1'),
    criterion: snap('skillBranchesCompleted', 1),
    progress: p(1, 'branches'),
    archipelago: ap,
  }),
  d({
    id: 'skillTree.allBranches',
    name: 'Fully Realized Snake',
    description: 'Complete every real skill-tree branch.',
    category: 'skillTree',
    difficulty: 'legendary',
    prerequisites: ['skillTree.oneBranch'],
    tree: { x: 560, y: 480, section: 'Skills' },
    icon: icon('skillTree', 'ALL'),
    criterion: snap('skillBranchesCompleted', Number.MAX_SAFE_INTEGER),
    progress: p(1, 'branches'),
    archipelago: ap,
  }),
  d({
    id: 'caves.appleRushClear',
    name: 'Core Before the Collapse',
    description: 'Devour every apple in a timed challenge cave before it collapses.',
    category: 'caves',
    difficulty: 'hard',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -420, y: 120, section: 'World' },
    icon: icon('caveRush', 'C!'),
    criterion: event('cave:appleRushCleared'),
    archipelago: ap,
  }),
  d({
    id: 'companions.first',
    name: 'Coil and Company',
    description: 'Gain a companion.',
    category: 'relationships',
    difficulty: 'medium',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: 600, section: 'Society' },
    icon: icon('companion', '2S'),
    criterion: event('companion:acquired'),
    archipelago: ap,
  }),
  d({
    id: 'shops.generalBuyout',
    name: 'Nothing Left but the Counter',
    description: 'Buy every item and permanent unlock from one general shopkeeper.',
    category: 'towns',
    difficulty: 'hard',
    prerequisites: ['towns.openGate'],
    tree: { x: -560, y: -360, section: 'Society' },
    icon: icon('shopBuyout', '$0'),
    criterion: event('shop:generalBoughtOut'),
    archipelago: ap,
  }),
  d({
    id: 'cards.fullDeck',
    name: 'Full Deck',
    description: 'Collect every card.',
    category: 'cards',
    difficulty: 'legendary',
    prerequisites: ['towns.openGate'],
    tree: { x: -420, y: -720, section: 'Games' },
    icon: icon('card', 'ALL', 'deck'),
    criterion: snap('cardsOwned', TOTAL_CARD_COUNT),
    progress: p(TOTAL_CARD_COUNT, 'cards'),
    archipelago: ap,
  }),
  ...CARD_TABLES.map((table, index) =>
    d({
      id: `cards.win.${table.id}`,
      name: `Card Sharp: ${table.name}`,
      description: `Win at ${table.name}.`,
      category: 'cards',
      difficulty: 'medium',
      prerequisites: ['towns.openGate'],
      tree: { x: -560 - index * 140, y: -720, section: 'Games' },
      icon: icon('card', `C${index + 1}`, table.id),
      criterion: event('cards:tableWon', { tableId: table.id }),
      archipelago: ap,
    }),
  ),
  d({
    id: 'equipment.cowbell200',
    name: 'For Whom the Bell Coils',
    description: 'Walk 200 tiles with the cowbell equipped.',
    category: 'equipment',
    difficulty: 'medium',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 560, y: 600, section: 'Gear' },
    icon: icon('cowbell', 'CB'),
    criterion: snap('cowbellTilesWalked', 200),
    progress: p(200, 'tiles'),
    archipelago: ap,
  }),
  d({
    id: 'equipment.wardTrinity',
    name: 'Terms and Conditions Apply',
    description: 'Hold wards against three different damage types at once.',
    category: 'equipment',
    difficulty: 'hard',
    prerequisites: ['equipment.equipFirst'],
    tree: { x: 700, y: 600, section: 'Gear' },
    icon: icon('wards', 'W3'),
    criterion: snap('wardDamageTypesHeld', 3),
    progress: p(3, 'ward types'),
    archipelago: ap,
  }),
  d({
    id: 'system.zoomFlurry',
    name: 'Enhance! Enhance!',
    description: 'Fully zoom in and fully zoom out three times.',
    category: 'skillTree',
    difficulty: 'medium',
    scoreReward: 50,
    tree: { x: 980, y: 720, section: 'System' },
    icon: icon('zoom', 'Z!'),
    criterion: event('ui:achievementZoomFlurry'),
    archipelago: ap,
  }),
  d({
    id: 'exploration.trainSixZones',
    name: 'Express Across the Map',
    description: 'Ride the bullet train at least 6 zones in one trip.',
    category: 'exploration',
    difficulty: 'medium',
    prerequisites: ['exploration.rooms25'],
    tree: { x: -700, y: -600, section: 'World' },
    icon: icon('biome', 'TR'),
    criterion: snap('trainZonesTraveled', 6),
    progress: p(6, 'zones'),
    archipelago: ap,
  }),
] as readonly AchievementDefinition[];
