import { ARTIFACT_DEFINITIONS } from '../artifacts/artifacts.js';
import { CARD_DEFINITIONS, CARD_TABLES } from '../cards/cardGame.js';
import type { AchievementDefinition, AchievementIconSpec } from './achievementTypes.js';

const icon = (kind: AchievementIconSpec['kind'], fallbackGlyph: string, variant?: string): AchievementIconSpec => ({ kind, fallbackGlyph, variant });
const ap = { enabledByDefault: true } as const;

export const DISCOVERABLE_BIOME_COUNT = 10;
export const TOTAL_CARD_COUNT = CARD_DEFINITIONS.length;
export const TOTAL_ARTIFACT_COUNT = ARTIFACT_DEFINITIONS.length;

const definitions: AchievementDefinition[] = [
  { id: 'core.firstApple', name: 'A Classic', description: 'Eat your first apple.', category: 'core', difficulty: 'tutorial', tree: { x: 0, y: 0, section: 'The Snake' }, icon: icon('apple', 'A'), criterion: { kind: 'event', eventType: 'apple:eaten' }, archipelago: ap },
  { id: 'core.bigBite', name: 'Big Bite', description: 'Eat a gold apple.', category: 'core', difficulty: 'easy', prerequisites: ['core.firstApple'], tree: { x: 140, y: 0, section: 'The Snake' }, icon: icon('apple', 'G', 'gold'), criterion: { kind: 'event', eventType: 'apple:eaten', match: { appleTypeId: 'gold' } }, archipelago: ap },
  { id: 'stats.score500', name: 'Making Points', description: 'Reach 500 score.', category: 'stats', difficulty: 'easy', prerequisites: ['core.firstApple'], tree: { x: 140, y: -120, section: 'Growth' }, icon: icon('snake', '5'), criterion: { kind: 'score', target: 500 }, progress: { target: 500, label: 'score' }, archipelago: ap },
  { id: 'stats.score1000', name: 'Four Digits', description: 'Reach 1,000 score.', category: 'stats', difficulty: 'medium', prerequisites: ['stats.score500'], tree: { x: 280, y: -120, section: 'Growth' }, icon: icon('snake', '1K'), criterion: { kind: 'score', target: 1000 }, progress: { target: 1000, label: 'score' }, archipelago: ap },
  { id: 'stats.score10000', name: 'Score Lord', description: 'Reach 10,000 score.', category: 'stats', difficulty: 'legendary', prerequisites: ['stats.score1000'], tree: { x: 420, y: -120, section: 'Growth' }, icon: icon('snake', '10K'), criterion: { kind: 'score', target: 10000 }, progress: { target: 10000, label: 'score' }, archipelago: ap },
  { id: 'stats.length100', name: 'Long Snake', description: 'Reach length 100.', category: 'stats', difficulty: 'medium', prerequisites: ['core.bigBite'], tree: { x: 280, y: 0, section: 'Growth' }, icon: icon('snake', '100'), criterion: { kind: 'length', target: 100 }, progress: { target: 100, label: 'length' }, archipelago: ap },
  { id: 'stats.length2500', name: 'World Serpent', description: 'Reach length 2,500.', category: 'stats', difficulty: 'legendary', prerequisites: ['stats.length100'], tree: { x: 420, y: 0, section: 'Growth' }, icon: icon('snake', '2.5K'), criterion: { kind: 'length', target: 2500 }, progress: { target: 2500, label: 'length' }, archipelago: ap },
  { id: 'equipment.equipFirst', name: 'Dress for the Job', description: 'Equip any piece of equipment.', category: 'equipment', difficulty: 'easy', prerequisites: ['core.firstApple'], tree: { x: 140, y: 120, section: 'Equipment' }, icon: icon('equipment', 'E'), criterion: { kind: 'event', eventType: 'equipment:equipped' }, archipelago: ap },
  { id: 'equipment.secondChance', name: 'Second Chances', description: 'Gain an extra life.', category: 'equipment', difficulty: 'medium', prerequisites: ['equipment.equipFirst'], tree: { x: 280, y: 120, section: 'Equipment' }, icon: icon('heart', '+1'), criterion: { kind: 'event', eventType: 'extraLife:gained' }, archipelago: ap },
  { id: 'equipment.swim25', name: 'Olympic Swimmer', description: 'Swim across 25 water tiles.', category: 'equipment', difficulty: 'medium', prerequisites: ['equipment.equipFirst'], tree: { x: 280, y: 240, section: 'Equipment' }, icon: icon('water', 'W'), criterion: { kind: 'waterTiles', target: 25 }, progress: { target: 25, label: 'water tiles' }, archipelago: ap },
  { id: 'food.drunk', name: 'Get Drunk', description: 'Drink beer or wine.', category: 'equipment', difficulty: 'easy', prerequisites: ['equipment.equipFirst'], tree: { x: 280, y: 360, section: 'Equipment' }, icon: icon('drink', 'D'), criterion: { kind: 'event', eventType: 'item:consumed', match: { itemId: 'beer|wine' } }, archipelago: ap },
  { id: 'food.comboMeal', name: 'Combo Meal', description: 'Eat a Snake Burger, Snake Fries, and Snake Nuggets in one run.', category: 'equipment', difficulty: 'medium', prerequisites: ['equipment.equipFirst'], tree: { x: 420, y: 360, section: 'Equipment' }, icon: icon('fastFood', 'M'), criterion: { kind: 'event', eventType: 'item:consumed', match: { itemId: 'food-snake-burger|food-snake-fries|food-snake-nuggets' } }, progress: { target: 3, label: 'meal items' }, archipelago: ap },
  { id: 'exploration.rooms25', name: 'Road Trip', description: 'Visit 25 rooms.', category: 'exploration', difficulty: 'easy', prerequisites: ['core.firstApple'], tree: { x: -140, y: -120, section: 'World' }, icon: icon('biome', '25'), criterion: { kind: 'rooms', target: 25 }, progress: { target: 25, label: 'rooms' }, archipelago: ap },
  { id: 'towns.enterFirst', name: 'City Limits', description: 'Enter a town.', category: 'towns', difficulty: 'easy', prerequisites: ['exploration.rooms25'], tree: { x: -280, y: -120, section: 'World' }, icon: icon('town', 'T'), criterion: { kind: 'event', eventType: 'town:entered' }, archipelago: ap },
  { id: 'biomes.discoverAll', name: 'World Tour', description: 'Discover every biome.', category: 'biomes', difficulty: 'hard', prerequisites: ['exploration.rooms25'], tree: { x: -280, y: -240, section: 'World' }, icon: icon('biome', 'ALL'), criterion: { kind: 'biomes', target: DISCOVERABLE_BIOME_COUNT }, progress: { target: DISCOVERABLE_BIOME_COUNT, label: 'biomes' }, archipelago: ap },
  { id: 'caves.enterFirst', name: 'Below the Surface', description: 'Enter a cave.', category: 'caves', difficulty: 'medium', prerequisites: ['exploration.rooms25'], tree: { x: -280, y: 0, section: 'World' }, icon: icon('cave', 'C'), criterion: { kind: 'event', eventType: 'cave:entered' }, archipelago: ap },
  { id: 'guild.initiation', name: 'In the Guild', description: 'Complete Thieves Guild initiation.', category: 'guild', difficulty: 'medium', prerequisites: ['towns.enterFirst'], tree: { x: -420, y: -120, section: 'Society' }, icon: icon('guild', 'TG'), criterion: { kind: 'event', eventType: 'guild:initiationCompleted' }, archipelago: ap },
  { id: 'relationships.firstDate', name: 'First Date', description: 'Start dating someone.', category: 'relationships', difficulty: 'medium', prerequisites: ['towns.enterFirst'], tree: { x: -420, y: 0, section: 'Society' }, icon: icon('heart', '<3'), criterion: { kind: 'event', eventType: 'relationship:dated' }, archipelago: ap },
  { id: 'relationships.married', name: 'Till Death', description: 'Marry an NPC.', category: 'relationships', difficulty: 'hard', prerequisites: ['relationships.firstDate'], tree: { x: -560, y: 0, section: 'Society' }, icon: icon('heart', 'R'), criterion: { kind: 'event', eventType: 'relationship:married' }, archipelago: ap },
  { id: 'relationships.child', name: 'Family Expansion', description: 'Have a baby.', category: 'relationships', difficulty: 'hard', prerequisites: ['relationships.married'], tree: { x: -700, y: 0, section: 'Society' }, icon: icon('baby', 'B'), criterion: { kind: 'event', eventType: 'relationship:child' }, archipelago: ap },
  { id: 'fishing.firstCatch', name: "Gone Fishin'", description: 'Catch a fish.', category: 'fishing', difficulty: 'easy', prerequisites: ['exploration.rooms25'], tree: { x: -280, y: 120, section: 'Trades' }, icon: icon('fish', 'F'), criterion: { kind: 'event', eventType: 'fishing:caught' }, archipelago: ap },
  { id: 'fishing.legendary', name: 'Legend of the Lake', description: 'Catch a legendary fish.', category: 'fishing', difficulty: 'legendary', prerequisites: ['fishing.firstCatch'], tree: { x: -420, y: 120, section: 'Trades' }, icon: icon('fish', 'L'), criterion: { kind: 'event', eventType: 'fishing:caught', match: { rarity: 'legendary' } }, archipelago: ap },
  { id: 'archaeology.firstArtifact', name: 'Dusty Treasure', description: 'Recover an artifact.', category: 'archaeology', difficulty: 'easy', prerequisites: ['caves.enterFirst'], tree: { x: -420, y: 240, section: 'Trades' }, icon: icon('artifact', 'AR'), criterion: { kind: 'event', eventType: 'archaeology:artifactRecovered' }, archipelago: ap },
  { id: 'archaeology.depth25', name: 'Deep Dig', description: 'Reach archaeology depth 25.', category: 'archaeology', difficulty: 'medium', prerequisites: ['archaeology.firstArtifact'], tree: { x: -560, y: 240, section: 'Trades' }, icon: icon('artifact', '25'), criterion: { kind: 'event', eventType: 'archaeology:depthReached' }, progress: { target: 25, label: 'depth' }, archipelago: ap },
  { id: 'archaeology.chain5', name: 'Chain Reaction', description: 'Reach an archaeology chain of 5.', category: 'archaeology', difficulty: 'medium', prerequisites: ['archaeology.firstArtifact'], tree: { x: -560, y: 360, section: 'Trades' }, icon: icon('artifact', 'x5'), criterion: { kind: 'event', eventType: 'archaeology:chainReached' }, progress: { target: 5, label: 'chain' }, archipelago: ap },
  { id: 'cards.fullDeck', name: 'Full Deck', description: 'Collect every card.', category: 'cards', difficulty: 'legendary', prerequisites: ['towns.enterFirst'], tree: { x: -420, y: -240, section: 'Games' }, icon: icon('card', '52'), criterion: { kind: 'cards', target: TOTAL_CARD_COUNT }, progress: { target: TOTAL_CARD_COUNT, label: 'cards' }, archipelago: { enabledByDefault: false } },
  { id: 'boss.defeatFreakDennis', name: 'Freak Off', description: 'Defeat Freak Dennis.', category: 'bosses', difficulty: 'hard', prerequisites: ['stats.score1000'], tree: { x: 420, y: -240, section: 'Bosses' }, icon: icon('boss', 'FD'), criterion: { kind: 'event', eventType: 'boss:defeated', match: { bossKind: 'freak-dennis' } }, archipelago: ap },
  { id: 'boss.defeatFreakerDennis', name: 'Freakier Friday', description: 'Defeat Freaker Dennis.', category: 'bosses', difficulty: 'legendary', prerequisites: ['boss.defeatFreakDennis'], tree: { x: 560, y: -240, section: 'Bosses' }, icon: icon('boss', 'F2'), criterion: { kind: 'event', eventType: 'boss:defeated', match: { bossKind: 'freaker-dennis' } }, archipelago: ap },
  { id: 'boss.damageJasonVulnerable', name: "Now He's Vulnerable", description: 'Hurt Jason Statham while he is vulnerable.', category: 'bosses', difficulty: 'hard', prerequisites: ['boss.defeatFreakDennis'], tree: { x: 560, y: -360, section: 'Bosses' }, icon: icon('boss', 'JV'), criterion: { kind: 'event', eventType: 'boss:jasonVulnerableDamaged' }, archipelago: ap },
  { id: 'boss.defeatJasonStatham', name: 'Statham Must Fall', description: 'Defeat Jason Statham.', category: 'bosses', difficulty: 'legendary', prerequisites: ['boss.damageJasonVulnerable'], tree: { x: 700, y: -360, section: 'Bosses' }, icon: icon('boss', 'JS'), criterion: { kind: 'event', eventType: 'boss:defeated', match: { bossKind: 'jason-statham' } }, archipelago: ap },
  { id: 'rivals.length25', name: 'Let Them Cook', description: 'Let a rival snake reach length 25.', category: 'rivals', difficulty: 'medium', prerequisites: ['exploration.rooms25'], tree: { x: -140, y: 120, section: 'World' }, icon: icon('snake', 'R25'), criterion: { kind: 'event', eventType: 'rivalSnake:lengthReached' }, progress: { target: 25, label: 'rival length' }, archipelago: ap },
  { id: 'skillTree.oneBranch', name: 'Specialist', description: 'Complete one skill-tree branch.', category: 'skillTree', difficulty: 'medium', prerequisites: ['equipment.equipFirst'], tree: { x: 420, y: 120, section: 'Skills' }, icon: icon('skillTree', '1'), criterion: { kind: 'skillBranches', target: 1 }, progress: { target: 1, label: 'branches' }, archipelago: ap },
  { id: 'skillTree.allBranches', name: 'Fully Realized Snake', description: 'Complete every skill-tree branch.', category: 'skillTree', difficulty: 'legendary', prerequisites: ['skillTree.oneBranch'], tree: { x: 560, y: 120, section: 'Skills' }, icon: icon('skillTree', 'ALL'), criterion: { kind: 'skillBranches', target: 3 }, progress: { target: 3, label: 'branches' }, archipelago: ap },
];

for (const [index, table] of CARD_TABLES.entries()) {
  definitions.push({
    id: `cards.win.${table.id}`,
    name: `Card Sharp: ${table.name}`,
    description: `Win at ${table.name}.`,
    category: 'cards', difficulty: 'medium', prerequisites: ['towns.enterFirst'],
    tree: { x: -420 - index * 140, y: -360, section: 'Games' },
    icon: icon('card', `C${index + 1}`),
    criterion: { kind: 'event', eventType: 'cards:tableWon', match: { tableId: table.id } },
    archipelago: ap,
  });
}

export const ACHIEVEMENT_DEFINITIONS = definitions as readonly AchievementDefinition[];
