import type { ActorVoiceEntry } from '../voiceTypes.js';

export const ASK_AROUND_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'around-rumor-quest-resident',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'They tell it like they helped, which is the traditional civic reward.',
    text: '{{rumor}} The town has already agreed it was obvious after somebody else did it.',
    priority: 106,
    roles: ['resident', 'questGiver', 'hunter', 'cook'],
    memoryTags: ['quest'],
    tags: ['rumor', 'quest', 'town'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-quest-shop',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Success is wonderful. It creates customers with score and stories with no receipts.',
    priority: 108,
    roles: ['shopkeeper', 'bartender', 'goblinMerchant'],
    memoryTags: ['quest'],
    tags: ['rumor', 'quest', 'shop'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-taming-hunter',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'They glance toward the nearest patch of wilderness before continuing.',
    text: '{{rumor}} Animals do not follow titles. Whatever happened, the animal believed it.',
    priority: 110,
    roles: ['hunter', 'trapper', 'fisher', 'resident'],
    memoryTags: ['taming'],
    tags: ['rumor', 'animal', 'taming'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-hunt-cook',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} The forest calls it tragedy. The kitchen calls it inventory.',
    priority: 109,
    roles: ['cook', 'butcher', 'hunter', 'bartender'],
    memoryTags: ['hunting'],
    tags: ['rumor', 'animal', 'hunting'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-cooking',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'They inhale as if the evidence might still be in the air.',
    text: '{{rumor}} Nobody agrees on the recipe, but several people have claimed the leftovers.',
    priority: 102,
    roles: ['cook', 'bartender', 'resident', 'shopkeeper'],
    memoryTags: ['cooking'],
    tags: ['rumor', 'food', 'cooking'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-gate-guard',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'The guard recites the unofficial version with official posture.',
    text: '{{rumor}} A gate opening is never news until somebody dislikes who passed through it.',
    priority: 114,
    roles: ['guard', 'gateGuard'],
    memoryTags: ['gate'],
    tags: ['rumor', 'town', 'gate', 'law'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-revival-religious',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Theology has requested a little time to update the paperwork.',
    priority: 122,
    roles: ['goblinPriest', 'potionMaker', 'angel', 'resident'],
    memoryTags: ['revival'],
    tags: ['rumor', 'revival', 'religion'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-revival-deadpan',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Apparently death is a door now. Somebody should oil the hinge.',
    priority: 120,
    personalityTags: ['deadpan', 'cynical', 'paranoid'],
    memoryTags: ['revival'],
    tags: ['rumor', 'revival'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-guard-crime',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'The guard checks the street before answering.',
    text: 'People are calling it an incident. Incidents are crimes with better posture.',
    priority: 112,
    roles: ['guard', 'gateGuard'],
    memoryTags: ['crime'],
    tags: ['rumor', 'crime', 'law'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-goblin-crime',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: 'Unlicensed chaos. Beautiful. Illegal. Taxable.',
    priority: 111,
    personalityTags: ['goblin'],
    memoryTags: ['crime'],
    tags: ['rumor', 'crime', 'goblin'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-player-eaten-coward',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'They lower their voice and raise their distance.',
    text: 'People are saying someone went into your mouth with a name and came out as a warning.',
    priority: 120,
    personalityTags: ['cowardly', 'paranoid'],
    memoryTags: ['eaten', 'humanoid'],
    tags: ['rumor', 'eaten', 'fear'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-player-eaten-shop',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: 'The bandits are calling it a recruitment issue. I am calling it medicine with teeth.',
    priority: 118,
    roles: ['shopkeeper', 'bartender'],
    memoryTags: ['eaten', 'humanoid'],
    tags: ['rumor', 'eaten', 'shop'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-player-eaten-goblin',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: 'Bandit-based healthcare is now a phrase people are trying not to repeat.',
    priority: 119,
    personalityTags: ['goblin'],
    memoryTags: ['eaten', 'humanoid'],
    tags: ['rumor', 'eaten', 'goblin'],
    source: 'rumor',
  },
  {
    id: 'around-faction-human-goblin-guard',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'The goblins are allowed through the east gate. Their receipts are not.',
    priority: 104,
    roles: ['guard', 'gateGuard'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-goblin',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    beat: 'The goblin folds a receipt into something almost religious.',
    text: 'Humans call it a tense truce. Goblins call it unpaid violence.',
    priority: 105,
    personalityTags: ['goblin'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-deadpan',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'The guards and goblins are doing peace again. It involves fewer smiles than advertised.',
    priority: 101,
    personalityTags: ['deadpan'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-cynical',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'Both sides say they want order. That is how you know everyone brought weapons.',
    priority: 100,
    personalityTags: ['cynical', 'paranoid'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-market',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'The truce is quiet today. That usually means everyone is busy counting exits.',
    priority: 110,
    factionStates: ['tense', 'truce'],
    tags: ['faction', 'goblin', 'human', 'ambient'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-road',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'Human roads and goblin contracts both lead here. Neither admits responsibility.',
    priority: 109,
    factionStates: ['tense', 'truce'],
    tags: ['faction', 'goblin', 'human', 'ambient'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-gate',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'The gate stays open because closing it would make the argument too honest.',
    priority: 108,
    factionStates: ['tense', 'truce'],
    tags: ['faction', 'goblin', 'human', 'ambient'],
    source: 'faction',
  },
  {
    id: 'around-bandit-threat-guard',
    bucket: 'ask-around',
    topic: 'around.banditThreat',
    beat: 'The guard checks the gate before answering.',
    text: 'Bandits were seen near the market. Officially, we are monitoring. Unofficially, monitoring is what cowards call waiting.',
    priority: 122,
    roles: ['guard', 'gateGuard'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    tags: ['faction', 'bandit', 'danger'],
    source: 'faction',
  },
  {
    id: 'around-bandit-threat-goblin',
    bucket: 'ask-around',
    topic: 'around.banditThreat',
    text: 'Bandits approach. We have locked the ledgers and left the worthless merchandise visible.',
    priority: 123,
    personalityTags: ['goblin'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    tags: ['faction', 'bandit', 'goblin'],
    source: 'faction',
  },
  {
    id: 'around-bandit-threat-shop',
    bucket: 'ask-around',
    topic: 'around.banditThreat',
    text: 'Bandits near the market. Bad for safety, excellent for ward sales.',
    priority: 118,
    roles: ['shopkeeper', 'goblinMerchant'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    tags: ['faction', 'bandit', 'shop'],
    source: 'faction',
  },
  {
    id: 'around-wanted-guard',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Wanted posters do not gossip. People do it for them.',
    priority: 98,
    roles: ['guard', 'gateGuard'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'town'],
    source: 'faction',
  },
  {
    id: 'around-wanted-thief',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Three posters up, two witnesses lying, one grate happier. That is civic arithmetic.',
    priority: 96,
    roles: ['thief', 'thiefContact', 'guildContact'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'guild'],
    source: 'faction',
  },
  {
    id: 'around-king-guard',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'The King reaches town through forms, gates, and uniforms. That is how distance learns to give orders.',
    priority: 78,
    roles: ['guard', 'gateGuard'],
    requiresLore: 'king',
    tags: ['lore', 'king', 'law'],
    source: 'lore',
  },
  {
    id: 'around-king-goblin',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Bellgrave debt arrives pre-signed. Goblins respect the efficiency and resent the handwriting.',
    priority: 80,
    personalityTags: ['goblin'],
    requiresLore: 'king',
    tags: ['lore', 'king', 'goblin'],
    source: 'lore',
  },
  {
    id: 'around-king-civilian',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'People talk about the King when prices rise, roads close, or somebody official needs a distant excuse.',
    priority: 72,
    requiresLore: 'king',
    tags: ['lore', 'king', 'town'],
    source: 'lore',
  },
  {
    id: 'around-gossip-family',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} is family. You can tell because everyone lies about being fine in the same accent.',
    priority: 88,
    socialLinkKinds: ['family'],
    tags: ['social', 'family'],
    source: 'social',
  },
  {
    id: 'around-gossip-rival',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} and I disagree professionally, emotionally, and whenever either of us is awake.',
    priority: 86,
    socialLinkKinds: ['rival'],
    tags: ['social', 'rival'],
    source: 'social',
  },
  {
    id: 'around-gossip-debt-goblin',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} owes more than money. Money is just guilt with numbers.',
    priority: 89,
    personalityTags: ['goblin'],
    socialLinkKinds: ['debtor', 'creditor'],
    tags: ['social', 'debt', 'goblin'],
    source: 'social',
  },
  {
    id: 'around-shop-economy-danger',
    bucket: 'ask-around',
    topic: 'around.shopEconomy',
    text: 'Danger changes inventory. People buy rope before bravery and bandages after.',
    priority: 74,
    roles: ['shopkeeper', 'bartender', 'goblinMerchant'],
    tags: ['shop', 'danger'],
    source: 'fallback',
  },
  {
    id: 'around-town-practical',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Quiet roads are either safe or proud of themselves. I do not trust either kind.',
    priority: 18,
    personalityTags: ['practical', 'paranoid'],
    tags: ['town'],
    source: 'fallback',
  },
  {
    id: 'around-town-village',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Bandits do not raid poor villages for money. They raid us to practice.',
    priority: 12,
    roles: ['resident', 'cook', 'hunter'],
    tags: ['town', 'bandit'],
    source: 'fallback',
  },
  {
    id: 'around-town-market',
    bucket: 'ask-around',
    topic: 'around.shopEconomy',
    text: 'The market knows the mood before the mayor does. Count closed shutters, then count smiles.',
    priority: 34,
    roles: ['resident', 'shopkeeper', 'bartender', 'cook'],
    tags: ['town', 'shop'],
    source: 'fallback',
  },
  {
    id: 'around-town-gate',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'The gate is where news arrives tired and leaves expensive.',
    priority: 32,
    roles: ['guard', 'gateGuard', 'resident'],
    tags: ['town', 'gate'],
    source: 'fallback',
  },
  {
    id: 'around-town-neighbors',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: 'Neighbors are calm today, which means the arguments have moved indoors.',
    priority: 30,
    personalityTags: ['nosy', 'practical', 'kind'],
    tags: ['town', 'social'],
    source: 'fallback',
  },
  {
    id: 'around-town-king-quiet',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'The King is not in town, but his paperwork is. Paperwork travels better than mercy.',
    priority: 28,
    personalityTags: ['lawful', 'regal', 'cynical'],
    tags: ['town', 'king'],
    source: 'fallback',
  },
  {
    id: 'around-town-fallback',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'People are saying the day is normal. That is how a day starts lying.',
    priority: 1,
    tags: ['town'],
    source: 'fallback',
  },
];
