import type { ActorVoiceEntry } from '../voiceTypes.js';

export const ASK_PERSONAL_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'personal-family-practical',
    bucket: 'ask-personal',
    topic: 'personal.family',
    text: '{{target}} is family. I say that before they do something that makes it sound like slander.',
    priority: 120,
    socialLinkKinds: ['family'],
    personalityTags: ['practical', 'deadpan'],
    tags: ['social', 'family'],
    source: 'social',
  },
  {
    id: 'personal-family-kind',
    bucket: 'ask-personal',
    topic: 'personal.family',
    beat: 'They soften before they can make it useful.',
    text: '{{target}} is family. If they say they are fine, check twice.',
    priority: 120,
    socialLinkKinds: ['family'],
    personalityTags: ['kind', 'softhearted'],
    tags: ['social', 'family'],
    source: 'social',
  },
  {
    id: 'personal-social-rival',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} is my rival. They call it mutual respect because cowardice has syllables.',
    priority: 116,
    socialLinkKinds: ['rival'],
    tags: ['social', 'rival'],
    source: 'social',
  },
  {
    id: 'personal-social-creditor-goblin',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    beat: 'The goblin touches their ledger like a prayer book.',
    text: '{{target}} owes me. Not money only. Money is the polite part.',
    priority: 118,
    personalityTags: ['goblin'],
    socialLinkKinds: ['debtor', 'creditor'],
    tags: ['social', 'debt', 'goblin'],
    source: 'social',
  },
  {
    id: 'personal-insecurity-sharp',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    text: 'I tell jokes because silence keeps asking follow-up questions.',
    priority: 108,
    personalityTags: ['sharp', 'deadpan'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['soul', 'insecurity'],
    source: 'soul',
  },
  {
    id: 'personal-insecurity-kind',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    beat: 'They fold their hands until both look borrowed.',
    text: 'I worry being useful is the only reason anyone stays. Then someone needs soup, and I become convenient again.',
    priority: 108,
    personalityTags: ['kind', 'softhearted'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['soul', 'insecurity'],
    source: 'soul',
  },
  {
    id: 'personal-insecurity-regal',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    text: 'I was praised for courage on the day I was most afraid. Nobility begins there, apparently.',
    priority: 108,
    personalityTags: ['regal', 'brave'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['soul', 'insecurity'],
    source: 'soul',
  },
  {
    id: 'personal-longing-lonely',
    bucket: 'ask-personal',
    topic: 'personal.longing',
    text: 'I want to leave town and be missed for the correct reasons.',
    priority: 104,
    personalityTags: ['lonely', 'romantic', 'melancholy'],
    requiresSoul: 'any',
    revealsSoul: 'opinionHint',
    tags: ['soul', 'longing'],
    source: 'soul',
  },
  {
    id: 'personal-longing-practical',
    bucket: 'ask-personal',
    topic: 'personal.longing',
    text: 'I want one quiet morning where no one needs anything from me. That is not romance. That is fantasy.',
    priority: 103,
    personalityTags: ['practical'],
    requiresSoul: 'any',
    revealsSoul: 'opinionHint',
    tags: ['soul', 'longing'],
    source: 'soul',
  },
  {
    id: 'personal-wound-guard',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    beat: 'They adjust their badge like it has become heavier.',
    text: 'My father died enforcing a road tax. The form said accident. The road said nothing, which was legally wise.',
    priority: 114,
    roles: ['guard', 'gateGuard'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['soul', 'wound', 'king'],
    source: 'soul',
  },
  {
    id: 'personal-wound-goblin',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    beat: 'The goblin folds a receipt until it becomes almost religious.',
    text: 'My son died owing nothing. Do you understand how frightening that is? No debt, no thread. No proof he touched the world.',
    priority: 115,
    personalityTags: ['goblin'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['soul', 'wound', 'goblin'],
    source: 'soul',
  },
  {
    id: 'personal-wound-poetic',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    text: 'The King paved over our orchard. In spring, the road still smelled like apples. That was the cruelest part.',
    priority: 113,
    personalityTags: ['poetic', 'melancholy'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['soul', 'wound', 'king'],
    source: 'soul',
  },
  {
    id: 'personal-contradiction-bureaucratic',
    bucket: 'ask-personal',
    topic: 'personal.contradiction',
    text: 'I believe in forms because people are worse. I distrust forms because people made them.',
    priority: 102,
    personalityTags: ['bureaucratic', 'lawful'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['soul', 'contradiction'],
    source: 'soul',
  },
  {
    id: 'personal-contradiction-violent',
    bucket: 'ask-personal',
    topic: 'personal.contradiction',
    text: 'I like peace best after it has proved it can survive a fight.',
    priority: 102,
    personalityTags: ['violent', 'brave'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['soul', 'contradiction'],
    source: 'soul',
  },
  {
    id: 'personal-secret-royal',
    bucket: 'ask-personal',
    topic: 'personal.secret',
    beat: 'They check the street before speaking.',
    text: 'My name was not always Vell. If the crown asks, I drowned twenty years ago.',
    priority: 128,
    requiresSoul: 'secret',
    requiresLore: 'king',
    revealsSoul: 'secret',
    tags: ['soul', 'secret', 'king'],
    source: 'lore',
  },
  {
    id: 'personal-secret-debt',
    bucket: 'ask-personal',
    topic: 'personal.secret',
    text: 'I pay under a false family name. Do not look impressed. Shame is cheaper in bulk.',
    priority: 116,
    requiresSoul: 'secret',
    revealsSoul: 'secret',
    tags: ['soul', 'secret', 'debt'],
    source: 'soul',
  },
  {
    id: 'personal-king-guard-bitter',
    bucket: 'ask-personal',
    topic: 'personal.king',
    text: 'Bellgrave did not invent cruelty. He made it punctual.',
    priority: 112,
    roles: ['guard', 'gateGuard'],
    requiresLore: 'king',
    tags: ['lore', 'king'],
    source: 'lore',
  },
  {
    id: 'personal-king-goblin',
    bucket: 'ask-personal',
    topic: 'personal.king',
    text: 'Bellgrave? Big crown, small ledger discipline. Kingdom owes itself and calls that monarchy.',
    priority: 112,
    personalityTags: ['goblin'],
    requiresLore: 'king',
    tags: ['lore', 'king', 'goblin'],
    source: 'lore',
  },
  {
    id: 'personal-relationship-fond',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    beat: 'They look at your tail, then pretend they were studying the floor.',
    text: 'You are hard to miss. I hate how relieved that makes me.',
    priority: 106,
    relationshipStages: ['crush', 'dating', 'lover', 'married'],
    personalityTags: ['romantic', 'sentimental'],
    tags: ['relationship', 'personal'],
    source: 'soul',
  },
  {
    id: 'personal-fallback',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: 'I do not usually talk about myself. The habit has survived worse questions than this.',
    priority: 1,
    tags: ['personal'],
    source: 'fallback',
  },
];
