import type { ActorVoiceEntry } from '../voiceTypes.js';

export const EXPANDED_TALK_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'talk-biome-ember-shopkeeper',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'Heat makes people honest about water and dishonest about prices.',
    priority: 58,
    biomeIds: ['ember-waste', 'liberty-badlands'],
    roles: ['shopkeeper', 'goblinMerchant', 'bartender'],
    tags: ['biome', 'heat', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-biome-ember-coward',
    bucket: 'talk',
    topic: 'talk.local.biome',
    beat: 'They dab sweat from their lip like it might testify.',
    text: 'Nothing should be this warm unless it is food, fever, or judgment.',
    priority: 56,
    biomeIds: ['ember-waste', 'liberty-badlands'],
    personalityTags: ['cowardly', 'paranoid'],
    tags: ['biome', 'heat', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-biome-ocean-deadpan',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'The ocean keeps trying to enter commerce. I respect the persistence.',
    priority: 55,
    biomeIds: ['sunken-ocean'],
    personalityTags: ['deadpan', 'practical'],
    tags: ['biome', 'ocean'],
    source: 'fallback',
  },
  {
    id: 'talk-biome-parish-religious',
    bucket: 'talk',
    topic: 'talk.local.biome',
    beat: 'Their voice drops to the volume used for shrines and blackmail.',
    text: 'Moonlit Parish forgives nothing. It merely waits until confession becomes decorative.',
    priority: 62,
    biomeIds: ['moonlit-parish'],
    personalityTags: ['religious', 'melancholy'],
    tags: ['biome', 'holy', 'danger'],
    source: 'fallback',
  },
  {
    id: 'talk-biome-peak-regal',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'Jade Peak has manners. It lets you see exactly how far you will fall.',
    priority: 58,
    biomeIds: ['jade-peak-province'],
    personalityTags: ['regal', 'brave'],
    tags: ['biome', 'mountain'],
    source: 'fallback',
  },
  {
    id: 'talk-biome-depths-goblin',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'Sable Depths is excellent accounting. Every sound arrives itemized and late.',
    priority: 61,
    biomeIds: ['sable-depths'],
    personalityTags: ['goblin', 'bureaucratic'],
    tags: ['biome', 'goblin', 'danger'],
    source: 'fallback',
  },
  {
    id: 'talk-danger-guard-high',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'Keep your head low. If that is anatomically insulting, take it strategically.',
    priority: 68,
    roles: ['guard', 'gateGuard'],
    minDangerLevel: 6,
    tags: ['danger', 'guard'],
    source: 'fallback',
  },
  {
    id: 'talk-danger-hunter-high',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'The tracks here overlap. Predator, prey, fool, tax collector. Sometimes one creature covers several categories.',
    priority: 66,
    roles: ['hunter', 'trapper'],
    minDangerLevel: 5,
    tags: ['danger', 'hunting'],
    source: 'fallback',
  },
  {
    id: 'talk-danger-romantic-high',
    bucket: 'talk',
    topic: 'talk.local.biome',
    beat: 'They smile like the bad idea has already happened.',
    text: 'Danger makes everyone honest for a second. I am trying not to enjoy the second.',
    priority: 64,
    personalityTags: ['romantic', 'poetic'],
    minDangerLevel: 6,
    tags: ['danger', 'romance'],
    source: 'fallback',
  },
  {
    id: 'talk-danger-greedy-high',
    bucket: 'talk',
    topic: 'talk.local.biome',
    text: 'When the road gets dangerous, courage becomes a subscription service.',
    priority: 64,
    personalityTags: ['greedy', 'goblin'],
    minDangerLevel: 6,
    tags: ['danger', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-mood-angry-lawful',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'I am calm because shouting would make this a public procedure.',
    priority: 70,
    personalityTags: ['lawful', 'bureaucratic'],
    attitudes: ['angry', 'resentful'],
    tags: ['mood', 'anger', 'law'],
    source: 'fallback',
  },
  {
    id: 'talk-mood-angry-violent',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'My patience is not gone. It is standing behind you with a chair.',
    priority: 72,
    personalityTags: ['violent', 'vengeful'],
    attitudes: ['angry', 'hostile'],
    tags: ['mood', 'anger'],
    source: 'fallback',
  },
  {
    id: 'talk-mood-afraid-civilian',
    bucket: 'talk',
    topic: 'talk.generic',
    beat: 'They keep one foot pointed toward the nearest exit.',
    text: 'I am not afraid. I am geographically prepared.',
    priority: 70,
    roles: ['resident', 'cook', 'fisher'],
    attitudes: ['afraid'],
    tags: ['mood', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-mood-fond-deadpan',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'I have become accustomed to your outline. This is not permission to become smug.',
    priority: 72,
    personalityTags: ['deadpan'],
    attitudes: ['fond', 'friendly'],
    tags: ['mood', 'fond'],
    source: 'fallback',
  },
  {
    id: 'talk-mood-fond-kind',
    bucket: 'talk',
    topic: 'talk.generic',
    beat: 'Their shoulders lower before they remember to be careful.',
    text: 'There you are. I was not worried. I was preparing to have been worried.',
    priority: 72,
    personalityTags: ['kind', 'softhearted'],
    attitudes: ['fond', 'friendly'],
    tags: ['mood', 'fond'],
    source: 'fallback',
  },
  {
    id: 'talk-hostile-warning-guard',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'One more step and this becomes paperwork with blood in it.',
    priority: 130,
    roles: ['guard', 'gateGuard'],
    hostility: ['hostile', 'suspicious'],
    tags: ['hostile', 'law'],
    source: 'fallback',
  },
  {
    id: 'talk-hostile-warning-goblin',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Hostility acknowledged. Counter-hostility pending approval from the Ledger Below.',
    priority: 130,
    personalityTags: ['goblin', 'bureaucratic'],
    hostility: ['hostile', 'suspicious'],
    tags: ['hostile', 'goblin'],
    source: 'fallback',
  },
  {
    id: 'talk-memory-pickpocket-shop',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'Inventory moved without consent. Around here we call that theft, unless a guild calls it theater.',
    priority: 110,
    roles: ['shopkeeper', 'goblinMerchant', 'bartender'],
    memoryTags: ['pickpocket'],
    tags: ['memory', 'crime', 'shop'],
    source: 'memory',
  },
  {
    id: 'talk-memory-town-crime-coward',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: 'They smile with the exact number of teeth required by survival.',
    text: 'I saw nothing. I heard less. I am, legally speaking, furniture.',
    priority: 112,
    personalityTags: ['cowardly', 'paranoid'],
    memoryTags: ['town', 'crime'],
    tags: ['memory', 'crime', 'fear'],
    source: 'memory',
  },
  {
    id: 'talk-memory-animal-hunted-hunter',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'You hunt like hunger borrowed a map. Crude, but not useless.',
    priority: 104,
    roles: ['hunter', 'trapper'],
    memoryTags: ['animal', 'hunted'],
    tags: ['memory', 'hunting'],
    source: 'memory',
  },
];

export const EXPANDED_ASK_AROUND_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'around-rumor-current-guard',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} I am repeating it because silence makes worse citizens.',
    priority: 130,
    roles: ['guard', 'gateGuard'],
    tags: ['rumor', 'law'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-current-shop',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} That is what people are buying extra locks about.',
    priority: 130,
    roles: ['shopkeeper', 'goblinMerchant', 'bartender'],
    tags: ['rumor', 'shop'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-current-civilian',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'They lean in with the guilty relief of someone sharing weather.',
    text: '{{rumor}} People keep lowering their voices around that sentence.',
    priority: 128,
    roles: ['resident', 'cook', 'fisher', 'hunter', 'questGiver'],
    tags: ['rumor', 'town'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-current-goblin',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Rumor is just unpaid testimony with better shoes.',
    priority: 132,
    personalityTags: ['goblin'],
    tags: ['rumor', 'goblin'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-specific-crime-guard',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: 'The guard makes the street feel narrower by looking down it.',
    text: '{{rumor}} That is the public version. The private version has more footprints.',
    priority: 134,
    roles: ['guard', 'gateGuard'],
    memoryTags: ['crime'],
    tags: ['rumor', 'crime', 'law'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-specific-eaten-kind',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} People are laughing because fear needs somewhere to sit.',
    priority: 132,
    personalityTags: ['kind', 'softhearted'],
    memoryTags: ['eaten'],
    tags: ['rumor', 'eaten', 'fear'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-specific-eaten-deadpan',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} The town has chosen not to metabolize that information calmly.',
    priority: 132,
    personalityTags: ['deadpan', 'sharp'],
    memoryTags: ['eaten'],
    tags: ['rumor', 'eaten'],
    source: 'rumor',
  },
  {
    id: 'around-rumor-specific-pickpocket-thief',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Amateur work, unless it was professional work pretending to limp.',
    priority: 133,
    roles: ['thief', 'thiefContact', 'guildContact'],
    memoryTags: ['pickpocket'],
    tags: ['rumor', 'pickpocket', 'guild'],
    source: 'rumor',
  },
  {
    id: 'around-current-town-wanted-civilian',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'The town is practicing normal faces. That means somebody official is angry.',
    priority: 112,
    roles: ['resident', 'cook', 'fisher', 'hunter'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'town'],
    source: 'faction',
  },
  {
    id: 'around-current-town-wanted-goblin',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Wanted level rising. Human law does this charming thing where panic wears a hat.',
    priority: 114,
    personalityTags: ['goblin'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'goblin', 'law'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-shop',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'Humans and goblins both want peace. Neither side has agreed what peace costs.',
    priority: 108,
    roles: ['shopkeeper', 'bartender', 'blackMarketMerchant'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human', 'shop'],
    source: 'faction',
  },
  {
    id: 'around-faction-human-goblin-romantic',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'The truce looks like two people at a wedding who know the same secret.',
    priority: 106,
    personalityTags: ['romantic', 'poetic'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    tags: ['faction', 'goblin', 'human'],
    source: 'faction',
  },
  {
    id: 'around-bandit-civilian-afraid',
    bucket: 'ask-around',
    topic: 'around.banditThreat',
    beat: 'They lower their voice until it is almost furniture.',
    text: 'Bandits do not need to enter town to raid it. Sometimes they just teach everyone to close early.',
    priority: 124,
    roles: ['resident', 'cook', 'fisher'],
    attitudes: ['afraid', 'wary'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    tags: ['faction', 'bandit', 'fear'],
    source: 'faction',
  },
  {
    id: 'around-bandit-thief',
    bucket: 'ask-around',
    topic: 'around.banditThreat',
    text: 'Bandits are thieves who never learned doors. It embarrasses the profession.',
    priority: 125,
    roles: ['thief', 'thiefContact', 'guildContact'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    tags: ['faction', 'bandit', 'guild'],
    source: 'faction',
  },
  {
    id: 'around-social-friend-soft',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} is a friend. They would deny needing help, which is how you know where to start.',
    priority: 94,
    socialLinkKinds: ['friend'],
    personalityTags: ['kind', 'softhearted', 'sentimental'],
    tags: ['social', 'friend'],
    source: 'social',
  },
  {
    id: 'around-social-friend-deadpan',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} is tolerable in ways I refuse to document.',
    priority: 94,
    socialLinkKinds: ['friend'],
    personalityTags: ['deadpan', 'practical'],
    tags: ['social', 'friend'],
    source: 'social',
  },
  {
    id: 'around-social-ex-romantic',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} and I were once a story. The ending keeps asking for edits.',
    priority: 98,
    socialLinkKinds: ['ex'],
    personalityTags: ['romantic', 'poetic', 'melancholy'],
    tags: ['social', 'ex', 'romance'],
    source: 'social',
  },
  {
    id: 'around-social-boss-worker',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} signs things like the ink is afraid of them.',
    priority: 92,
    socialLinkKinds: ['boss'],
    personalityTags: ['bureaucratic', 'lawful', 'practical'],
    tags: ['social', 'work'],
    source: 'social',
  },
  {
    id: 'around-shop-economy-wanted',
    bucket: 'ask-around',
    topic: 'around.shopEconomy',
    text: 'When wanted posters go up, people buy three things: locks, lies, and snacks for waiting.',
    priority: 110,
    roles: ['shopkeeper', 'goblinMerchant', 'blackMarketMerchant'],
    townMoodTags: ['wanted'],
    tags: ['shop', 'wanted'],
    source: 'faction',
  },
  {
    id: 'around-quest-lead-guard',
    bucket: 'ask-around',
    topic: 'around.questLead',
    text: 'If you want trouble, follow the road that looks recently forgiven.',
    priority: 38,
    roles: ['guard', 'gateGuard', 'questGiver'],
    tags: ['quest', 'road'],
    source: 'fallback',
  },
  {
    id: 'around-quest-lead-goblin',
    bucket: 'ask-around',
    topic: 'around.questLead',
    text: 'Adventure is unpaid labor with better songs. Check the cold road if you enjoy invoices from fate.',
    priority: 40,
    personalityTags: ['goblin'],
    tags: ['quest', 'goblin'],
    source: 'fallback',
  },
  {
    id: 'around-danger-high-paranoid',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'People are walking in pairs. Not because they trust each other. Because two obituaries split the shame.',
    priority: 82,
    personalityTags: ['paranoid', 'cowardly'],
    minDangerLevel: 6,
    tags: ['danger', 'town'],
    source: 'fallback',
  },
  {
    id: 'around-danger-high-regal',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'The road is hostile. The official phrasing is challenging. Officials are paid by the cowardice.',
    priority: 82,
    personalityTags: ['regal', 'lawful'],
    minDangerLevel: 6,
    tags: ['danger', 'law'],
    source: 'fallback',
  },
  {
    id: 'around-danger-high-hungry',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    text: 'Danger makes people waste food. They run, drop bread, and call it tragedy. I call it logistics.',
    priority: 82,
    personalityTags: ['hungry'],
    minDangerLevel: 6,
    tags: ['danger', 'food'],
    source: 'fallback',
  },
];

export const EXPANDED_ASK_PERSONAL_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'personal-family-coward',
    bucket: 'ask-personal',
    topic: 'personal.family',
    beat: 'They glance toward {{target}} without moving their head.',
    text: '{{target}} is family. Please do not make that information dramatic.',
    priority: 122,
    socialLinkKinds: ['family'],
    personalityTags: ['cowardly', 'paranoid'],
    tags: ['social', 'family', 'fear'],
    source: 'social',
  },
  {
    id: 'personal-family-goblin',
    bucket: 'ask-personal',
    topic: 'personal.family',
    text: '{{target}} is family. Shared blood, shared liability, separate invoices.',
    priority: 122,
    socialLinkKinds: ['family'],
    personalityTags: ['goblin', 'bureaucratic'],
    tags: ['social', 'family', 'goblin'],
    source: 'social',
  },
  {
    id: 'personal-friend-practical',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} is a friend. We disagree on almost everything except showing up.',
    priority: 118,
    socialLinkKinds: ['friend'],
    personalityTags: ['practical', 'deadpan', 'lawful'],
    tags: ['social', 'friend'],
    source: 'social',
  },
  {
    id: 'personal-friend-kind',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    beat: 'They try to make the affection sound like a minor administrative detail.',
    text: '{{target}} matters to me. If you repeat that, I will pretend I meant strategically.',
    priority: 118,
    socialLinkKinds: ['friend'],
    personalityTags: ['kind', 'softhearted', 'sentimental'],
    tags: ['social', 'friend'],
    source: 'social',
  },
  {
    id: 'personal-rival-violent',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} is my rival. One day we will settle it peacefully, by which I mean in public.',
    priority: 120,
    socialLinkKinds: ['rival'],
    personalityTags: ['violent', 'brave', 'vengeful'],
    tags: ['social', 'rival'],
    source: 'social',
  },
  {
    id: 'personal-rival-regal',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} mistakes posture for honor. I intend to correct the curriculum.',
    priority: 120,
    socialLinkKinds: ['rival'],
    personalityTags: ['regal', 'statusHungry'],
    tags: ['social', 'rival'],
    source: 'social',
  },
  {
    id: 'personal-ex-melancholy',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    beat: 'For a moment, their face becomes a room no one has opened lately.',
    text: '{{target}} and I were close. Some doors remain doors after the house burns down.',
    priority: 124,
    socialLinkKinds: ['ex'],
    personalityTags: ['melancholy', 'romantic', 'poetic'],
    tags: ['social', 'ex', 'romance'],
    source: 'social',
  },
  {
    id: 'personal-debt-practical',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} and I have a debt between us. I prefer debts. They admit what feelings hide.',
    priority: 118,
    socialLinkKinds: ['debtor', 'creditor'],
    personalityTags: ['practical', 'sharp', 'greedy'],
    tags: ['social', 'debt'],
    source: 'social',
  },
  {
    id: 'personal-social-ex-generic',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} and I used to be closer. People call that history when they want it to stop bleeding.',
    priority: 116,
    socialLinkKinds: ['ex'],
    tags: ['social', 'ex'],
    source: 'social',
  },
  {
    id: 'personal-social-faction-ally',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} and I stand on the same side because the other sides keep making worse arguments.',
    priority: 114,
    socialLinkKinds: ['factionAlly'],
    tags: ['social', 'faction'],
    source: 'social',
  },
  {
    id: 'personal-social-generic-link',
    bucket: 'ask-personal',
    topic: 'personal.socialLink',
    text: '{{target}} matters. I am saying it plainly so my fear has fewer places to hide.',
    priority: 112,
    socialLinkKinds: ['friend', 'lover', 'spouse', 'boss', 'unknown'],
    tags: ['social'],
    source: 'social',
  },
  {
    id: 'personal-insecurity-coward',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    beat: 'They laugh once, then inspect the laugh for damage.',
    text: 'I worry courage is just fear that found a costume before I did.',
    priority: 110,
    personalityTags: ['cowardly', 'paranoid'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['soul', 'insecurity', 'fear'],
    source: 'soul',
  },
  {
    id: 'personal-insecurity-greedy',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    text: 'I count money because people keep changing value when I look away.',
    priority: 110,
    personalityTags: ['greedy', 'goblin'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['soul', 'insecurity', 'money'],
    source: 'soul',
  },
  {
    id: 'personal-longing-hungry',
    bucket: 'ask-personal',
    topic: 'personal.longing',
    text: 'I want a meal nobody earned by surviving something first.',
    priority: 108,
    personalityTags: ['hungry'],
    requiresSoul: 'any',
    revealsSoul: 'opinionHint',
    tags: ['soul', 'longing', 'food'],
    source: 'soul',
  },
  {
    id: 'personal-longing-religious',
    bucket: 'ask-personal',
    topic: 'personal.longing',
    text: 'I want a god who answers before the receipt is due.',
    priority: 108,
    personalityTags: ['religious', 'goblin'],
    requiresSoul: 'any',
    revealsSoul: 'opinionHint',
    tags: ['soul', 'longing', 'holy'],
    source: 'soul',
  },
  {
    id: 'personal-wound-thief',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    text: 'First thing I stole was bread. Second was the story where I had another choice.',
    priority: 116,
    roles: ['thief', 'thiefContact', 'guildContact'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['soul', 'wound', 'crime'],
    source: 'soul',
  },
  {
    id: 'personal-wound-shopkeeper',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    text: 'My first shop burned. People remember the fire. I remember who asked for credit the next morning.',
    priority: 114,
    roles: ['shopkeeper', 'goblinMerchant', 'blackMarketMerchant'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['soul', 'wound', 'shop'],
    source: 'soul',
  },
  {
    id: 'personal-contradiction-kind',
    bucket: 'ask-personal',
    topic: 'personal.contradiction',
    text: 'I believe people can change. I also keep a list, because optimism should have backups.',
    priority: 106,
    personalityTags: ['kind', 'softhearted'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['soul', 'contradiction'],
    source: 'soul',
  },
  {
    id: 'personal-contradiction-goblin',
    bucket: 'ask-personal',
    topic: 'personal.contradiction',
    text: 'The Ledger Below says all debts matter. My heart keeps making unauthorized exceptions.',
    priority: 108,
    personalityTags: ['goblin', 'religious'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['soul', 'contradiction', 'goblin'],
    source: 'soul',
  },
  {
    id: 'personal-secret-crime-thief',
    bucket: 'ask-personal',
    topic: 'personal.secret',
    beat: 'They smile like a lock learning religion.',
    text: 'There is a grate under the old market that opens for names, not keys. I know three names.',
    priority: 126,
    roles: ['thief', 'thiefContact', 'guildContact'],
    requiresSoul: 'secret',
    revealsSoul: 'secret',
    tags: ['soul', 'secret', 'guild'],
    source: 'soul',
  },
  {
    id: 'personal-secret-guard',
    bucket: 'ask-personal',
    topic: 'personal.secret',
    text: 'The west gate ledger skips one winter. Everyone old enough to know why suddenly enjoys silence.',
    priority: 124,
    roles: ['guard', 'gateGuard'],
    requiresSoul: 'secret',
    revealsSoul: 'secret',
    tags: ['soul', 'secret', 'king'],
    source: 'soul',
  },
  {
    id: 'personal-king-loyal',
    bucket: 'ask-personal',
    topic: 'personal.king',
    text: 'The King is not kind. Kindness is for neighbors. Kings are measured by which disasters arrive on schedule.',
    priority: 114,
    personalityTags: ['lawful', 'regal'],
    requiresLore: 'king',
    tags: ['lore', 'king'],
    source: 'lore',
  },
  {
    id: 'personal-king-mocking',
    bucket: 'ask-personal',
    topic: 'personal.king',
    text: 'Bellgrave wears a crown because calling it a warning label felt impolite.',
    priority: 114,
    personalityTags: ['sharp', 'cynical', 'deadpan'],
    requiresLore: 'king',
    tags: ['lore', 'king'],
    source: 'lore',
  },
];
