import type { ActorVoiceEntry } from '../voiceTypes.js';

export const ROLE_CONTEXT_TALK_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'role-talk-guard-wanted-lawful',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: '{{name}} plants one hand near their weapon, but does not draw it yet.',
    text: 'Do not confuse my restraint for forgiveness. {{town}} has a memory, snake, and right now it remembers your teeth.',
    priority: 166,
    roles: ['guard', 'gateGuard'],
    personalityTags: ['lawful', 'bureaucratic', 'regal'],
    townMoodTags: ['wanted'],
    attitudes: ['wary', 'angry', 'hostile'],
    tags: ['wanted', 'law', 'crime', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-guard-wanted-kind',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: '{{name}} lowers their voice so the whole street does not become a verdict.',
    text: 'I can want you alive and still want you accountable. Give me one clean reason not to call the others.',
    priority: 164,
    roles: ['guard', 'gateGuard'],
    personalityTags: ['kind', 'softhearted', 'idealistic'],
    townMoodTags: ['wanted'],
    attitudes: ['wary', 'afraid', 'fond'],
    tags: ['wanted', 'mercy', 'law', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-guard-fond-wanted',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: '{{name}} looks furious with the town, with you, and with their own heart.',
    text: 'Mamma mia, snake. I liked you before the wanted board learned your silhouette. Help me make that not sound stupid.',
    priority: 178,
    roles: ['guard', 'gateGuard'],
    relationshipStages: ['crush', 'dating', 'lover', 'married'],
    townMoodTags: ['wanted'],
    attitudes: ['fond', 'resentful', 'angry'],
    tags: ['wanted', 'romance', 'conflict', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-shopkeeper-low-health-greedy',
    bucket: 'talk',
    topic: 'talk.player.health',
    text: 'You are leaking urgency. I sell urgency in bottles, bandages, and regrettable markups.',
    priority: 126,
    roles: ['shopkeeper', 'goblinMerchant', 'blackMarketMerchant'],
    personalityTags: ['greedy', 'practical', 'goblin'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'shop', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-talk-shopkeeper-fond-low-health',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: '{{name}} shoves something medicinal across the counter before naming a price.',
    text: 'Pay me later. Bleed on my floor now and I will charge your ghost rent.',
    priority: 138,
    roles: ['shopkeeper', 'goblinMerchant'],
    relationshipStages: ['dating', 'lover', 'married'],
    attitudes: ['fond'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'shop', 'romance', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-talk-bartender-rumor-sharp',
    bucket: 'talk',
    topic: 'talk.local.town',
    beat: '{{name}} wipes the same clean spot on the bar until the silence pays rent.',
    text: 'Everyone confesses to furniture. I simply stand near the furniture and remember who used which cup.',
    priority: 118,
    roles: ['bartender', 'cook'],
    personalityTags: ['sharp', 'nosy', 'deadpan'],
    tags: ['rumor', 'town', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-talk-thief-wanted-fond',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'The posters are insulting. If you must become notorious, at least make the drawing flattering.',
    priority: 154,
    roles: ['thief', 'thiefContact', 'guildContact', 'blackMarketMerchant'],
    personalityTags: ['criminal', 'sharp', 'petty'],
    townMoodTags: ['wanted'],
    attitudes: ['fond', 'friendly', 'wary'],
    tags: ['wanted', 'crime', 'guild', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-thief-wanted-angry',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: '{{name}} smiles like a locked door deciding whether to stay locked.',
    text: 'You brought heat without bringing profit. That is not crime, darling snake. That is weather with an ego.',
    priority: 158,
    roles: ['thief', 'thiefContact', 'guildContact', 'blackMarketMerchant'],
    personalityTags: ['criminal', 'greedy', 'cynical'],
    townMoodTags: ['wanted'],
    attitudes: ['angry', 'resentful', 'hostile'],
    tags: ['wanted', 'crime', 'guild', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-questgiver-danger-practical',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'If you are here for heroics, stand behind the plan until the plan has finished being useful.',
    priority: 118,
    roles: ['questGiver', 'hunter', 'trapper'],
    personalityTags: ['practical', 'lawful', 'brave'],
    minDangerLevel: 5,
    tags: ['quest', 'danger', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-talk-resident-wanted-afraid',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    beat: '{{name}} keeps smiling because panic has become a civic skill.',
    text: 'Please do not make me choose between politeness and survival. I am bad at both under pressure.',
    priority: 152,
    roles: ['resident', 'cook', 'fisher'],
    personalityTags: ['cowardly', 'paranoid', 'kind'],
    townMoodTags: ['wanted'],
    attitudes: ['afraid', 'wary'],
    tags: ['wanted', 'fear', 'town', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-talk-goblin-clerk-contract',
    bucket: 'talk',
    topic: 'talk.generic',
    beat: '{{name}} taps an invisible clause into the air.',
    text: 'Affection is admissible. Liability remains undefeated.',
    priority: 112,
    roles: ['goblinClerk', 'goblinMerchant', 'goblinPriest'],
    personalityTags: ['goblin', 'bureaucratic'],
    tags: ['goblin', 'contract', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-talk-romance-candidate-hurt',
    bucket: 'talk',
    topic: 'personal.relationship',
    beat: '{{name}} does not step away, which is not the same as forgiving you.',
    text: 'I am still here. Do not mistake that for endlessness.',
    priority: 142,
    roles: ['romanceCandidate', 'resident', 'shopkeeper', 'guard'],
    relationshipStages: ['dating', 'lover', 'married'],
    attitudes: ['resentful', 'angry'],
    tags: ['romance', 'hurt', 'boundary', 'role-context'],
    source: 'fallback',
  },
];

export const ROLE_CONTEXT_ASK_AROUND_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'role-around-guard-crime-report',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    beat: '{{name}} recites the report, then adds one word that was not written down.',
    text: '{{rumor}} That is the public version. The private version is that people are scared, and scared people swing wide.',
    priority: 174,
    roles: ['guard', 'gateGuard'],
    personalityTags: ['lawful', 'kind', 'bureaucratic'],
    townMoodTags: ['wanted'],
    tags: ['crime', 'wanted', 'law', 'role-context'],
    source: 'rumor',
  },
  {
    id: 'role-around-guard-faction-war',
    bucket: 'ask-around',
    topic: 'around.factionTension',
    text: '{{factionEvent}} I do not need you to pick a side. I need you to understand every side now has a blade.',
    priority: 168,
    roles: ['guard', 'gateGuard', 'questGiver'],
    factionStates: ['skirmishing', 'hostile', 'war'],
    personalityTags: ['lawful', 'brave', 'idealistic'],
    tags: ['faction', 'war', 'law', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-around-shopkeeper-shortage',
    bucket: 'ask-around',
    topic: 'around.shopEconomy',
    beat: '{{name}} counts on their fingers and somehow makes it feel threatening.',
    text: 'Supplies are not low. Supplies are shy, expensive, and emotionally unavailable.',
    priority: 142,
    roles: ['shopkeeper', 'goblinMerchant', 'blackMarketMerchant'],
    personalityTags: ['greedy', 'practical', 'deadpan'],
    tags: ['shop', 'economy', 'food', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-around-shopkeeper-wanted-market',
    bucket: 'ask-around',
    topic: 'around.shopEconomy',
    text: 'When the town hunts someone, prices learn to run. If that someone is you, do not expect a discount for causing the lesson.',
    priority: 160,
    roles: ['shopkeeper', 'blackMarketMerchant', 'goblinMerchant'],
    townMoodTags: ['wanted'],
    personalityTags: ['greedy', 'practical', 'goblin'],
    tags: ['wanted', 'shop', 'economy', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-around-bartender-rumor-soft',
    bucket: 'ask-around',
    topic: 'around.rumor',
    beat: '{{name}} pushes the rumor toward you gently, as if it might bruise.',
    text: '{{rumor}} Say you heard it from the floorboards. They have fewer enemies than I do.',
    priority: 154,
    roles: ['bartender', 'cook', 'resident'],
    personalityTags: ['kind', 'nosy', 'sentimental'],
    tags: ['rumor', 'town', 'role-context'],
    source: 'rumor',
  },
  {
    id: 'role-around-bartender-rumor-sharp',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} I would call it gossip, but gossip wears perfume. This smells like evidence.',
    priority: 156,
    roles: ['bartender', 'cook'],
    personalityTags: ['sharp', 'deadpan', 'cynical'],
    tags: ['rumor', 'evidence', 'role-context'],
    source: 'rumor',
  },
  {
    id: 'role-around-thief-crime-profit',
    bucket: 'ask-around',
    topic: 'around.rumor',
    text: '{{rumor}} Whoever did it had appetite. Appetite is not strategy, but it can be hired.',
    priority: 158,
    roles: ['thief', 'thiefContact', 'guildContact', 'blackMarketMerchant'],
    personalityTags: ['criminal', 'greedy', 'sharp'],
    tags: ['crime', 'guild', 'rumor', 'role-context'],
    source: 'rumor',
  },
  {
    id: 'role-around-thief-faction-truce',
    bucket: 'ask-around',
    topic: 'around.factionTension',
    text: '{{factionEvent}} A truce is just a knife taking a nap. Step softly.',
    priority: 144,
    roles: ['thief', 'thiefContact', 'guildContact'],
    factionStates: ['tense', 'truce', 'skirmishing'],
    personalityTags: ['criminal', 'cynical', 'sharp'],
    tags: ['faction', 'truce', 'guild', 'role-context'],
    source: 'faction',
  },
  {
    id: 'role-around-questgiver-lead-duty',
    bucket: 'ask-around',
    topic: 'around.questLead',
    text: 'There is work worth doing, which is different from work being noble. Noble work gets people killed for applause.',
    priority: 148,
    roles: ['questGiver', 'hunter', 'trapper'],
    personalityTags: ['practical', 'brave', 'cynical'],
    tags: ['quest', 'duty', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-around-resident-fear-map',
    bucket: 'ask-around',
    topic: 'around.currentEvent',
    beat: '{{name}} points with their chin, unwilling to donate a whole hand to the direction.',
    text: 'People avoid that way now. Not because they know what happened. Because they know no one came back funny enough to describe it.',
    priority: 132,
    roles: ['resident', 'fisher', 'cook'],
    personalityTags: ['cowardly', 'paranoid', 'deadpan'],
    minDangerLevel: 4,
    tags: ['danger', 'town', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-around-goblin-liability',
    bucket: 'ask-around',
    topic: 'around.goblinHuman',
    text: 'Human panic remains under-audited. Goblin panic at least arrives with witnesses, stamps, and a place to initial.',
    priority: 146,
    roles: ['goblinClerk', 'goblinMerchant', 'goblinPriest'],
    personalityTags: ['goblin', 'bureaucratic'],
    tags: ['goblin', 'contract', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-around-social-link-protective',
    bucket: 'ask-around',
    topic: 'around.actorGossip',
    text: '{{target}} is not gossip to me. Ask again gently or ask someone worse.',
    priority: 166,
    personalityTags: ['kind', 'sentimental', 'softhearted'],
    socialLinkKinds: ['family', 'friend', 'lover'],
    tags: ['social', 'boundary', 'role-context'],
    source: 'social',
  },
];

export const ROLE_CONTEXT_ASK_PERSONAL_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'role-personal-guard-mercy-wound',
    bucket: 'ask-personal',
    topic: 'personal.wound',
    beat: '{{name}} looks at their hands like the answer might still be drying there.',
    text: 'The law taught me where to stand. It did not teach me what to do when the guilty started crying like children.',
    priority: 164,
    roles: ['guard', 'gateGuard'],
    personalityTags: ['lawful', 'kind', 'idealistic'],
    requiresSoul: 'wound',
    revealsSoul: 'wound',
    tags: ['law', 'wound', 'mercy', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-guard-romance-wanted',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    text: 'Loving you would not erase the law. That is the trouble. I would have to look at both and stop pretending one was smaller.',
    priority: 170,
    roles: ['guard', 'gateGuard'],
    relationshipStages: ['dating', 'lover', 'married'],
    townMoodTags: ['wanted'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['romance', 'law', 'wanted', 'contradiction', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-shopkeeper-insecurity',
    bucket: 'ask-personal',
    topic: 'personal.insecurity',
    beat: '{{name}} laughs first, which is how they lock the door before opening it.',
    text: 'I count money because money stays counted. People change their minds and call it growth.',
    priority: 158,
    roles: ['shopkeeper', 'goblinMerchant', 'blackMarketMerchant'],
    personalityTags: ['greedy', 'practical', 'cynical'],
    requiresSoul: 'insecurity',
    revealsSoul: 'insecurity',
    tags: ['shop', 'insecurity', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-shopkeeper-romance-ledger',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    text: 'No, I cannot put us in a ledger. I tried. The numbers blushed and refused to balance.',
    priority: 160,
    roles: ['shopkeeper', 'goblinMerchant'],
    relationshipStages: ['dating', 'lover', 'married'],
    personalityTags: ['greedy', 'romantic', 'goblin'],
    tags: ['romance', 'shop', 'ledger', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-personal-bartender-secret',
    bucket: 'ask-personal',
    topic: 'personal.secret',
    beat: '{{name}} stops cleaning the glass. The room notices.',
    text: 'I know which stories are true because I buried one of my own under the bar and hear it knocking nightly.',
    priority: 166,
    roles: ['bartender', 'cook'],
    personalityTags: ['melancholy', 'sharp', 'sentimental'],
    requiresSoul: 'secret',
    revealsSoul: 'secret',
    tags: ['secret', 'rumor', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-thief-family',
    bucket: 'ask-personal',
    topic: 'personal.family',
    text: 'Family is whoever knows where you hide and brings soup instead of guards.',
    priority: 154,
    roles: ['thief', 'thiefContact', 'guildContact', 'blackMarketMerchant'],
    personalityTags: ['criminal', 'sentimental', 'lonely'],
    tags: ['family', 'crime', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-personal-thief-romance-trust',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    beat: '{{name}} flicks a coin across their knuckles, misses, and lets you see that they missed.',
    text: 'Trust is letting someone know the trick and hoping they still clap.',
    priority: 162,
    roles: ['thief', 'thiefContact', 'guildContact'],
    relationshipStages: ['dating', 'lover', 'married'],
    personalityTags: ['criminal', 'romantic', 'sharp'],
    tags: ['romance', 'trust', 'crime', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-personal-questgiver-longing',
    bucket: 'ask-personal',
    topic: 'personal.longing',
    text: 'I keep giving out tasks because if someone else finishes a thing, maybe I can believe endings are real.',
    priority: 160,
    roles: ['questGiver'],
    personalityTags: ['melancholy', 'practical', 'idealistic'],
    requiresSoul: 'any',
    revealsSoul: 'insecurity',
    tags: ['quest', 'longing', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-resident-cowardice',
    bucket: 'ask-personal',
    topic: 'personal.contradiction',
    beat: '{{name}} smiles bravely, which mostly proves they know what bravery is supposed to resemble.',
    text: 'I want to be brave in a large, visible way. Instead I survive in small private ways and hope the difference is not immoral.',
    priority: 154,
    roles: ['resident', 'fisher', 'cook'],
    personalityTags: ['cowardly', 'kind', 'softhearted'],
    requiresSoul: 'contradiction',
    revealsSoul: 'contradiction',
    tags: ['fear', 'contradiction', 'role-context'],
    source: 'soul',
  },
  {
    id: 'role-personal-goblin-contract-family',
    bucket: 'ask-personal',
    topic: 'personal.family',
    text: 'Family is a contract written in panic, amended in soup, and renewed whenever someone comes home carrying the wrong hat.',
    priority: 156,
    roles: ['goblinClerk', 'goblinMerchant', 'goblinPriest'],
    personalityTags: ['goblin', 'bureaucratic', 'sentimental'],
    tags: ['family', 'goblin', 'contract', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-personal-romance-resentment-boundary',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    beat: '{{name}} chooses every word like it might become furniture in the life you share.',
    text: 'I can forgive a wound. I cannot marry a pattern. Show me which one you are.',
    priority: 174,
    roles: ['romanceCandidate', 'resident', 'shopkeeper', 'guard'],
    relationshipStages: ['lover', 'married'],
    attitudes: ['resentful', 'angry'],
    tags: ['romance', 'boundary', 'resentment', 'role-context'],
    source: 'fallback',
  },
  {
    id: 'role-personal-romance-fond-revelation',
    bucket: 'ask-personal',
    topic: 'personal.relationship',
    beat: '{{name}} looks embarrassed by how much truth arrived without permission.',
    text: 'I used to think love would make me simpler. It has made me specific. Terribly, wonderfully specific.',
    priority: 150,
    roles: ['romanceCandidate', 'resident', 'shopkeeper', 'guard', 'questGiver'],
    relationshipStages: ['lover', 'married'],
    attitudes: ['fond', 'friendly'],
    personalityTags: ['romantic', 'poetic', 'sentimental', 'deadpan'],
    tags: ['romance', 'revelation', 'role-context'],
    source: 'fallback',
  },
];
