import type { ActorVoiceEntry } from '../voiceTypes.js';

export const TALK_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'talk-intro-kind',
    bucket: 'talk',
    topic: 'talk.introduction',
    beat: '{{name}} gives you the kind of careful smile reserved for strangers and weather.',
    text: 'A talking snake, then. I am {{name}}. Around here I try to keep people fed, forgiven, or at least found.',
    priority: 140,
    personalityTags: ['kind', 'softhearted', 'sentimental'],
    tags: ['introduction', 'kind'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-lawful',
    bucket: 'talk',
    topic: 'talk.introduction',
    text: 'State your business cleanly. I am {{name}}, and I prefer conversations that leave records and no bite marks.',
    priority: 140,
    personalityTags: ['lawful', 'bureaucratic', 'regal'],
    tags: ['introduction', 'law'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-sharp',
    bucket: 'talk',
    topic: 'talk.introduction',
    text: 'Well. A snake with questions. I am {{name}}. Try not to make curiosity look contagious.',
    priority: 140,
    personalityTags: ['sharp', 'deadpan', 'cynical'],
    tags: ['introduction'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-coward',
    bucket: 'talk',
    topic: 'talk.introduction',
    beat: '{{name}} measures the distance to the nearest exit before answering.',
    text: 'Hello. I am {{name}}. I say that politely because panic has never improved a first impression.',
    priority: 140,
    personalityTags: ['cowardly', 'paranoid'],
    tags: ['introduction', 'fear'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-greedy',
    bucket: 'talk',
    topic: 'talk.introduction',
    text: 'Welcome, stranger. I am {{name}}, and I believe every conversation can become mutually billable.',
    priority: 140,
    personalityTags: ['greedy'],
    tags: ['introduction', 'shop'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-goblin',
    bucket: 'talk',
    topic: 'talk.introduction',
    text: 'Snake acknowledged. I am {{name}}. All greetings are provisional until the Ledger Below assigns liability.',
    priority: 145,
    personalityTags: ['goblin'],
    tags: ['introduction', 'goblin'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-intro-fallback',
    bucket: 'talk',
    topic: 'talk.introduction',
    text: 'A stranger with scales. I am {{name}}. That is enough truth for a first meeting.',
    priority: 130,
    tags: ['introduction'],
    oncePerActor: true,
    source: 'fallback',
  },
  {
    id: 'talk-health-kind-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They glance at the blood before they look at your face.',
    text: 'Sit down before you become a rumor with teeth.',
    priority: 100,
    personalityTags: ['kind', 'softhearted'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'concern'],
    source: 'fallback',
  },
  {
    id: 'talk-health-greedy-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    text: 'You are bleeding in a way that suggests purchasing power.',
    priority: 99,
    roles: ['shopkeeper', 'goblinMerchant'],
    personalityTags: ['greedy', 'goblin'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-health-deadpan-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    text: 'You look medically anecdotal.',
    priority: 94,
    personalityTags: ['deadpan'],
    healthBands: ['low', 'critical'],
    tags: ['health'],
    source: 'fallback',
  },
  {
    id: 'talk-health-coward-critical',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They keep both eyes on your mouth.',
    text: 'Please do not die near me. I have never handled a corpse with this much tail.',
    priority: 103,
    personalityTags: ['cowardly'],
    healthBands: ['critical'],
    tags: ['health', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-health-romantic-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They reach toward you, then stop short of the blood.',
    text: 'Do not smile like that. You are hurt and I am angry about caring.',
    priority: 101,
    personalityTags: ['romantic'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'romance'],
    source: 'fallback',
  },
  {
    id: 'talk-length-tiny-coward',
    bucket: 'talk',
    topic: 'talk.player.length',
    beat: 'They peer down, then immediately regret seeming taller.',
    text: 'Oh. Smaller. Good. Not good for you, perhaps. Good for my obituary.',
    priority: 66,
    personalityTags: ['cowardly'],
    snakeLengthBands: ['tiny'],
    tags: ['length', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-length-tiny-sharp',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'Garden snake energy. Brave of you to make it everyone\'s problem.',
    priority: 64,
    personalityTags: ['sharp', 'deadpan'],
    snakeLengthBands: ['tiny'],
    tags: ['length'],
    source: 'fallback',
  },
  {
    id: 'talk-length-long-practical',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'Long enough to be useful. Long enough to be a problem. Classic.',
    priority: 62,
    personalityTags: ['practical'],
    snakeLengthBands: ['long', 'veryLong'],
    tags: ['length'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-coward',
    bucket: 'talk',
    topic: 'talk.player.length',
    beat: 'They look left. They look right. You are also there.',
    text: 'That is too much snake. I am surrounded by one person.',
    priority: 90,
    personalityTags: ['cowardly'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-shop',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'If you break something with the back half of yourself, I am charging the front half.',
    priority: 88,
    roles: ['shopkeeper', 'goblinMerchant'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-regal',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'By the Bellgrave Charter, no citizen should occupy that many directions.',
    priority: 86,
    personalityTags: ['regal', 'bureaucratic'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'king'],
    source: 'fallback',
  },
  {
    id: 'talk-memory-hunt-shopkeeper',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'I heard about the hunting. Bad day for rabbits, useful day for soup.',
    priority: 96,
    roles: ['shopkeeper', 'bartender', 'cook'],
    memoryTags: ['hunting'],
    tags: ['memory', 'hunting', 'shop'],
    source: 'memory',
  },
  {
    id: 'talk-memory-hunt-kind',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'I hope it was quick. I know that is a foolish thing to ask of hunger.',
    priority: 95,
    personalityTags: ['kind', 'softhearted'],
    memoryTags: ['hunting'],
    tags: ['memory', 'hunting'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-guard',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    beat: 'Their hand settles near the weapon before their manners can stop it.',
    text: 'People are not food. The fact that I had to say that has changed the room.',
    priority: 120,
    roles: ['guard', 'gateGuard'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten', 'crime'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-goblin',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    text: 'Bandit-based healthcare. Primitive, effective, underregulated.',
    priority: 116,
    personalityTags: ['goblin'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten', 'goblin'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-deadpan',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    text: 'Efficient. Horrible. Efficient.',
    priority: 114,
    personalityTags: ['deadpan'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten'],
    source: 'memory',
  },
  {
    id: 'talk-memory-player-death-kind',
    bucket: 'talk',
    topic: 'talk.player.death',
    beat: 'Their relief arrives late and tries to look professional.',
    text: 'I heard you died. I am choosing to treat your return as good news before fear argues.',
    priority: 118,
    personalityTags: ['kind', 'softhearted', 'sentimental'],
    memoryTags: ['player', 'death'],
    tags: ['memory', 'death', 'concern'],
    source: 'memory',
  },
  {
    id: 'talk-memory-player-death-deadpan',
    bucket: 'talk',
    topic: 'talk.player.death',
    text: 'Dying and continuing to make appointments is either heroic or poor scheduling.',
    priority: 116,
    personalityTags: ['deadpan', 'practical'],
    memoryTags: ['player', 'death'],
    tags: ['memory', 'death'],
    source: 'memory',
  },
  {
    id: 'talk-memory-player-revival-goblin',
    bucket: 'talk',
    topic: 'talk.player.revival',
    text: 'Your death failed to finalize. The Ledger Below has opened a dispute ticket.',
    priority: 119,
    personalityTags: ['goblin'],
    memoryTags: ['player', 'revival'],
    tags: ['memory', 'revival', 'goblin'],
    source: 'memory',
  },
  {
    id: 'talk-wanted-guard',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'The wanted posters are getting less hypothetical. That is not career advice. That is weather.',
    priority: 92,
    roles: ['guard', 'gateGuard'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'law'],
    source: 'faction',
  },
  {
    id: 'talk-wanted-shop',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'Wanted customers pay faster. Fear improves the checkout line.',
    priority: 84,
    roles: ['shopkeeper', 'goblinMerchant'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'shop'],
    source: 'faction',
  },
  {
    id: 'talk-town-guard',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'Roads, gates, taxes, guns. Civilization is just fear with receipts.',
    priority: 42,
    roles: ['guard', 'gateGuard'],
    tags: ['town', 'king'],
    source: 'fallback',
  },
  {
    id: 'talk-town-goblin',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'Humans call it law when the receipt has a flag.',
    priority: 45,
    personalityTags: ['goblin'],
    tags: ['town', 'goblin'],
    source: 'fallback',
  },
  {
    id: 'talk-town-kind',
    bucket: 'talk',
    topic: 'talk.local.town',
    beat: 'They glance toward the nearest doorway, softening before the sentence does.',
    text: 'People here pretend not to need help. It is the local accent.',
    priority: 46,
    personalityTags: ['kind', 'softhearted'],
    tags: ['town', 'kind'],
    source: 'fallback',
  },
  {
    id: 'talk-town-nosy',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'Every window knows a different version of the same afternoon. I am collecting the contradictions.',
    priority: 46,
    personalityTags: ['nosy', 'petty'],
    tags: ['town', 'gossip'],
    source: 'fallback',
  },
  {
    id: 'talk-town-lawful',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'The rules are posted clearly enough for everyone to argue about them with confidence.',
    priority: 46,
    personalityTags: ['lawful', 'bureaucratic'],
    tags: ['town', 'law'],
    source: 'fallback',
  },
  {
    id: 'talk-town-lonely',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'This place gets loud so nobody notices how many people are alone in it.',
    priority: 46,
    personalityTags: ['lonely', 'melancholy'],
    tags: ['town'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-practical',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Roads are safer after someone else tests them.',
    priority: 5,
    personalityTags: ['practical'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-coward',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'I respect bravery. I try to do it from behind doors.',
    priority: 5,
    personalityTags: ['cowardly'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-greedy',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Local danger, local prices. That is what makes it culture.',
    priority: 5,
    personalityTags: ['greedy'],
    tags: ['generic', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-poetic',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'A quiet road is either safe or proud of itself.',
    priority: 5,
    personalityTags: ['poetic', 'melancholy'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-deadpan',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'This town has survived today so far. Morale is becoming reckless.',
    priority: 5,
    personalityTags: ['deadpan'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-brave',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'If trouble arrives, face it square. Sideways fear still counts as fear.',
    priority: 7,
    personalityTags: ['brave', 'idealistic'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-cynical',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'A promise is just a debt wearing perfume. Still, people keep buying the bottle.',
    priority: 7,
    personalityTags: ['cynical', 'sharp'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-sentimental',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'The old road remembers everyone. That is sweet until you wonder what it tells strangers.',
    priority: 7,
    personalityTags: ['sentimental', 'romantic'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-fallback',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Keep moving. Standing still gives the world time to recognize you.',
    priority: 1,
    tags: ['generic'],
    source: 'fallback',
  },
];
