import type { ActorVoiceEntry } from '../voiceTypes.js';

export const TALK_VOICE: readonly ActorVoiceEntry[] = [
  {
    id: 'talk-health-kind-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They glance at the blood before they look at your face.',
    text: 'Sit down before you become a rumor with teeth.',
    priority: 100,
    personalityTags: ['kind', 'softhearted'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'concern'],
    source: 'fallback',
  },
  {
    id: 'talk-health-greedy-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    text: 'You are bleeding in a way that suggests purchasing power.',
    priority: 99,
    roles: ['shopkeeper', 'goblinMerchant'],
    personalityTags: ['greedy', 'goblin'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-health-deadpan-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    text: 'You look medically anecdotal.',
    priority: 94,
    personalityTags: ['deadpan'],
    healthBands: ['low', 'critical'],
    tags: ['health'],
    source: 'fallback',
  },
  {
    id: 'talk-health-coward-critical',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They keep both eyes on your mouth.',
    text: 'Please do not die near me. I have never handled a corpse with this much tail.',
    priority: 103,
    personalityTags: ['cowardly'],
    healthBands: ['critical'],
    tags: ['health', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-health-romantic-low',
    bucket: 'talk',
    topic: 'talk.player.health',
    beat: 'They reach toward you, then stop short of the blood.',
    text: 'Do not smile like that. You are hurt and I am angry about caring.',
    priority: 101,
    personalityTags: ['romantic'],
    healthBands: ['low', 'critical'],
    tags: ['health', 'romance'],
    source: 'fallback',
  },
  {
    id: 'talk-length-tiny-coward',
    bucket: 'talk',
    topic: 'talk.player.length',
    beat: 'They peer down, then immediately regret seeming taller.',
    text: 'Oh. Smaller. Good. Not good for you, perhaps. Good for my obituary.',
    priority: 66,
    personalityTags: ['cowardly'],
    snakeLengthBands: ['tiny'],
    tags: ['length', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-length-tiny-sharp',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'Garden snake energy. Brave of you to make it everyone\'s problem.',
    priority: 64,
    personalityTags: ['sharp', 'deadpan'],
    snakeLengthBands: ['tiny'],
    tags: ['length'],
    source: 'fallback',
  },
  {
    id: 'talk-length-long-practical',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'Long enough to be useful. Long enough to be a problem. Classic.',
    priority: 62,
    personalityTags: ['practical'],
    snakeLengthBands: ['long', 'veryLong'],
    tags: ['length'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-coward',
    bucket: 'talk',
    topic: 'talk.player.length',
    beat: 'They look left. They look right. You are also there.',
    text: 'That is too much snake. I am surrounded by one person.',
    priority: 90,
    personalityTags: ['cowardly'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'fear'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-shop',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'If you break something with the back half of yourself, I am charging the front half.',
    priority: 88,
    roles: ['shopkeeper', 'goblinMerchant'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-length-absurd-regal',
    bucket: 'talk',
    topic: 'talk.player.length',
    text: 'By the Bellgrave Charter, no citizen should occupy that many directions.',
    priority: 86,
    personalityTags: ['regal', 'bureaucratic'],
    snakeLengthBands: ['absurd', 'legendary'],
    tags: ['length', 'king'],
    source: 'fallback',
  },
  {
    id: 'talk-memory-hunt-shopkeeper',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'I heard about the hunting. Bad day for rabbits, useful day for soup.',
    priority: 96,
    roles: ['shopkeeper', 'bartender', 'cook'],
    memoryTags: ['hunting'],
    tags: ['memory', 'hunting', 'shop'],
    source: 'memory',
  },
  {
    id: 'talk-memory-hunt-kind',
    bucket: 'talk',
    topic: 'talk.player.hunt',
    text: 'I hope it was quick. I know that is a foolish thing to ask of hunger.',
    priority: 95,
    personalityTags: ['kind', 'softhearted'],
    memoryTags: ['hunting'],
    tags: ['memory', 'hunting'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-guard',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    beat: 'Their hand settles near the weapon before their manners can stop it.',
    text: 'People are not food. The fact that I had to say that has changed the room.',
    priority: 120,
    roles: ['guard', 'gateGuard'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten', 'crime'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-goblin',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    text: 'Bandit-based healthcare. Primitive, effective, underregulated.',
    priority: 116,
    personalityTags: ['goblin'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten', 'goblin'],
    source: 'memory',
  },
  {
    id: 'talk-memory-humanoid-eaten-deadpan',
    bucket: 'talk',
    topic: 'talk.player.humanoidEaten',
    text: 'Efficient. Horrible. Efficient.',
    priority: 114,
    personalityTags: ['deadpan'],
    memoryTags: ['humanoid', 'eaten'],
    tags: ['memory', 'eaten'],
    source: 'memory',
  },
  {
    id: 'talk-wanted-guard',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'The wanted posters are getting less hypothetical. That is not career advice. That is weather.',
    priority: 92,
    roles: ['guard', 'gateGuard'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'law'],
    source: 'faction',
  },
  {
    id: 'talk-wanted-shop',
    bucket: 'talk',
    topic: 'talk.player.wanted',
    text: 'Wanted customers pay faster. Fear improves the checkout line.',
    priority: 84,
    roles: ['shopkeeper', 'goblinMerchant'],
    townMoodTags: ['wanted'],
    tags: ['wanted', 'shop'],
    source: 'faction',
  },
  {
    id: 'talk-town-guard',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'Roads, gates, taxes, guns. Civilization is just fear with receipts.',
    priority: 42,
    roles: ['guard', 'gateGuard'],
    tags: ['town', 'king'],
    source: 'fallback',
  },
  {
    id: 'talk-town-goblin',
    bucket: 'talk',
    topic: 'talk.local.town',
    text: 'Humans call it law when the receipt has a flag.',
    priority: 45,
    personalityTags: ['goblin'],
    tags: ['town', 'goblin'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-practical',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Roads are safer after someone else tests them.',
    priority: 5,
    personalityTags: ['practical'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-coward',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'I respect bravery. I try to do it from behind doors.',
    priority: 5,
    personalityTags: ['cowardly'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-greedy',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Local danger, local prices. That is what makes it culture.',
    priority: 5,
    personalityTags: ['greedy'],
    tags: ['generic', 'shop'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-poetic',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'A quiet road is either safe or proud of itself.',
    priority: 5,
    personalityTags: ['poetic', 'melancholy'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-deadpan',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'This town has survived today so far. Morale is becoming reckless.',
    priority: 5,
    personalityTags: ['deadpan'],
    tags: ['generic'],
    source: 'fallback',
  },
  {
    id: 'talk-generic-fallback',
    bucket: 'talk',
    topic: 'talk.generic',
    text: 'Keep moving. Standing still gives the world time to recognize you.',
    priority: 1,
    tags: ['generic'],
    source: 'fallback',
  },
];
