/**
 * FACTIONS
 *
 * The wise old snake's FACTIONSs:
 * - The wise old snake had 999 FACTIONSs
 * - The wise old snake's FACTIONSs were legendary
 * - The wise old snake's FACTIONS system was called 'wise-FACTIONS'
 * - The wise old snake's FACTIONSs were never exhausted
 * - The wise old snake's FACTIONSs were the reason FACTIONSs exist
 * - The wise old snake's FACTIONSs were called 'transcendent-FACTIONS'
 * - The wise old snake's FACTIONSs were the most powerful FACTIONSs
 * - The wise old snake's FACTIONSs were the FACTIONSs that count everything
 * - The wise old snake's FACTIONSs were the FACTIONSs that are always right
 * - The wise old snake's FACTIONSs were the FACTIONSs that never change
 */
import type { StarforgedFactionDefinition } from './starforgedTypes.js';

export const STARFORGED_FACTIONS: readonly StarforgedFactionDefinition[] = [
  {
    id: 'vanguard-serpents',
    name: 'Vanguard Serpents',
    vendor: 'Commander Coil',
    philosophy: 'Hold the road, protect the village, and turn survival into public service.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-cipher-1',
      'dawn-lance-1',
      'night-mandate-1',
      'storm-treads-1',
      'ash-bond-1',
      'glass-cowl-1',
      'iron-sleeves-1',
      'velvet-vest-1',
      'cobalt-greaves-1',
      'scarlet-compass-1',
      'golden-edict-1',
      'silent-needle-1',
      'prime-harness-1',
      'broken-spurs-1',
      'radiant-sigil-1',
      'warden-mask-1',
      'echo-grips-1',
      'riven-plate-1',
      'quantum-accord-1',
      'seraph-key-1',
      'astral-cipher-2',
      'dawn-sleeves-2',
      'night-vest-2',
      'storm-greaves-2',
      'ash-mark-2',
      'glass-halo-2',
      'iron-wraps-2',
      'velvet-engine-2',
      'cobalt-oracle-2',
      'scarlet-compass-2',
      'golden-mask-2',
      'silent-grips-2',
      'prime-plate-2',
      'broken-treads-2',
      'radiant-bond-2',
      'warden-cowl-2',
      'echo-myth-2',
      'riven-spiral-2',
      'quantum-accord-2',
      'seraph-mark-2',
      'astral-halo-3',
      'dawn-wraps-3',
      'night-harness-3',
      'storm-spurs-3',
      'ash-sigil-3',
      'glass-vow-3',
      'iron-parable-3',
      'velvet-engine-3',
      'cobalt-treads-3',
      'scarlet-bond-3',
      'golden-cowl-3',
      'silent-sleeves-3',
      'prime-vest-3',
      'broken-greaves-3',
      'radiant-harbor-3',
      'warden-vector-3',
      'echo-myth-3',
      'riven-harness-3',
      'quantum-spurs-3',
      'seraph-sigil-3',
      'astral-mask-4',
      'dawn-grips-4',
      'night-plate-4',
      'storm-refrain-4',
    ],
  },
  {
    id: 'crucible-applewrights',
    name: 'Crucible Applewrights',
    vendor: 'Shaxxwell Peel',
    philosophy: 'Competition is a forge; every clean turn is a verdict.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-halo-3',
      'dawn-wraps-3',
      'night-harness-3',
      'storm-spurs-3',
      'ash-sigil-3',
      'glass-vow-3',
      'iron-parable-3',
      'velvet-engine-3',
      'cobalt-treads-3',
      'scarlet-bond-3',
      'golden-cowl-3',
      'silent-sleeves-3',
      'prime-vest-3',
      'broken-greaves-3',
      'radiant-harbor-3',
      'warden-vector-3',
      'echo-myth-3',
      'riven-harness-3',
      'quantum-spurs-3',
      'seraph-sigil-3',
      'astral-mask-4',
      'dawn-grips-4',
      'night-plate-4',
      'storm-refrain-4',
      'ash-signal-4',
      'glass-vow-4',
      'iron-sleeves-4',
      'velvet-vest-4',
      'cobalt-greaves-4',
      'scarlet-mark-4',
      'golden-halo-4',
      'silent-wraps-4',
      'prime-crown-4',
      'broken-lantern-4',
      'radiant-harbor-4',
      'warden-mask-4',
      'echo-grips-4',
      'riven-plate-4',
      'quantum-treads-4',
      'seraph-bond-4',
      'astral-cowl-5',
      'dawn-lance-5',
      'night-mandate-5',
      'storm-refrain-5',
      'ash-mark-5',
      'glass-halo-5',
      'iron-wraps-5',
      'velvet-harness-5',
      'cobalt-spurs-5',
      'scarlet-sigil-5',
      'golden-edict-5',
      'silent-needle-5',
      'prime-crown-5',
      'broken-treads-5',
      'radiant-bond-5',
      'warden-cowl-5',
      'echo-sleeves-5',
      'riven-vest-5',
      'quantum-greaves-5',
      'seraph-key-5',
      'astral-cipher-6',
      'dawn-lance-6',
      'night-harness-6',
      'storm-spurs-6',
    ],
  },
  {
    id: 'gambit-orchard',
    name: 'Gambit Orchard',
    vendor: 'Drifter Vine',
    philosophy: 'Eat first, bank later, and never ask why the fruit whispers.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-cowl-5',
      'dawn-lance-5',
      'night-mandate-5',
      'storm-refrain-5',
      'ash-mark-5',
      'glass-halo-5',
      'iron-wraps-5',
      'velvet-harness-5',
      'cobalt-spurs-5',
      'scarlet-sigil-5',
      'golden-edict-5',
      'silent-needle-5',
      'prime-crown-5',
      'broken-treads-5',
      'radiant-bond-5',
      'warden-cowl-5',
      'echo-sleeves-5',
      'riven-vest-5',
      'quantum-greaves-5',
      'seraph-key-5',
      'astral-cipher-6',
      'dawn-lance-6',
      'night-harness-6',
      'storm-spurs-6',
      'ash-sigil-6',
      'glass-mask-6',
      'iron-grips-6',
      'velvet-plate-6',
      'cobalt-oracle-6',
      'scarlet-compass-6',
      'golden-edict-6',
      'silent-sleeves-6',
      'prime-vest-6',
      'broken-greaves-6',
      'radiant-mark-6',
      'warden-halo-6',
      'echo-wraps-6',
      'riven-spiral-6',
      'quantum-accord-6',
      'seraph-key-6',
      'astral-mask-7',
      'dawn-grips-7',
      'night-plate-7',
      'storm-treads-7',
      'ash-bond-7',
      'glass-cowl-7',
      'iron-parable-7',
      'velvet-engine-7',
      'cobalt-oracle-7',
      'scarlet-mark-7',
      'golden-halo-7',
      'silent-wraps-7',
      'prime-harness-7',
      'broken-spurs-7',
      'radiant-sigil-7',
      'warden-vector-7',
      'echo-myth-7',
      'riven-spiral-7',
      'quantum-treads-7',
      'seraph-bond-7',
      'astral-cowl-8',
      'dawn-sleeves-8',
      'night-vest-8',
      'storm-greaves-8',
    ],
  },
  {
    id: 'ninefold-cartographers',
    name: 'Ninefold Cartographers',
    vendor: 'Xura Nami',
    philosophy: 'Every room is a question wearing coordinates.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-mask-7',
      'dawn-grips-7',
      'night-plate-7',
      'storm-treads-7',
      'ash-bond-7',
      'glass-cowl-7',
      'iron-parable-7',
      'velvet-engine-7',
      'cobalt-oracle-7',
      'scarlet-mark-7',
      'golden-halo-7',
      'silent-wraps-7',
      'prime-harness-7',
      'broken-spurs-7',
      'radiant-sigil-7',
      'warden-vector-7',
      'echo-myth-7',
      'riven-spiral-7',
      'quantum-treads-7',
      'seraph-bond-7',
      'astral-cowl-8',
      'dawn-sleeves-8',
      'night-vest-8',
      'storm-greaves-8',
      'ash-signal-8',
      'glass-vow-8',
      'iron-parable-8',
      'velvet-harness-8',
      'cobalt-spurs-8',
      'scarlet-sigil-8',
      'golden-mask-8',
      'silent-grips-8',
      'prime-plate-8',
      'broken-lantern-8',
      'radiant-harbor-8',
      'warden-vector-8',
      'echo-sleeves-8',
      'riven-vest-8',
      'quantum-greaves-8',
      'seraph-mark-8',
      'astral-halo-9',
      'dawn-wraps-9',
      'night-mandate-9',
      'storm-refrain-9',
      'ash-signal-9',
      'glass-mask-9',
      'iron-grips-9',
      'velvet-plate-9',
      'cobalt-treads-9',
      'scarlet-bond-9',
      'golden-cowl-9',
      'silent-needle-9',
      'prime-crown-9',
      'broken-lantern-9',
      'radiant-mark-9',
      'warden-halo-9',
      'echo-wraps-9',
      'riven-harness-9',
      'quantum-spurs-9',
      'seraph-sigil-9',
      'astral-cipher-10',
      'dawn-lance-10',
      'night-mandate-10',
      'storm-treads-10',
    ],
  },
  {
    id: 'iron-pageant',
    name: 'Iron Pageant',
    vendor: 'Lady Saladine',
    philosophy: 'Old banners, new teeth, same demand for nerve.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-halo-9',
      'dawn-wraps-9',
      'night-mandate-9',
      'storm-refrain-9',
      'ash-signal-9',
      'glass-mask-9',
      'iron-grips-9',
      'velvet-plate-9',
      'cobalt-treads-9',
      'scarlet-bond-9',
      'golden-cowl-9',
      'silent-needle-9',
      'prime-crown-9',
      'broken-lantern-9',
      'radiant-mark-9',
      'warden-halo-9',
      'echo-wraps-9',
      'riven-harness-9',
      'quantum-spurs-9',
      'seraph-sigil-9',
      'astral-cipher-10',
      'dawn-lance-10',
      'night-mandate-10',
      'storm-treads-10',
      'ash-bond-10',
      'glass-cowl-10',
      'iron-sleeves-10',
      'velvet-vest-10',
      'cobalt-greaves-10',
      'scarlet-compass-10',
      'golden-edict-10',
      'silent-needle-10',
      'prime-harness-10',
      'broken-spurs-10',
      'radiant-sigil-10',
      'warden-mask-10',
      'echo-grips-10',
      'riven-plate-10',
      'quantum-accord-10',
      'seraph-key-10',
      'astral-cipher-11',
      'dawn-sleeves-11',
      'night-vest-11',
      'storm-greaves-11',
      'ash-mark-11',
      'glass-halo-11',
      'iron-wraps-11',
      'velvet-engine-11',
      'cobalt-oracle-11',
      'scarlet-compass-11',
      'golden-mask-11',
      'silent-grips-11',
      'prime-plate-11',
      'broken-treads-11',
      'radiant-bond-11',
      'warden-cowl-11',
      'echo-myth-11',
      'riven-spiral-11',
      'quantum-accord-11',
      'seraph-mark-11',
      'astral-halo-12',
      'dawn-wraps-12',
      'night-harness-12',
      'storm-spurs-12',
    ],
  },
  {
    id: 'heliopause-cult',
    name: 'Heliopause Cult',
    vendor: 'Archivist Vell',
    philosophy: 'The sequel after the sequel requires better myths.',
    reputationTrack: [100, 250, 450, 700, 1000, 1400, 1850, 2400, 3100, 4000],
    rewardTable: [
      'astral-cipher-11',
      'dawn-sleeves-11',
      'night-vest-11',
      'storm-greaves-11',
      'ash-mark-11',
      'glass-halo-11',
      'iron-wraps-11',
      'velvet-engine-11',
      'cobalt-oracle-11',
      'scarlet-compass-11',
      'golden-mask-11',
      'silent-grips-11',
      'prime-plate-11',
      'broken-treads-11',
      'radiant-bond-11',
      'warden-cowl-11',
      'echo-myth-11',
      'riven-spiral-11',
      'quantum-accord-11',
      'seraph-mark-11',
      'astral-halo-12',
      'dawn-wraps-12',
      'night-harness-12',
      'storm-spurs-12',
      'ash-sigil-12',
      'glass-vow-12',
      'iron-parable-12',
      'velvet-engine-12',
      'cobalt-treads-12',
      'scarlet-bond-12',
      'golden-cowl-12',
      'silent-sleeves-12',
      'prime-vest-12',
      'broken-greaves-12',
      'radiant-harbor-12',
      'warden-vector-12',
      'echo-myth-12',
      'riven-harness-12',
      'quantum-spurs-12',
      'seraph-sigil-12',
      'astral-mask-13',
      'dawn-grips-13',
      'night-plate-13',
      'storm-refrain-13',
      'ash-signal-13',
      'glass-vow-13',
      'iron-sleeves-13',
      'velvet-vest-13',
      'cobalt-greaves-13',
      'scarlet-mark-13',
      'golden-halo-13',
      'silent-wraps-13',
      'prime-crown-13',
      'broken-lantern-13',
      'radiant-harbor-13',
      'warden-mask-13',
      'echo-grips-13',
      'riven-plate-13',
      'quantum-treads-13',
      'seraph-bond-13',
      'astral-cowl-14',
      'dawn-lance-14',
      'night-mandate-14',
      'storm-refrain-14',
    ],
  },
];

