import type { Item } from '../inventory/item.js';

export const MINECRAFT_ITEMS: readonly Item[] = [
  // Tools — pickaxes
  {
    id: 'wooden_pickaxe',
    name: 'Wooden Pickaxe',
    description: 'A basic pickaxe for mining stone and ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'Sturdier than wood. Mines iron ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    description: 'Solid iron. Mines diamond ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  {
    id: 'diamond_pickaxe',
    name: 'Diamond Pickaxe',
    description: 'Shines bright and mines anything.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.01 },
  },
  // Tools — swords
  {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    description: 'A basic melee weapon.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'stone_sword',
    name: 'Stone Sword',
    description: 'A sturdy blade for combat.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.03 },
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A reliable iron blade.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  // Tools — axes
  {
    id: 'wooden_axe',
    name: 'Wooden Axe',
    description: 'Chops wood quickly.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.06 },
  },
  {
    id: 'stone_axe',
    name: 'Stone Axe',
    description: 'Sturdier axe for harder wood.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'iron_axe',
    name: 'Iron Axe',
    description: 'A fine iron axe.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.03 },
  },
  // Tools — shovels
  {
    id: 'wooden_shovel',
    name: 'Wooden Shovel',
    description: 'Digs dirt and sand.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'stone_shovel',
    name: 'Stone Shovel',
    description: 'Sturdier shovel for gravel.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'iron_shovel',
    name: 'Iron Shovel',
    description: 'Fine iron shovel.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  // Materials
  {
    id: 'cobblestone',
    name: 'Cobblestone',
    description: 'A common building block.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'torch_item',
    name: 'Torch',
    description: 'Emits light. Useful for dark places.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_beef',
    name: 'Raw Beef',
    description: 'A strip of raw cow meat. Edible, but risky.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked_beef',
    name: 'Cooked Beef',
    description: 'A strip of grilled beef. Nourishing.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'bread',
    name: 'Bread',
    description: 'A loaf of bread. Filling and safe.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'stick',
    name: 'Stick',
    description: 'A small wooden rod. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'planks_item',
    name: 'Planks',
    description: 'Processed wood. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    description: 'Refined iron. Essential for tools.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    description: 'Refined gold. Valuable.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    description: 'A precious gemstone. The hardest material.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'coal',
    name: 'Coal',
    description: 'A black mineral. Used for fuel and torches.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'bucket',
    name: 'Bucket',
    description: 'An iron bucket. For liquids and transport.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'boat',
    name: 'Boat',
    description: 'A wooden vessel for water travel.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'chest',
    name: 'Chest',
    description: 'A storage container.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ladder',
    name: 'Ladder',
    description: 'Climbable rungs. Useful for vertical movement.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'door',
    name: 'Door',
    description: 'A wooden door. Closes gaps.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'furnace',
    name: 'Furnace',
    description: 'Smelts ore and cooks food.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'rotten_flesh',
    name: 'Rotten Flesh',
    description: 'Decaying meat. Not appetizing.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'bones',
    name: 'Bones',
    description: 'Bones from the undead.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'arrows',
    name: 'Arrows',
    description: 'Wooden shafts with stone tips.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'leather',
    name: 'Leather',
    description: 'Cured hide. Soft and flexible.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'gunpowder',
    name: 'Gunpowder',
    description: 'Explosive powder from creepers.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_iron',
    name: 'Raw Iron',
    description: 'Unrefined iron ore. Needs smelting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_gold',
    name: 'Raw Gold',
    description: 'Unrefined gold ore. Needs smelting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'armors',
    name: 'Armor Pieces',
    description: 'Scrap armor. Not very useful.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'fire_charge',
    name: 'Fire Charge',
    description: 'A burning ember. From creepers.',
    kind: 'consumable',
    category: 'material',
  },
];

const MC_ITEM_MAP = new Map<string, Item>(
  MINECRAFT_ITEMS.map((item) => [item.id, item]),
);

export function getMinecraftItem(id: string): Item | undefined {
  return MC_ITEM_MAP.get(id);
}

export function isMinecraftItem(id: string): boolean {
  return MC_ITEM_MAP.has(id);
}

export function getMinecraftItems(): readonly Item[] {
  return MINECRAFT_ITEMS;
}
