import type { Item } from '../inventory/item.js';

export const MINECRAFT_ITEMS: readonly Item[] = [
  // Tools — pickaxes
  {
    id: 'wooden_pickaxe',
    name: 'Wooden Pickaxe',
    description: 'A basic pickaxe for mining stone and ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'Sturdier than wood. Mines iron ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    description: 'Solid iron. Mines diamond ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  {
    id: 'diamond_pickaxe',
    name: 'Diamond Pickaxe',
    description: 'Shines bright and mines anything.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.01 },
  },
  // Tools — swords
  {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    description: 'A basic melee weapon.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'stone_sword',
    name: 'Stone Sword',
    description: 'A sturdy blade for combat.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.03 },
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A reliable iron blade.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  // Tools — axes
  {
    id: 'wooden_axe',
    name: 'Wooden Axe',
    description: 'Chops wood quickly.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.06 },
  },
  {
    id: 'stone_axe',
    name: 'Stone Axe',
    description: 'Sturdier axe for harder wood.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'iron_axe',
    name: 'Iron Axe',
    description: 'A fine iron axe.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.03 },
  },
  // Tools — shovels
  {
    id: 'wooden_shovel',
    name: 'Wooden Shovel',
    description: 'Digs dirt and sand.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.05 },
  },
  {
    id: 'stone_shovel',
    name: 'Stone Shovel',
    description: 'Sturdier shovel for gravel.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.04 },
  },
  {
    id: 'iron_shovel',
    name: 'Iron Shovel',
    description: 'Fine iron shovel.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
    modifiers: { tickDelayScalar: 1.02 },
  },
  // Materials
  {
    id: 'cobblestone',
    name: 'Cobblestone',
    description: 'A common building block.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'torch_item',
    name: 'Torch',
    description: 'Emits light. Useful for dark places.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_beef',
    name: 'Raw Beef',
    description: 'A strip of raw cow meat. Edible, but risky.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked_beef',
    name: 'Cooked Beef',
    description: 'A strip of grilled beef. Nourishing.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'bread',
    name: 'Bread',
    description: 'A loaf of bread. Filling and safe.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'stick',
    name: 'Stick',
    description: 'A small wooden rod. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'planks_item',
    name: 'Planks',
    description: 'Processed wood. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    description: 'Refined iron. Essential for tools.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    description: 'Refined gold. Valuable.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    description: 'A precious gemstone. The hardest material.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'coal',
    name: 'Coal',
    description: 'A black mineral. Used for fuel and torches.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'bucket',
    name: 'Bucket',
    description: 'An iron bucket. For liquids and transport.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'boat',
    name: 'Boat',
    description: 'A wooden vessel for water travel.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'chest',
    name: 'Chest',
    description: 'A storage container.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ladder',
    name: 'Ladder',
    description: 'Climbable rungs. Useful for vertical movement.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'door',
    name: 'Door',
    description: 'A wooden door. Closes gaps.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'furnace',
    name: 'Furnace',
    description: 'Smelts ore and cooks food.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'rotten_flesh',
    name: 'Rotten Flesh',
    description: 'Decaying meat. Not appetizing.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'bones',
    name: 'Bones',
    description: 'Bones from the undead.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'arrows',
    name: 'Arrows',
    description: 'Wooden shafts with stone tips.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'leather',
    name: 'Leather',
    description: 'Cured hide. Soft and flexible.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'gunpowder',
    name: 'Gunpowder',
    description: 'Explosive powder from creepers.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_iron',
    name: 'Raw Iron',
    description: 'Unrefined iron ore. Needs smelting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_gold',
    name: 'Raw Gold',
    description: 'Unrefined gold ore. Needs smelting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'armors',
    name: 'Armor Pieces',
    description: 'Scrap armor. Not very useful.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'fire_charge',
    name: 'Fire Charge',
    description: 'A burning ember. From creepers.',
    kind: 'consumable',
    category: 'material',
  },
  // Farming items
  {
    id: 'seeds',
    name: 'Seeds',
    description: 'Tiny seeds. Can be planted on farmland.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'wheat',
    name: 'Wheat',
    description: 'Harvested wheat. Makes bread.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'pumpkin_item',
    name: 'Pumpkin',
    description: 'A large orange gourd. Grow on farmland.',
    kind: 'consumable',
    category: 'food',
  },
  // Armor items — leather
  {
    id: 'leather_helmet',
    name: 'Leather Helmet',
    description: 'Soft leather headgear.',
    kind: 'equipment',
    slot: 'helm',
    category: 'material',
    modifiers: { tickDelayScalar: 0.98 },
  },
  {
    id: 'leather_chestplate',
    name: 'Leather Chestplate',
    description: 'Soft leather body armor.',
    kind: 'equipment',
    slot: 'cloak',
    category: 'material',
    modifiers: { tickDelayScalar: 0.97 },
  },
  {
    id: 'leather_leggings',
    name: 'Leather Leggings',
    description: 'Soft leather leg armor.',
    kind: 'equipment',
    slot: 'belt',
    category: 'material',
    modifiers: { tickDelayScalar: 0.98 },
  },
  {
    id: 'leather_boots',
    name: 'Leather Boots',
    description: 'Soft leather foot protection.',
    kind: 'equipment',
    slot: 'boots',
    category: 'material',
    modifiers: { tickDelayScalar: 0.99 },
  },
  // Armor items — iron
  {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    description: 'Sturdy iron headgear.',
    kind: 'equipment',
    slot: 'helm',
    category: 'material',
    modifiers: { tickDelayScalar: 0.95 },
  },
  {
    id: 'iron_chestplate',
    name: 'Iron Chestplate',
    description: 'Heavy iron body armor.',
    kind: 'equipment',
    slot: 'cloak',
    category: 'material',
    modifiers: { tickDelayScalar: 0.92 },
  },
  {
    id: 'iron_leggings',
    name: 'Iron Leggings',
    description: 'Heavy iron leg armor.',
    kind: 'equipment',
    slot: 'belt',
    category: 'material',
    modifiers: { tickDelayScalar: 0.94 },
  },
  {
    id: 'iron_boots',
    name: 'Iron Boots',
    description: 'Heavy iron foot protection.',
    kind: 'equipment',
    slot: 'boots',
    category: 'material',
    modifiers: { tickDelayScalar: 0.97 },
  },
  // Armor items — diamond
  {
    id: 'diamond_helmet',
    name: 'Diamond Helmet',
    description: 'Brilliant diamond headgear.',
    kind: 'equipment',
    slot: 'helm',
    category: 'material',
    modifiers: { tickDelayScalar: 0.96 },
  },
  {
    id: 'diamond_chestplate',
    name: 'Diamond Chestplate',
    description: 'Brilliant diamond body armor.',
    kind: 'equipment',
    slot: 'cloak',
    category: 'material',
    modifiers: { tickDelayScalar: 0.93 },
  },
  {
    id: 'diamond_leggings',
    name: 'Diamond Leggings',
    description: 'Brilliant diamond leg armor.',
    kind: 'equipment',
    slot: 'belt',
    category: 'material',
    modifiers: { tickDelayScalar: 0.95 },
  },
  {
    id: 'diamond_boots',
    name: 'Diamond Boots',
    description: 'Brilliant diamond foot protection.',
    kind: 'equipment',
    slot: 'boots',
    category: 'material',
    modifiers: { tickDelayScalar: 0.97 },
  },
  // Fishing items
  {
    id: 'fishing_rod',
    name: 'Fishing Rod',
    description: 'A basic fishing rod for catching fish.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.03 },
  },
  {
    id: 'enchanted_fishing_rod',
    name: 'Enchanted Fishing Rod',
    description: 'An enchanted rod with better catch rates.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.01 },
  },
  {
    id: 'diamond_fishing_rod',
    name: 'Diamond Fishing Rod',
    description: 'A diamond fishing rod for the best catches.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
    modifiers: { tickDelayScalar: 1.0 },
  },
  {
    id: 'worm',
    name: 'Worm',
    description: 'A wriggling worm. Used as fishing bait.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    description: 'A small shrimp. Good fishing bait.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'cricket',
    name: 'Cricket',
    description: 'A live cricket. Excellent fishing bait.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'fly',
    name: 'Fly',
    description: 'A tiny fly. Decent fishing bait.',
    kind: 'consumable',
    category: 'material',
  },
  // Fish items
  {
    id: 'salmon',
    name: 'Salmon',
    description: 'A fresh salmon. Can be cooked.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked_salmon',
    name: 'Cooked Salmon',
    description: 'A grilled salmon fillet. Delicious.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cod',
    name: 'Cod',
    description: 'A fresh cod. Can be cooked.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked_cod',
    name: 'Cooked Cod',
    description: 'A grilled cod fillet. Nourishing.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'pufferfish',
    name: 'Pufferfish',
    description: 'A pufferfish. Do not eat!',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'tropical_fish',
    name: 'Tropical Fish',
    description: 'A beautiful tropical fish.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'shark',
    name: 'Shark',
    description: 'A mighty shark! A rare catch.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'shark_tooth',
    name: 'Shark Tooth',
    description: 'A sharp shark tooth. Craft material.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'whale',
    name: 'Whale',
    description: 'A magnificent whale. Extremely rare!',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'squid',
    name: 'Squid',
    description: 'A squid. Drops ink sacs.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ink_sac',
    name: 'Ink Sac',
    description: 'Black ink from squids. Crafting material.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'lobster',
    name: 'Lobster',
    description: 'A fresh lobster. Cook it for food.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'crab',
    name: 'Crab',
    description: 'A crab. Drop crab meat.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'crab_meat',
    name: 'Crab Meat',
    description: 'Fresh crab meat. Edible.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'seahorse',
    name: 'Seahorse',
    description: 'A tiny seahorse. A rare find!',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'octopus',
    name: 'Octopus',
    description: 'An octopus. A dangerous catch.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'clownfish',
    name: 'Clownfish',
    description: 'A friendly clownfish. Nemo-inspired.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'barracuda',
    name: 'Barracuda',
    description: 'A fierce barracuda. A great catch!',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'marlin',
    name: 'Marlin',
    description: 'A powerful marlin. Very rare!',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'swordfish',
    name: 'Swordfish',
    description: 'A swordfish with a long blade. Rare!',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'eel',
    name: 'Eel',
    description: 'A slippery eel. Cook it well.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'ray',
    name: 'Ray',
    description: 'A ray. A beautiful creature.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'stingray',
    name: 'Stingray',
    description: 'A stingray. Careful of the tail!',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'manta_ray',
    name: 'Manta Ray',
    description: 'A majestic manta ray. Legendary!',
    kind: 'consumable',
    category: 'material',
  },
  // Brewing items
  {
    id: 'nether_wart',
    name: 'Nether Wart',
    description: 'Grown in the Nether. Makes Awkward Potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'blaze_powder',
    name: 'Blaze Powder',
    description: 'Made from blaze rods. Fuels brewing stands.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'glowstone_dust',
    name: 'Glowstone Dust',
    description: 'Glowing dust. Upgrades potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'fermented_spider_eye',
    name: 'Fermented Spider Eye',
    description: 'Inverts potion effects.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'redstone',
    name: 'Redstone Dust',
    description: 'Extends potion duration.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'dragon_breath',
    name: 'Dragon Breath',
    description: 'Makes lingering potions. Very rare!',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'dragon_egg',
    name: 'Dragon Egg',
    description: 'A legendary catalyst. Makes Healing potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'golden_carrot',
    name: 'Golden Carrot',
    description: 'Makes Night Vision potions.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'magma_cream',
    name: 'Magma Cream',
    description: 'Makes Fire Resistance potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'pufferfish_item',
    name: 'Pufferfish (Item)',
    description: 'Makes Water Breathing potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'rabbit_foot',
    name: 'Rabbit Foot',
    description: 'Makes Jump Boost potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ghast_tear',
    name: 'Ghast Tear',
    description: 'Makes Regeneration potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'blaze_rod',
    name: 'Blaze Rod',
    description: 'Makes Strength potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ender_pearl',
    name: 'Ender Pearl',
    description: 'Makes Invisibility potions.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'enchanted_golden_apple',
    name: 'Enchanted Golden Apple',
    description: 'Grants multiple potion effects. Very rare!',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'ender_eye',
    name: 'Ender Eye',
    description: 'Used to activate End portals.',
    kind: 'consumable',
    category: 'material',
  },
  // Enchanting items
  {
    id: 'lapis_lazuli',
    name: 'Lapis Lazuli',
    description: 'A blue gemstone. Used in enchanting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'book',
    name: 'Book',
    description: 'A book. Used in enchanting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'experience_bottle',
    name: 'Experience Bottle',
    description: 'Throw to gain XP. Found in dungeons.',
    kind: 'consumable',
    category: 'material',
  },
  // Portal items
  {
    id: 'flint_and_steel',
    name: 'Flint and Steel',
    description: 'Used to light fire and portals.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'end_crystal',
    name: 'End Crystal',
    description: 'Restores health or damages entities.',
    kind: 'consumable',
    category: 'material',
  },
  // Nether items
  {
    id: 'nether_bricks',
    name: 'Nether Bricks',
    description: 'Bricks from the Nether.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'nether_star',
    name: 'Nether Star',
    description: 'Dropped by the Wither. Extremely rare!',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'magma_block',
    name: 'Magma Block',
    description: 'A block of solidified magma.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'soul_sand',
    name: 'Soul Sand',
    description: 'Slows entities that walk on it.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'soul_soil',
    name: 'Soul Soil',
    description: 'Dark soil from the Nether.',
    kind: 'consumable',
    category: 'material',
  },
  // End items
  {
    id: 'end_rod',
    name: 'End Rod',
    description: 'A glowing rod from the End.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'shulker_shell',
    name: 'Shulker Shell',
    description: 'Dropped by Shulkers. Craft shulker boxes.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'ender_pearl_item',
    name: 'Ender Pearl',
    description: 'Used for teleportation.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'elytra',
    name: 'Elytra',
    description: 'Wings for gliding through the air.',
    kind: 'equipment',
    slot: 'cloak',
    category: 'material',
    modifiers: { tickDelayScalar: 0.95 },
  },
  // Potions
  {
    id: 'potion',
    name: 'Potion',
    description: 'A brewed potion with various effects.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'splash_potion',
    name: 'Splash Potion',
    description: 'A throwable potion.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'lingering_potion',
    name: 'Lingering Potion',
    description: 'Creates a lingering potion cloud.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'glass_bottle',
    name: 'Glass Bottle',
    description: 'Used to brew potions.',
    kind: 'consumable',
    category: 'material',
  },
  // Misc crafting items
  {
    id: 'stick_from_wood',
    name: 'Stick',
    description: 'A wooden stick. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'paper',
    name: 'Paper',
    description: 'Made from sugar cane. Used in books.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'quill',
    name: 'Quill',
    description: 'A feather quill for writing.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'oak_boat',
    name: 'Oak Boat',
    description: 'Travel across water.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'minecart',
    name: 'Minecart',
    description: 'Ride on rails.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'rail',
    name: 'Rail',
    description: 'Minecart tracks.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'powered_rail',
    name: 'Powered Rail',
    description: 'Rails powered by coal.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'detector_rail',
    name: 'Detector Rail',
    description: 'Rails that detect minecarts.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'tripwire_hook',
    name: 'Tripwire Hook',
    description: 'Creates tripwire alarms.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'lever',
    name: 'Lever',
    description: 'A switch for redstone.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'redstone_torch',
    name: 'Redstone Torch',
    description: 'Emits a redstone signal.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'note_block',
    name: 'Note Block',
    description: 'Plays musical notes.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'jukebox',
    name: 'Jukebox',
    description: 'Plays music discs.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'music_disc',
    name: 'Music Disc',
    description: 'A disc for the jukebox.',
    kind: 'consumable',
    category: 'material',
  },
  // Nether Wart Block items
  {
    id: 'beacon',
    name: 'Beacon',
    description: 'Grants buffs in an area. Requires nether star.',
    kind: 'consumable',
    category: 'material',
  },
  // Structure blocks
  {
    id: 'structure_block_item',
    name: 'Structure Block',
    description: 'Saves and loads structures.',
    kind: 'consumable',
    category: 'material',
  },
  // Spawn eggs (represented as consumables)
  {
    id: 'zombie_spawn_egg',
    name: 'Zombie Spawn Egg',
    description: 'Spawns a zombie.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'skeleton_spawn_egg',
    name: 'Skeleton Spawn Egg',
    description: 'Spawns a skeleton.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'creeper_spawn_egg',
    name: 'Creeper Spawn Egg',
    description: 'Spawns a creeper.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'cow_spawn_egg',
    name: 'Cow Spawn Egg',
    description: 'Spawns a cow.',
    kind: 'consumable',
    category: 'material',
  },
  // Dye colors
  {
    id: 'white_dye',
    name: 'White Dye',
    description: 'White dye. From bones or lilies.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'red_dye',
    name: 'Red Dye',
    description: 'Red dye. From poppies.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'blue_dye',
    name: 'Blue Dye',
    description: 'Blue dye. From lapis.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'green_dye',
    name: 'Green Dye',
    description: 'Green dye. From cactus.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'black_dye',
    name: 'Black Dye',
    description: 'Black dye. From ink sacs.',
    kind: 'consumable',
    category: 'material',
  },
];

const MC_ITEM_MAP = new Map<string, Item>(MINECRAFT_ITEMS.map((item) => [item.id, item]));

export function getMinecraftItem(id: string): Item | undefined {
  return MC_ITEM_MAP.get(id);
}

export function isMinecraftItem(id: string): boolean {
  return MC_ITEM_MAP.has(id);
}

export function getMinecraftItems(): readonly Item[] {
  return MINECRAFT_ITEMS;
}
