import type { FishDefinition, FishSellOffer } from './types.js';
import type { BiomeId } from '../world/biomes.js';

export const FISH_DEFINITIONS: readonly FishDefinition[] = [
  // ===== VERDIGRIS BASIN =====
  {
    typeId: 'minnow',
    name: 'Minnow',
    description: 'A tiny silver fish. Barely fights, barely matters.',
    biomeId: 'verdigris-basin',
    rarity: 'common',
    baseScore: 1,
    minWeight: 0.1,
    maxWeight: 0.3,
    difficulty: 2,
    fightAggression: 0.2,
    fightStruggleInterval: 8,
    spawnWeight: 50,
  },
  {
    typeId: 'perch',
    name: 'Perch',
    description: 'A sturdy little fish with spikes and a grudge.',
    biomeId: 'verdigris-basin',
    rarity: 'common',
    baseScore: 2,
    minWeight: 0.3,
    maxWeight: 1.0,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 30,
  },
  // ===== EMBER WASTE =====
  {
    typeId: 'desert-catfish',
    name: 'Desert Catfish',
    description: 'Barely alive, still thrashing. The desert\'s idea of a meal.',
    biomeId: 'ember-waste',
    rarity: 'common',
    baseScore: 3,
    minWeight: 0.5,
    maxWeight: 2.0,
    difficulty: 3,
    fightAggression: 0.4,
    fightStruggleInterval: 6,
    spawnWeight: 40,
  },
  {
    typeId: 'fire-eel',
    name: 'Fire Eel',
    description: 'Warm to the touch. Some say it still sparkles.',
    biomeId: 'ember-waste',
    rarity: 'uncommon',
    baseScore: 5,
    minWeight: 1.0,
    maxWeight: 3.0,
    difficulty: 5,
    fightAggression: 0.6,
    fightStruggleInterval: 5,
    spawnWeight: 15,
  },
  // ===== MOONLIT PARISH =====
  {
    typeId: 'ice-perch',
    name: 'Ice Perch',
    description: 'Cold as regret. Crunches when you bite.',
    biomeId: 'moonlit-parish',
    rarity: 'common',
    baseScore: 2,
    minWeight: 0.3,
    maxWeight: 0.8,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 35,
  },
  {
    typeId: 'frost-trout',
    name: 'Frost Trout',
    description: 'Shimmers with a cold light. Beautiful and unforgiving.',
    biomeId: 'moonlit-parish',
    rarity: 'uncommon',
    baseScore: 4,
    minWeight: 0.8,
    maxWeight: 2.5,
    difficulty: 4,
    fightAggression: 0.5,
    fightStruggleInterval: 6,
    spawnWeight: 20,
  },
  // ===== SABLE DEPTHS =====
  {
    typeId: 'deep-minnow',
    name: 'Deep Minnow',
    description: 'Smaller than it should be. Blind, but angry.',
    biomeId: 'sable-depths',
    rarity: 'common',
    baseScore: 3,
    minWeight: 0.2,
    maxWeight: 0.5,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 40,
  },
  {
    typeId: 'abyss-catfish',
    name: 'Abyss Catfish',
    description: 'Whiskers like cable. Mouth like a vault.',
    biomeId: 'sable-depths',
    rarity: 'uncommon',
    baseScore: 6,
    minWeight: 1.0,
    maxWeight: 4.0,
    difficulty: 5,
    fightAggression: 0.5,
    fightStruggleInterval: 5,
    spawnWeight: 25,
  },
  {
    typeId: 'shadow-eel',
    name: 'Shadow Eel',
    description: 'You cannot see it, but you feel it pulling.',
    biomeId: 'sable-depths',
    rarity: 'rare',
    baseScore: 12,
    minWeight: 3.0,
    maxWeight: 8.0,
    difficulty: 7,
    fightAggression: 0.7,
    fightStruggleInterval: 4,
    spawnWeight: 8,
  },
  // ===== GLOAM GARDEN =====
  {
    typeId: 'garden-carp',
    name: 'Garden Carp',
    description: 'Fat and patient. It knew you were coming.',
    biomeId: 'gloam-garden',
    rarity: 'common',
    baseScore: 3,
    minWeight: 0.5,
    maxWeight: 1.5,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 35,
  },
  {
    typeId: 'moon-perch',
    name: 'Moon Perch',
    description: 'Reflects moonlight even when the sky is gone.',
    biomeId: 'gloam-garden',
    rarity: 'uncommon',
    baseScore: 5,
    minWeight: 1.0,
    maxWeight: 3.0,
    difficulty: 4,
    fightAggression: 0.4,
    fightStruggleInterval: 6,
    spawnWeight: 25,
  },
  // ===== ELDERWOOD MAZE =====
  {
    typeId: 'swamp-catfish',
    name: 'Swamp Catfish',
    description: 'Mud in its gills, mud in its eyes, mud in its soul.',
    biomeId: 'elderwood-maze',
    rarity: 'common',
    baseScore: 3,
    minWeight: 0.5,
    maxWeight: 2.0,
    difficulty: 3,
    fightAggression: 0.4,
    fightStruggleInterval: 6,
    spawnWeight: 30,
  },
  {
    typeId: 'forest-eel',
    name: 'Forest Eel',
    description: 'Root-tangled and venomous. Do not let it touch you.',
    biomeId: 'elderwood-maze',
    rarity: 'uncommon',
    baseScore: 6,
    minWeight: 1.5,
    maxWeight: 4.0,
    difficulty: 5,
    fightAggression: 0.5,
    fightStruggleInterval: 5,
    spawnWeight: 18,
  },
  {
    typeId: 'kelp-serpent',
    name: 'Kelp Serpent',
    description: 'Long as a corridor. Hungrier than a promise.',
    biomeId: 'elderwood-maze',
    rarity: 'rare',
    baseScore: 15,
    minWeight: 4.0,
    maxWeight: 10.0,
    difficulty: 8,
    fightAggression: 0.7,
    fightStruggleInterval: 4,
    spawnWeight: 7,
  },
  // ===== SUNKEN OCEAN =====
  {
    typeId: 'reef-fish',
    name: 'Reef Fish',
    description: 'Colorful, confused, and very willing to bite.',
    biomeId: 'sunken-ocean',
    rarity: 'common',
    baseScore: 3,
    minWeight: 0.3,
    maxWeight: 1.0,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 35,
  },
  {
    typeId: 'ocean-bass',
    name: 'Ocean Bass',
    description: 'Heavy as a brick. Fast as a grudge.',
    biomeId: 'sunken-ocean',
    rarity: 'uncommon',
    baseScore: 6,
    minWeight: 1.0,
    maxWeight: 5.0,
    difficulty: 5,
    fightAggression: 0.5,
    fightStruggleInterval: 5,
    spawnWeight: 25,
  },
  {
    typeId: 'blue-marlin',
    name: 'Blue Marlin',
    description: 'A blade with fins. You respect it. It may respect you back.',
    biomeId: 'sunken-ocean',
    rarity: 'rare',
    baseScore: 15,
    minWeight: 5.0,
    maxWeight: 20.0,
    difficulty: 8,
    fightAggression: 0.7,
    fightStruggleInterval: 3,
    spawnWeight: 10,
  },
  {
    typeId: 'kraken-baitfish',
    name: 'Kraken Baitfish',
    description: 'Not the kraken itself. Just what the kraken wants for breakfast.',
    biomeId: 'sunken-ocean',
    rarity: 'legendary',
    baseScore: 30,
    minWeight: 20.0,
    maxWeight: 50.0,
    difficulty: 10,
    fightAggression: 0.9,
    fightStruggleInterval: 3,
    spawnWeight: 3,
  },
  // ===== JADE PEAK PROVINCE =====
  {
    typeId: 'koi',
    name: 'Koi',
    description: 'Painted by monks. Swum by pilgrims. Caught by you.',
    biomeId: 'jade-peak-province',
    rarity: 'common',
    baseScore: 4,
    minWeight: 0.5,
    maxWeight: 2.0,
    difficulty: 3,
    fightAggression: 0.3,
    fightStruggleInterval: 7,
    spawnWeight: 35,
  },
  {
    typeId: 'golden-koi',
    name: 'Golden Koi',
    description: 'The color of a wish you did not make soon enough.',
    biomeId: 'jade-peak-province',
    rarity: 'uncommon',
    baseScore: 8,
    minWeight: 2.0,
    maxWeight: 5.0,
    difficulty: 5,
    fightAggression: 0.4,
    fightStruggleInterval: 6,
    spawnWeight: 20,
  },
  {
    typeId: 'dragon-carp',
    name: 'Dragon Carp',
    description: 'Old enough to remember the mountain as it was.',
    biomeId: 'jade-peak-province',
    rarity: 'rare',
    baseScore: 18,
    minWeight: 5.0,
    maxWeight: 15.0,
    difficulty: 8,
    fightAggression: 0.7,
    fightStruggleInterval: 4,
    spawnWeight: 8,
  },
  // ===== LIBERTY BADLANDS =====
  {
    typeId: 'prairie-minnow',
    name: 'Prairie Minnow',
    description: 'Tiny, tough, and absolutely unimpressed by you.',
    biomeId: 'liberty-badlands',
    rarity: 'common',
    baseScore: 2,
    minWeight: 0.2,
    maxWeight: 0.5,
    difficulty: 2,
    fightAggression: 0.2,
    fightStruggleInterval: 8,
    spawnWeight: 35,
  },
  {
    typeId: 'badlands-bass',
    name: 'Badlands Bass',
    description: 'Built for dust and drought. Still fights.',
    biomeId: 'liberty-badlands',
    rarity: 'uncommon',
    baseScore: 5,
    minWeight: 1.0,
    maxWeight: 4.0,
    difficulty: 4,
    fightAggression: 0.4,
    fightStruggleInterval: 6,
    spawnWeight: 25,
  },
  {
    typeId: 'jackalope-lure',
    name: 'Jackalope Lure',
    description: 'Part fish, part myth, all trouble.',
    biomeId: 'liberty-badlands',
    rarity: 'rare',
    baseScore: 12,
    minWeight: 3.0,
    maxWeight: 10.0,
    difficulty: 7,
    fightAggression: 0.6,
    fightStruggleInterval: 5,
    spawnWeight: 8,
  },
];

/** Mapping from fish type id to definition */
const FISH_MAP = new Map<string, FishDefinition>(
  FISH_DEFINITIONS.map((f) => [f.typeId, f]),
);

/** Lookup a fish definition by type id */
export function getFishDefinition(typeId: string): FishDefinition | undefined {
  return FISH_MAP.get(typeId);
}

/** Get all fish definitions for a given biome */
export function getFishByBiome(biomeId: BiomeId): readonly FishDefinition[] {
  return FISH_DEFINITIONS.filter((f) => f.biomeId === biomeId);
}

/** Weighted random selection among fish for a biome */
export function pickRandomFish(biomeId: BiomeId, rng: () => number): FishDefinition | undefined {
  const fish = getFishByBiome(biomeId);
  if (fish.length === 0) return undefined;

  const totalWeight = fish.reduce((sum, f) => sum + f.spawnWeight, 0);
  let roll = rng() * totalWeight;

  for (const f of fish) {
    roll -= f.spawnWeight;
    if (roll <= 0) return f;
  }

  return fish[fish.length - 1];
}

/** All fish sell offers (for shop integration) */
export const FISH_SELL_OFFERS: readonly FishSellOffer[] = FISH_DEFINITIONS.map((f) => ({
  typeId: f.typeId,
  id: `fish-${f.typeId}`,
  itemId: `fish-${f.typeId}`,
  name: f.name,
  sellPrice: Math.max(1, Math.floor(f.baseScore * 0.6)),
}));
