import type {
  SkillBranchId,
  SkillEffect,
  SkillNodeKind,
  SkillPerkDefinition,
} from './skillTypes.js';

interface PerkInput {
  id: string;
  title: string;
  shortLabel: string;
  description: string;
  branchId: SkillBranchId;
  kind: SkillNodeKind;
  tier: number;
  lane?: number;
  route?: string;
  requires?: readonly string[];
  cost: number;
  effects: readonly SkillEffect[];
  secondaryBranch?: SkillBranchId;
  tags?: readonly string[];
  grantableAtStart?: boolean;
  migrationAliases?: readonly string[];
}

const BRANCH_LABELS: Record<SkillBranchId, string> = {
  momentum: 'Momentum',
  survival: 'Survival',
  arcane: 'Arcane',
  growth: 'Growth',
  predator: 'Predator',
  fellowship: 'Fellowship',
};

const flag = (key: string, value: unknown, resetValue?: unknown): SkillEffect => ({
  type: 'setFlag',
  key,
  value,
  resetValue,
});

function perk(input: PerkInput): SkillPerkDefinition {
  return {
    id: input.id,
    title: input.title,
    shortLabel: input.shortLabel,
    description: input.description,
    branch: BRANCH_LABELS[input.branchId],
    branchId: input.branchId,
    secondaryBranch: input.secondaryBranch,
    kind: input.kind,
    route: input.route,
    tags: input.tags ?? [],
    grantableAtStart: input.grantableAtStart,
    migrationAliases: input.migrationAliases,
    rankDescriptions: [input.description],
    costByRank: [input.cost],
    effectsByRank: [input.effects],
    requires: input.requires,
    position: { x: input.lane ?? 0, y: input.tier },
  };
}

const momentum: SkillPerkDefinition[] = [
  perk({
    id: 'swiftScales',
    title: 'Swift Scales',
    shortLabel: 'SWIFT',
    description:
      'Straight movement builds up to 5 Momentum. At 5, spend 3 for a 3-tick Surge and 2 ward ticks. Turning keeps 25%; decay starts after 4 idle ticks.',
    branchId: 'momentum',
    kind: 'entry',
    tier: 0,
    cost: 12,
    grantableAtStart: true,
    tags: ['momentum', 'surge'],
    effects: [
      flag('momentum.config.swiftScales', {
        enabled: true,
        maxStacks: 5,
        baseGain: 1,
        decayDelay: 4,
        decayLoss: 1,
        turnRetention: 0.25,
        surgeThreshold: 5,
        surgeDuration: 3,
        surgeCooldown: 10,
        surgeConsume: 3,
        surgeInvulnerability: 2,
        phaseTicksOnSurge: 0,
        scorePerStack: 0,
        surgeScore: 0,
        trailTicks: 0,
        trailScorePerTick: 0,
      }),
    ],
  }),
  perk({
    id: 'corneringInstinct',
    title: 'Cornering Instinct',
    shortLabel: 'TURN',
    description: 'Sharp pivots gain 2 forgiveness ticks and retain 25% more Momentum.',
    branchId: 'momentum',
    kind: 'core',
    tier: 1,
    requires: ['swiftScales'],
    cost: 24,
    migrationAliases: ['hyperReflex'],
    tags: ['momentum'],
    effects: [
      flag('momentum.config.corneringInstinct', { turnForgiveness: 2, turnRetentionBonus: 0.25 }),
    ],
  }),
  perk({
    id: 'slipstream',
    title: 'Slipstream',
    shortLabel: 'STREAM',
    description: 'Surges leave a 6-tick trail that followers can use.',
    branchId: 'momentum',
    kind: 'core',
    tier: 2,
    requires: ['corneringInstinct'],
    cost: 38,
    migrationAliases: ['quantumTrail'],
    tags: ['surge', 'trail'],
    effects: [flag('momentum.config.slipstream', { trailTicks: 6, trailScorePerTick: 0 })],
  }),
  perk({
    id: 'windShear',
    title: 'Wind Shear',
    shortLabel: 'FLOW',
    description: 'Retain 50% more Momentum on turns; decay starts 3 ticks later.',
    branchId: 'momentum',
    kind: 'route',
    route: 'flow',
    tier: 3,
    lane: -1,
    requires: ['slipstream'],
    cost: 54,
    tags: ['momentum', 'surge'],
    effects: [flag('momentum.config.windShear', { turnRetentionBonus: 0.5, decayDelayBonus: 3 })],
  }),
  perk({
    id: 'phaseStride',
    title: 'Phase Stride',
    shortLabel: 'PHASE',
    description: 'Surges grant 3 phase ticks and 1 ward tick. Room entry grants 3 phase ticks.',
    branchId: 'momentum',
    kind: 'route',
    route: 'flow',
    tier: 4,
    lane: -1,
    requires: ['windShear'],
    cost: 72,
    tags: ['surge', 'phase'],
    effects: [
      flag('momentum.config.phaseStride', {
        phaseTicksOnSurgeBonus: 3,
        surgeInvulnerabilityBonus: 1,
      }),
      flag('traversal.config.phaseSlip', { phaseTicksOnEnterBonus: 3 }),
    ],
  }),
  perk({
    id: 'endlessRoad',
    title: 'Endless Road',
    shortLabel: 'ENDLESS',
    description:
      'Surges last 2 ticks longer and recharge 2 ticks sooner. Room entry grants 2 phase ticks.',
    branchId: 'momentum',
    kind: 'capstone',
    route: 'flow',
    tier: 5,
    lane: -1,
    requires: ['phaseStride'],
    cost: 110,
    migrationAliases: ['chronoSurge'],
    tags: ['momentum', 'surge'],
    effects: [
      flag('momentum.config.endlessRoad', { surgeDurationBonus: 2, surgeCooldownBonus: -2 }),
      flag('traversal.config.endlessRoad', { phaseTicksOnEnterBonus: 2 }),
    ],
  }),
  perk({
    id: 'overclock',
    title: 'Overclock',
    shortLabel: 'IMPACT',
    description: 'Surges last 2 ticks longer, recharge 3 ticks sooner, and cost 1 less Momentum.',
    branchId: 'momentum',
    kind: 'route',
    route: 'impact',
    tier: 3,
    lane: 1,
    requires: ['slipstream'],
    cost: 54,
    tags: ['momentum', 'surge'],
    effects: [
      flag('momentum.config.overclock', {
        surgeDurationBonus: 2,
        surgeCooldownBonus: -3,
        surgeConsumeBonus: -1,
      }),
    ],
  }),
  perk({
    id: 'kineticRelease',
    title: 'Kinetic Release',
    shortLabel: 'RELEASE',
    description: 'Spending full Momentum clears nearby collision hazards.',
    branchId: 'momentum',
    kind: 'capstone',
    route: 'impact',
    tier: 4,
    lane: 1,
    requires: ['overclock'],
    cost: 96,
    migrationAliases: ['rashMomentum'],
    tags: ['momentum', 'surge'],
    effects: [flag('momentum.kineticRelease', { enabled: true })],
  }),
];

const survival: SkillPerkDefinition[] = [
  perk({
    id: 'thickScales',
    title: 'Thick Scales',
    shortLabel: 'HEART',
    description: 'Maximum hearts +1.',
    branchId: 'survival',
    kind: 'entry',
    tier: 0,
    cost: 18,
    grantableAtStart: true,
    tags: ['health'],
    effects: [
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.thickScales',
        stat: 'maxHealth',
        operation: 'add',
        value: 1,
      },
    ],
  }),
  perk({
    id: 'secondWind',
    title: 'Second Wind',
    shortLabel: 'RECOVER',
    description: 'Surviving a critical hit triggers Second Wind recovery.',
    branchId: 'survival',
    kind: 'core',
    tier: 1,
    requires: ['thickScales'],
    cost: 28,
    tags: ['recovery'],
    effects: [flag('survival.secondWind', { enabled: true })],
  }),
  perk({
    id: 'fieldcraft',
    title: 'Fieldcraft',
    shortLabel: 'CAMP',
    description:
      'Unlock basic meat and fish recipes at kitchens, diners, ramen stands, and campfires.',
    branchId: 'survival',
    kind: 'core',
    tier: 2,
    requires: ['secondWind'],
    cost: 40,
    migrationAliases: ['campCook'],
    tags: ['cooking'],
    effects: [flag('skill.homestead.campCook', true, false)],
  }),
  perk({
    id: 'hardenedScales',
    title: 'Hardened Scales',
    shortLabel: 'BLOCK',
    description: 'Gain 1 self-collision prevention charge.',
    branchId: 'survival',
    kind: 'route',
    route: 'bulwark',
    tier: 3,
    lane: -1,
    requires: ['fieldcraft'],
    cost: 56,
    tags: ['ward'],
    effects: [flag('fortitude.hardened', { charges: 1 })],
  }),
  perk({
    id: 'wardedBody',
    title: 'Warded Body',
    shortLabel: 'WARD',
    description: 'Eligible food grants 6 ward ticks.',
    branchId: 'survival',
    kind: 'capstone',
    route: 'bulwark',
    tier: 4,
    lane: -1,
    requires: ['hardenedScales'],
    cost: 86,
    migrationAliases: ['shieldMatron', 'wardedStride'],
    tags: ['ward'],
    effects: [
      flag('fortitude.invulnerability', { enabled: true }),
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.wardedBody',
        stat: 'wardDuration',
        operation: 'add',
        value: 6,
      },
    ],
  }),
  perk({
    id: 'bloodBank',
    title: 'Blood Bank',
    shortLabel: 'BANK',
    description: 'Store 4 food-vitality charges; a full bank grows 2 segments.',
    branchId: 'survival',
    kind: 'route',
    route: 'renewal',
    tier: 3,
    lane: 1,
    requires: ['fieldcraft'],
    cost: 56,
    tags: ['recovery', 'nutrition'],
    effects: [
      flag('fortitude.bloodBank', { stored: 0, capacity: 4, reward: { score: 0, growth: 2 } }),
    ],
  }),
  perk({
    id: 'regenerator',
    title: 'Regenerator',
    shortLabel: 'REGEN',
    description: 'While critically short, grow 1 segment every 36 movement ticks.',
    branchId: 'survival',
    kind: 'route',
    route: 'renewal',
    tier: 4,
    lane: 1,
    requires: ['bloodBank'],
    cost: 78,
    tags: ['recovery'],
    effects: [flag('fortitude.regenerator', { interval: 36, amount: 1, criticalOnly: true })],
  }),
  perk({
    id: 'oneMoreChance',
    title: 'One More Chance',
    shortLabel: 'LIFE',
    description: 'Extra-life charges +1.',
    branchId: 'survival',
    kind: 'route',
    route: 'renewal',
    tier: 5,
    lane: 1,
    requires: ['regenerator'],
    cost: 104,
    tags: ['revival'],
    effects: [
      { type: 'extraLifeCharge', count: 1 },
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.oneMoreChance',
        stat: 'extraLifeCapacity',
        operation: 'add',
        value: 1,
      },
    ],
  }),
  perk({
    id: 'phoenixFrame',
    title: 'Phoenix Frame',
    shortLabel: 'PHOENIX',
    description: 'Phoenix revival charges +1; revival grants post-revival protection.',
    branchId: 'survival',
    kind: 'capstone',
    route: 'renewal',
    tier: 6,
    lane: 1,
    requires: ['oneMoreChance'],
    cost: 132,
    tags: ['revival'],
    effects: [flag('fortitude.phoenix', { charges: 1 })],
  }),
];

const arcane: SkillPerkDefinition[] = [
  perk({
    id: 'manaBloom',
    title: 'Mana Bloom',
    shortLabel: 'MANA',
    description: 'Unlock mana: 60 capacity, 1.2 regeneration per tick, starting full.',
    branchId: 'arcane',
    kind: 'entry',
    tier: 0,
    cost: 22,
    grantableAtStart: true,
    tags: ['mana'],
    effects: [
      { type: 'manaEnable', max: 0, regen: 0 },
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.manaBloom',
        stat: 'manaMax',
        operation: 'add',
        value: 60,
      },
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.manaBloom',
        stat: 'manaRegen',
        operation: 'add',
        value: 1.2,
      },
    ],
  }),
  perk({
    id: 'spellbook',
    title: 'Spellbook',
    shortLabel: 'SPELL',
    description: 'Unlock the spellbook and spell assignment.',
    branchId: 'arcane',
    kind: 'core',
    tier: 1,
    requires: ['manaBloom'],
    cost: 30,
    migrationAliases: ['manaWeave'],
    tags: ['spell'],
    effects: [flag('arcane.spellbook', { enabled: true })],
  }),
  perk({
    id: 'arcanePulse',
    title: 'Arcane Pulse',
    shortLabel: 'PULSE',
    description: 'Arcane Pulse costs 20 mana, grants 4 score, and grows 2 segments.',
    branchId: 'arcane',
    kind: 'core',
    tier: 2,
    requires: ['spellbook'],
    cost: 44,
    tags: ['spell'],
    effects: [{ type: 'unlockArcanePulse' }],
  }),
  perk({
    id: 'preparedCaster',
    title: 'Prepared Caster',
    shortLabel: 'PREP',
    description: 'Prepared spell slots +1.',
    branchId: 'arcane',
    kind: 'route',
    route: 'prepared',
    tier: 3,
    lane: -1,
    requires: ['arcanePulse'],
    cost: 58,
    tags: ['spell', 'slot'],
    effects: [
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.preparedCaster',
        stat: 'spellSlotCapacity',
        operation: 'add',
        value: 1,
      },
    ],
  }),
  perk({
    id: 'spellweaver',
    title: 'Spellweaver',
    shortLabel: 'WEAVE',
    description: 'Different consecutive spell tags activate Spellweaver sequences.',
    branchId: 'arcane',
    kind: 'capstone',
    route: 'prepared',
    tier: 4,
    lane: -1,
    requires: ['preparedCaster'],
    cost: 92,
    migrationAliases: ['spellforge', 'fluxCondenser'],
    tags: ['spell'],
    effects: [flag('arcane.spellweaver', { enabled: true })],
  }),
  perk({
    id: 'overcast',
    title: 'Overcast',
    shortLabel: 'OVERCAST',
    description: 'Cast without enough mana by spending body resources.',
    branchId: 'arcane',
    kind: 'route',
    route: 'channeler',
    tier: 3,
    lane: 1,
    requires: ['arcanePulse'],
    cost: 58,
    tags: ['spell', 'overcast'],
    effects: [flag('arcane.overcast', { enabled: true })],
  }),
  perk({
    id: 'sparkReservoir',
    title: 'Spark Reservoir',
    shortLabel: 'DOUBLE',
    description: 'Maximum mana +60.',
    branchId: 'arcane',
    kind: 'route',
    route: 'channeler',
    tier: 4,
    lane: 1,
    requires: ['overcast'],
    cost: 82,
    tags: ['mana'],
    effects: [
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.sparkReservoir',
        stat: 'manaMax',
        operation: 'add',
        value: 60,
      },
    ],
  }),
  perk({
    id: 'astralNova',
    title: 'Astral Nova',
    shortLabel: 'NOVA',
    description: 'A fully committed Overcast triggers Astral Nova.',
    branchId: 'arcane',
    kind: 'capstone',
    route: 'channeler',
    tier: 5,
    lane: 1,
    requires: ['sparkReservoir'],
    cost: 118,
    tags: ['spell', 'overcast'],
    effects: [flag('arcane.astralNova', { enabled: true })],
  }),
];

const growth: SkillPerkDefinition[] = [
  perk({
    id: 'controlledShedding',
    title: 'Controlled Shedding',
    shortLabel: 'SHED',
    description: 'Spend 3 safe segments to create a decoy. Cooldown: 20 ticks.',
    branchId: 'growth',
    kind: 'entry',
    tier: 0,
    cost: 16,
    grantableAtStart: true,
    migrationAliases: ['shed'],
    tags: ['length', 'shed'],
    effects: [flag('skill.tailcraft.shed', true, false)],
  }),
  perk({
    id: 'reserveNutrition',
    title: 'Reserve Nutrition',
    shortLabel: 'RESERVE',
    description: 'Store up to 4 unused food-growth charges.',
    branchId: 'growth',
    kind: 'core',
    tier: 1,
    requires: ['controlledShedding'],
    cost: 28,
    tags: ['nutrition'],
    effects: [
      flag('growth.reserveNutrition', { stored: 0 }),
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.reserveNutrition',
        stat: 'nutritionCapacity',
        operation: 'add',
        value: 4,
      },
    ],
  }),
  perk({
    id: 'digestiveChoice',
    title: 'Digestive Choice',
    shortLabel: 'DIGEST',
    description: 'Route eligible food to growth, Stored Nutrition, or recovery.',
    branchId: 'growth',
    kind: 'core',
    tier: 2,
    requires: ['reserveNutrition'],
    cost: 42,
    migrationAliases: ['gourmand'],
    tags: ['nutrition'],
    effects: [flag('growth.digestiveChoice', { mode: 'growth' })],
  }),
  perk({
    id: 'overgrown',
    title: 'Overgrown',
    shortLabel: 'HUGE',
    description: 'At Overgrown length, pickup radius gains 1 tile.',
    branchId: 'growth',
    kind: 'route',
    route: 'colossus',
    tier: 3,
    lane: -1,
    requires: ['digestiveChoice'],
    cost: 58,
    tags: ['length'],
    effects: [
      flag('growth.overgrown', { enabled: true }),
      {
        type: 'derivedStatModifier',
        sourceId: 'skill.overgrown',
        stat: 'pickupRadius',
        operation: 'add',
        value: 1,
      },
    ],
  }),
  perk({
    id: 'rootedColossus',
    title: 'Rooted Colossus',
    shortLabel: 'ROOTED',
    description: 'Extreme length plus slow movement grants collision resistance.',
    branchId: 'growth',
    kind: 'route',
    route: 'colossus',
    tier: 4,
    lane: -1,
    requires: ['overgrown'],
    cost: 84,
    tags: ['length', 'ward'],
    effects: [flag('growth.rootedColossus', { enabled: true })],
  }),
  perk({
    id: 'tooBigToFail',
    title: 'Too Big to Fail',
    shortLabel: 'MASS',
    description: 'At 12+ segments, lose 8 segments instead of dying.',
    branchId: 'growth',
    kind: 'capstone',
    route: 'colossus',
    tier: 5,
    lane: -1,
    requires: ['rootedColossus'],
    cost: 124,
    tags: ['length', 'revival'],
    effects: [flag('growth.tooBigToFail', { minimumLength: 12, cost: 8 })],
  }),
  perk({
    id: 'livingDecoy',
    title: 'Living Decoy',
    shortLabel: 'DECOY',
    description: 'Shed decoys become valid targets for nearby hostile actors.',
    branchId: 'growth',
    kind: 'route',
    route: 'metamorphosis',
    tier: 3,
    lane: 1,
    requires: ['digestiveChoice'],
    cost: 58,
    tags: ['shed'],
    effects: [flag('growth.livingDecoy', { enabled: true })],
  }),
  perk({
    id: 'rapidRegrowth',
    title: 'Rapid Regrowth',
    shortLabel: 'REGROW',
    description: 'Intentional length spending accelerates regrowth; damage does not.',
    branchId: 'growth',
    kind: 'route',
    route: 'metamorphosis',
    tier: 4,
    lane: 1,
    requires: ['livingDecoy'],
    cost: 82,
    migrationAliases: ['verdantGrowth', 'seasonalBloom'],
    tags: ['length', 'shed'],
    effects: [flag('growth.rapidRegrowth', { enabled: true })],
  }),
  perk({
    id: 'ouroboros',
    title: 'Ouroboros',
    shortLabel: 'LOOP',
    description: 'Spent length charges the next growth event. Echoed growth cannot recharge it.',
    branchId: 'growth',
    kind: 'capstone',
    route: 'metamorphosis',
    tier: 5,
    lane: 1,
    requires: ['rapidRegrowth'],
    cost: 120,
    tags: ['length', 'shed'],
    effects: [flag('growth.ouroboros', { enabled: true })],
  }),
];

const predator: SkillPerkDefinition[] = [
  perk({
    id: 'predatorInstinct',
    title: 'Predator Instinct',
    shortLabel: 'MARK',
    description: 'Hunt harmless animals. Animal bonus-drop chance +15 percentage points.',
    branchId: 'predator',
    kind: 'entry',
    tier: 0,
    cost: 12,
    grantableAtStart: true,
    migrationAliases: ['predatorI'],
    tags: ['prey', 'mark'],
    effects: [
      flag('skill.predator.huntHarmless', true, false),
      flag('skill.predator.dropBonus', true, false),
    ],
  }),
  perk({
    id: 'huntMomentum',
    title: 'Hunt Momentum',
    shortLabel: 'HUNT',
    description: 'Prey actions within 28 ticks build 4 Hunt Momentum. Decay starts after 6 ticks.',
    branchId: 'predator',
    kind: 'core',
    tier: 1,
    requires: ['predatorInstinct'],
    cost: 22,
    migrationAliases: ['scoreFlow'],
    tags: ['prey', 'hunt'],
    effects: [
      flag('predation.config.scoreFlow', {
        enabled: true,
        window: 28,
        decayHold: 6,
        decayStep: 1,
        maxStacks: 4,
        stackGain: 1,
        scorePerStack: 0,
      }),
    ],
  }),
  perk({
    id: 'rend',
    title: 'Rend',
    shortLabel: 'REND',
    description:
      'Quick prey actions grant bonus Momentum. At 2 stacks, gain 1 Rend that grows 1 segment.',
    branchId: 'predator',
    kind: 'core',
    tier: 2,
    requires: ['huntMomentum'],
    cost: 38,
    migrationAliases: ['doubleBite'],
    tags: ['prey', 'rend'],
    effects: [
      flag('predation.config.doubleBite', {
        quickEatWindow: 8,
        bonusStacksOnQuickEat: 1,
        rend: { enabled: true, gainThreshold: 2, maxCharges: 1, growthPerCharge: 1 },
      }),
    ],
  }),
  perk({
    id: 'bloodScent',
    title: 'Blood Scent',
    shortLabel: 'SCENT',
    description: 'Hunt window +8 ticks. Scent marks last 14 ticks.',
    branchId: 'predator',
    kind: 'route',
    route: 'pursuit',
    tier: 3,
    lane: -1,
    requires: ['rend'],
    cost: 54,
    migrationAliases: ['huntress'],
    tags: ['prey', 'mark'],
    effects: [flag('predation.config.bloodScent', { windowBonus: 8, scentDuration: 14 })],
  }),
  perk({
    id: 'feedingFrenzy',
    title: 'Feeding Frenzy',
    shortLabel: 'FRENZY',
    description: 'At 5 Hunt Momentum, trigger a 9-tick Frenzy.',
    branchId: 'predator',
    kind: 'route',
    route: 'pursuit',
    tier: 4,
    lane: -1,
    requires: ['bloodScent'],
    cost: 78,
    migrationAliases: ['bloodMoon'],
    tags: ['prey', 'frenzy'],
    effects: [
      flag('predation.config.feedingFrenzy', {
        frenzy: { threshold: 5, duration: 9, scoreBonus: 0 },
      }),
    ],
  }),
  perk({
    id: 'apexPounce',
    title: 'Apex Pounce',
    shortLabel: 'APEX',
    description: 'During Frenzy, spend 6 Momentum to grow 2. Cooldown 18 ticks; Frenzy +4 ticks.',
    branchId: 'predator',
    kind: 'capstone',
    route: 'pursuit',
    tier: 5,
    lane: -1,
    requires: ['feedingFrenzy'],
    cost: 116,
    tags: ['prey', 'frenzy'],
    effects: [
      flag('predation.config.apexPounce', {
        apex: { requiredStacks: 6, score: 0, growth: 2, cooldown: 18 },
        frenzy: { durationBonus: 4 },
      }),
    ],
  }),
  perk({
    id: 'stillHunter',
    title: 'Still Hunter',
    shortLabel: 'AMBUSH',
    description: 'Moving slowly while unnoticed prepares an Ambush.',
    branchId: 'predator',
    kind: 'route',
    route: 'ambush',
    tier: 3,
    lane: 1,
    requires: ['rend'],
    cost: 54,
    migrationAliases: ['ambushSense'],
    tags: ['prey', 'ambush'],
    effects: [flag('predator.stillHunter', { enabled: true })],
  }),
  perk({
    id: 'firstBlood',
    title: 'First Blood',
    shortLabel: 'FIRST',
    description: 'The first strike against unaware prey gains First Blood.',
    branchId: 'predator',
    kind: 'route',
    route: 'ambush',
    tier: 4,
    lane: 1,
    requires: ['stillHunter'],
    cost: 78,
    tags: ['prey', 'ambush'],
    effects: [flag('predator.firstBlood', { enabled: true })],
  }),
  perk({
    id: 'perfectPredator',
    title: 'Perfect Predator',
    shortLabel: 'PERFECT',
    description: 'Ambush primes Frenzy or transfers the mark to nearby prey.',
    branchId: 'predator',
    kind: 'capstone',
    route: 'ambush',
    tier: 5,
    lane: 1,
    requires: ['firstBlood'],
    cost: 116,
    migrationAliases: ['devourer'],
    tags: ['prey', 'ambush', 'frenzy'],
    effects: [flag('predator.perfectPredator', { enabled: true })],
  }),
];

const fellowship: SkillPerkDefinition[] = [
  perk({
    id: 'peoplePerson',
    title: 'People Person',
    shortLabel: 'CONNECT',
    description: 'Eligible relationships become Connections.',
    branchId: 'fellowship',
    kind: 'entry',
    tier: 0,
    cost: 14,
    grantableAtStart: true,
    tags: ['connection'],
    effects: [flag('fellowship.connections', { enabled: true })],
  }),
  perk({
    id: 'favorsOwed',
    title: 'Favors Owed',
    shortLabel: 'FAVOR',
    description: 'Each Connection offers 1 role-specific service.',
    branchId: 'fellowship',
    kind: 'core',
    tier: 1,
    requires: ['peoplePerson'],
    cost: 26,
    tags: ['connection', 'service'],
    effects: [flag('fellowship.favors', { enabled: true })],
  }),
  perk({
    id: 'introductions',
    title: 'Introductions',
    shortLabel: 'INTRO',
    description: 'Connections improve introductions to related actors and factions.',
    branchId: 'fellowship',
    kind: 'core',
    tier: 2,
    requires: ['favorsOwed'],
    cost: 40,
    tags: ['connection', 'reputation'],
    effects: [flag('fellowship.introductions', { enabled: true })],
  }),
  perk({
    id: 'packTactics',
    title: 'Pack Tactics',
    shortLabel: 'PACK',
    description: 'Coordinated attacks with companions gain Pack Tactics credit.',
    branchId: 'fellowship',
    kind: 'route',
    route: 'inner-circle',
    tier: 3,
    lane: -1,
    requires: ['introductions'],
    cost: 56,
    migrationAliases: ['packInstinct'],
    tags: ['connection', 'companion'],
    effects: [flag('fellowship.packTactics', { enabled: true })],
  }),
  perk({
    id: 'nobodyLeftBehind',
    title: 'Nobody Left Behind',
    shortLabel: 'RESCUE',
    description: 'A deeply bonded companion can rescue you once before life charges.',
    branchId: 'fellowship',
    kind: 'route',
    route: 'inner-circle',
    tier: 4,
    lane: -1,
    requires: ['packTactics'],
    cost: 88,
    tags: ['connection', 'companion', 'revival'],
    effects: [flag('fellowship.rescue', { enabled: true })],
  }),
  perk({
    id: 'chosenFamily',
    title: 'Chosen Family',
    shortLabel: 'FAMILY',
    description: 'Inner Circle members inherit 1 compatible support effect.',
    branchId: 'fellowship',
    kind: 'capstone',
    route: 'inner-circle',
    tier: 5,
    lane: -1,
    requires: ['nobodyLeftBehind'],
    cost: 126,
    tags: ['connection', 'companion'],
    effects: [flag('fellowship.chosenFamily', { enabled: true })],
  }),
  perk({
    id: 'preferredCustomer',
    title: 'Preferred Customer',
    shortLabel: 'RESERVE',
    description: 'Connected merchants gain 1 reserved stock slot.',
    branchId: 'fellowship',
    kind: 'route',
    route: 'wide-network',
    tier: 3,
    lane: 1,
    requires: ['introductions'],
    cost: 56,
    tags: ['connection', 'merchant'],
    effects: [flag('fellowship.preferredCustomer', { enabled: true })],
  }),
  perk({
    id: 'specialOrder',
    title: 'Special Order',
    shortLabel: 'ORDER',
    description: 'Connected merchants accept 1 category-based special order.',
    branchId: 'fellowship',
    kind: 'route',
    route: 'wide-network',
    tier: 4,
    lane: 1,
    requires: ['preferredCustomer'],
    cost: 88,
    tags: ['connection', 'merchant'],
    effects: [flag('fellowship.specialOrder', { enabled: true })],
  }),
  perk({
    id: 'everybodyKnowsSomebody',
    title: 'Everybody Knows Somebody',
    shortLabel: 'NETWORK',
    description: 'Connected shops and towns share eligible stock, referrals, and services.',
    branchId: 'fellowship',
    kind: 'capstone',
    route: 'wide-network',
    tier: 5,
    lane: 1,
    requires: ['specialOrder'],
    cost: 126,
    tags: ['connection', 'merchant', 'reputation'],
    effects: [flag('fellowship.network', { enabled: true })],
  }),
];

const combos: SkillPerkDefinition[] = [
  perk({
    id: 'arcaneVeil',
    title: 'Arcane Veil',
    shortLabel: 'VEIL',
    description: 'Spend 30 mana to negate a lethal hit before life charges.',
    branchId: 'arcane',
    secondaryBranch: 'survival',
    kind: 'combo',
    tier: 7,
    lane: -2,
    requires: ['manaBloom', 'wardedBody'],
    cost: 108,
    migrationAliases: ['starlightVeil'],
    tags: ['mana', 'ward', 'revival'],
    effects: [{ type: 'unlockArcaneVeil' }],
  }),
  perk({
    id: 'bloodMagic',
    title: 'Blood Magic',
    shortLabel: 'BLOOD',
    description: 'Overcast spends safe tail length before hearts.',
    branchId: 'arcane',
    secondaryBranch: 'growth',
    kind: 'combo',
    tier: 7,
    lane: -1,
    requires: ['overcast', 'controlledShedding'],
    cost: 104,
    tags: ['spell', 'length'],
    effects: [flag('combo.bloodMagic', { enabled: true })],
  }),
  perk({
    id: 'spellrush',
    title: 'Spellrush',
    shortLabel: 'RUSH',
    description: 'Casting preserves Surge; changing spell tags can extend it.',
    branchId: 'arcane',
    secondaryBranch: 'momentum',
    kind: 'combo',
    tier: 7,
    lane: 0,
    requires: ['preparedCaster', 'swiftScales'],
    cost: 98,
    tags: ['spell', 'surge'],
    effects: [flag('combo.spellrush', { enabled: true })],
  }),
  perk({
    id: 'ablativeMass',
    title: 'Ablative Mass',
    shortLabel: 'MASS',
    description: 'At 6+ segments, eligible damage removes length before hearts.',
    branchId: 'growth',
    secondaryBranch: 'survival',
    kind: 'combo',
    tier: 7,
    lane: 1,
    requires: ['overgrown', 'hardenedScales'],
    cost: 106,
    tags: ['length', 'ward'],
    effects: [flag('combo.ablativeMass', { minimumLength: 6 })],
  }),
  perk({
    id: 'devour',
    title: 'Devour',
    shortLabel: 'DEVOUR',
    description: 'Prey remains add Stored Nutrition and refresh the hunt window.',
    branchId: 'growth',
    secondaryBranch: 'predator',
    kind: 'combo',
    tier: 7,
    lane: 2,
    requires: ['reserveNutrition', 'huntMomentum'],
    cost: 96,
    tags: ['nutrition', 'prey'],
    effects: [flag('combo.devour', { enabled: true })],
  }),
  perk({
    id: 'relentlessPursuit',
    title: 'Relentless Pursuit',
    shortLabel: 'CHASE',
    description: 'Chasing marked prey builds Momentum; Surge refreshes the mark once.',
    branchId: 'predator',
    secondaryBranch: 'momentum',
    kind: 'combo',
    tier: 7,
    lane: 3,
    requires: ['bloodScent', 'swiftScales'],
    cost: 102,
    tags: ['prey', 'momentum'],
    effects: [flag('combo.relentlessPursuit', { enabled: true })],
  }),
  perk({
    id: 'packHunt',
    title: 'Pack Hunt',
    shortLabel: 'PACK',
    description: 'Companion attacks apply marks and build Hunt Momentum.',
    branchId: 'predator',
    secondaryBranch: 'fellowship',
    kind: 'combo',
    tier: 7,
    lane: 4,
    requires: ['huntMomentum', 'packTactics'],
    cost: 104,
    tags: ['prey', 'companion'],
    effects: [flag('combo.packHunt', { enabled: true })],
  }),
  perk({
    id: 'guardianBond',
    title: 'Guardian Bond',
    shortLabel: 'GUARD',
    description: 'Transfer a ward between you and a bonded companion.',
    branchId: 'survival',
    secondaryBranch: 'fellowship',
    kind: 'combo',
    tier: 7,
    lane: 5,
    requires: ['wardedBody', 'nobodyLeftBehind'],
    cost: 112,
    tags: ['ward', 'companion'],
    effects: [flag('combo.guardianBond', { enabled: true })],
  }),
];

export const SKILL_DEFINITIONS: readonly SkillPerkDefinition[] = [
  ...momentum,
  ...survival,
  ...arcane,
  ...growth,
  ...predator,
  ...fellowship,
  ...combos,
];

export const SKILL_BRANCH_IDS: readonly SkillBranchId[] = [
  'momentum',
  'survival',
  'arcane',
  'growth',
  'predator',
  'fellowship',
];
