import type { Item } from './item.js';

export const ITEMS: readonly Item[] = [
  {
    id: 'weapon-revolver',
    name: 'Pilgrim Revolver',
    description: 'A worn sidearm for formal disagreements. Equip it in your weapon slot to fire.',
    kind: 'equipment',
    slot: 'weapon',
    modifiers: {
      gunEnabled: true,
    },
  },
  {
    id: 'weapon-market-revolver',
    name: 'Market Revolver',
    description: 'A discounted revolver with an honest cylinder and a dishonest weight.',
    kind: 'equipment',
    slot: 'weapon',
    modifiers: {
      gunEnabled: true,
      tickDelayScalar: 1.08,
    },
  },
  {
    id: 'boots-quick',
    name: 'Quick Boots',
    description: 'Lightweight boots that quicken your stride.',
    kind: 'equipment',
    slot: 'boots',
    modifiers: {
      tickDelayScalar: 0.85,
    },
  },
  {
    id: 'boots-heavy',
    name: 'Heavy Boots',
    description: 'Bulky boots that weigh you down.',
    kind: 'equipment',
    slot: 'boots',
    modifiers: {
      tickDelayScalar: 1.2,
    },
  },
  {
    id: 'boots-swim-fins',
    name: 'Swim Fins',
    description: 'Flexible fins that let you cross lakes and ocean water.',
    kind: 'equipment',
    slot: 'boots',
    modifiers: {
      swimmingEnabled: true,
      tickDelayScalar: 1.05,
    },
  },
  {
    id: 'boots-lead-flippers',
    name: 'Lead Flippers',
    description: 'Village-grade flippers. They cross water and make every tile feel farther away.',
    kind: 'equipment',
    slot: 'boots',
    modifiers: {
      swimmingEnabled: true,
      tickDelayScalar: 1.12,
    },
  },
  {
    id: 'helm-seer',
    name: "Seer's Helm",
    description: 'Attuned senses reveal nearby walls.',
    kind: 'equipment',
    slot: 'helm',
    modifiers: {
      wallSenseBonus: 2,
    },
  },
  {
    id: 'ring-seismic',
    name: 'Seismic Ring',
    description: 'Each bite sends ripples through the stone.',
    kind: 'equipment',
    slot: 'ring',
    modifiers: {
      seismicPulseBonus: 1,
    },
  },
  {
    id: 'gloves-mason',
    name: "Mason's Gloves",
    description: 'Your tail lays bricks behind you.',
    kind: 'equipment',
    slot: 'gloves',
    modifiers: {
      masonryEnabled: true,
    },
  },
  {
    id: 'cloak-veil',
    name: 'Veil Cloak',
    description: 'Starlight lingers, granting fleeting invulnerability.',
    kind: 'equipment',
    slot: 'cloak',
    modifiers: {
      invulnerabilityBonus: 1,
    },
  },
  {
    id: 'cloak-frostguard',
    name: 'Frostguard Cloak',
    description: 'A lined travel cloak that keeps frigid depths from biting so quickly.',
    kind: 'equipment',
    slot: 'cloak',
    modifiers: {
      coldResistance: 0.75,
    },
  },
  {
    id: 'cloak-firebreak',
    name: 'Firebreak Cape',
    description: 'A patched cape that keeps ember heat off your scales while slowing your swagger.',
    kind: 'equipment',
    slot: 'cloak',
    modifiers: {
      heatResistance: 0.75,
      tickDelayScalar: 1.04,
    },
  },
  {
    id: 'helm-sunshade',
    name: 'Sunshade Helm',
    description: 'A broad-brimmed helm that cuts the worst of scorching heat.',
    kind: 'equipment',
    slot: 'helm',
    modifiers: {
      heatResistance: 0.75,
    },
  },
  {
    id: 'belt-regenerator',
    name: 'Belt of Renewal',
    description: 'Slow, steady growth over time.',
    kind: 'equipment',
    slot: 'belt',
    modifiers: {
      regenerator: { interval: 24, amount: 1 },
    },
  },
  {
    id: 'amulet-phoenix',
    name: 'Phoenix Charm',
    description: 'A single ember that cheats death once.',
    kind: 'equipment',
    slot: 'amulet',
    modifiers: {
      phoenixCharges: 1,
    },
  },
  {
    id: 'amulet-baby-bottle',
    name: 'Baby Bottle',
    description:
      'A warm little bottle full of second chances. Once per run, it remembers you whole.',
    kind: 'equipment',
    slot: 'amulet',
    modifiers: {
      phoenixCharges: 1,
    },
  },
  {
    id: 'amulet-time-splinter',
    name: 'Time Splinter',
    description: 'A shard of the future that flinches before the present arrives.',
    kind: 'equipment',
    slot: 'amulet',
    modifiers: {
      tickDelayScalar: 0.92,
      invulnerabilityBonus: 20,
    },
  },
  {
    id: 'deep-lying-bouquet',
    name: 'Deep-Lying Bouquet',
    description:
      'Wedding flowers dug from cold earth. They prove you can remember a promise across rooms.',
    kind: 'consumable',
    category: 'quest',
  },
  {
    id: 'stolen-signet',
    name: 'Stolen Signet',
    description: 'A warm ring with a family crest and a very recent absence.',
    kind: 'consumable',
    category: 'quest',
  },
  {
    id: 'forged-town-permit',
    name: 'Forged Town Permit',
    description: 'Official-looking paper that becomes less official the longer anyone reads it.',
    kind: 'consumable',
    category: 'quest',
  },
  {
    id: 'ring-ledger',
    name: 'Ledger Ring',
    description:
      'A brass ring engraved with numbers that change when you are not looking. Every debt wants to become a weapon.',
    kind: 'equipment',
    slot: 'ring',
    modifiers: {
      refundEveryRooms: { interval: 10, score: 20 },
      appleScorePenalty: 1,
    },
  },
  {
    id: 'helm-hazard-halo',
    name: 'Hazard Halo',
    description: 'A dim green halo that warns your skull before the world becomes technical.',
    kind: 'equipment',
    slot: 'helm',
    modifiers: {
      heatResistance: 0.35,
      coldResistance: 0.35,
      hazardMapSense: 1,
      radiationTimerScalar: 0.9,
    },
  },
  {
    id: 'amulet-scavenger',
    name: 'Scavenger Amulet',
    description:
      'A cave-worn charm that listens for useful hollows. Apples send a wider pulse through stone.',
    kind: 'equipment',
    slot: 'amulet',
    modifiers: {
      seismicPulseBonus: 2,
      hazardMapSense: 1,
    },
  },
  {
    id: 'ring-back-alley-dividend',
    name: 'Back-Alley Dividend',
    description:
      'A crooked silver ring that pays out when you keep moving, but its weight slows the rhythm.',
    kind: 'equipment',
    slot: 'ring',
    modifiers: {
      refundEveryRooms: { interval: 8, score: 18 },
      tickDelayScalar: 1.04,
    },
  },
  {
    id: 'helm-cave-echo',
    name: 'Cave Echo Helm',
    description: 'A battered helm that makes nearby walls feel louder and cold tunnels less cruel.',
    kind: 'equipment',
    slot: 'helm',
    modifiers: {
      wallSenseBonus: 2,
      coldResistance: 0.3,
    },
  },
  {
    id: 'belt-smuggler-cache',
    name: 'Smuggler Cache Belt',
    description:
      'A hidden-pocket belt that slowly finds room for more snake, provided you survive long enough.',
    kind: 'equipment',
    slot: 'belt',
    modifiers: {
      regenerator: { interval: 18, amount: 1 },
      tickDelayScalar: 1.03,
    },
  },
  {
    id: 'raw-meat',
    name: 'Raw Meat',
    description: 'A strip of raw meat, still warm. Cooking it would make it safe and nourishing.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked-meat',
    name: 'Cooked Meat',
    description: 'A strip of well-cooked meat. Filling and satisfying.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-meat',
    name: 'Fish Meat',
    description: 'A strip of raw fish meat. Slimy, but edible if you are desperate enough.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked-fish',
    name: 'Cooked Fish',
    description: 'A strip of grilled fish. Flaky and warm.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'hide',
    name: 'Hide',
    description: 'A scrap of cured animal hide. Tough and flexible.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'feather',
    name: 'Feather',
    description: 'A brightly colored feather. Light as air.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'egg',
    name: 'Egg',
    description: 'A small bird egg. Smooth and slightly warm.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'honey',
    name: 'Honey',
    description: 'A glob of wild honey. Sweet and golden.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'healing-potion',
    name: 'Healing Potion',
    description: 'A bright red tonic that restores two hearts.',
    kind: 'consumable',
    category: 'consumable',
  },
  {
    id: 'life-tonic',
    name: 'Life Tonic',
    description: 'A rare tonic that adds one extra-life charge for this run.',
    kind: 'consumable',
    category: 'consumable',
  },
  {
    id: 'beer',
    name: 'Beer',
    description: 'A tavern drink. Briefly makes your path drift side to side.',
    kind: 'consumable',
    category: 'consumable',
  },
  {
    id: 'wine',
    name: 'Wine',
    description: 'A stronger tavern drink. Briefly makes your path drift side to side.',
    kind: 'consumable',
    category: 'consumable',
  },
  {
    id: 'rope',
    name: 'Rope',
    description: 'A coil of braided rope. Useful for lassoing animals.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'A sturdy leather lead strap. The key to taming wild creatures.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'food-snake-burger',
    name: 'Snake Burger',
    description:
      'A juicy burger made with premium snake meat. +5 length, 1 minute invulnerability.',
    kind: 'consumable',
  },
  {
    id: 'food-snake-fries',
    name: 'Snake Fries',
    description:
      'Crispy golden fries seasoned with serpent herbs. +5 length, 1 minute invulnerability.',
    kind: 'consumable',
  },
  {
    id: 'food-snake-nuggets',
    name: 'Snake Nuggets',
    description: 'Crispy little nuggets of snake. +2 length, 30 seconds invulnerability.',
    kind: 'consumable',
  },
  {
    id: 'ofuda',
    name: 'Ofuda',
    description:
      'A paper talisman that negates one death. Stackable. Like a phoenix charge but single-use.',
    kind: 'consumable',
    category: 'consumable',
  },
  {
    id: 'weapon-jade-katana',
    name: 'Jade Katana',
    description: 'A blade that grants a one-time wall-smite ability. Cut through one wall segment.',
    kind: 'equipment',
    slot: 'weapon',
    modifiers: {
      wallSmiteEnabled: true,
    },
  },
  {
    id: 'boots-geta',
    name: 'Geta',
    description:
      'Traditional wooden sandals. Cosmetic, but grants +1 movement speed on bamboo tiles.',
    kind: 'equipment',
    slot: 'boots',
    modifiers: {
      tickDelayScalar: 0.97,
    },
  },
  {
    id: 'cloak-furoshiki',
    name: 'Furoshiki',
    description:
      'A wrapping cloth that temporarily stores one collected apple for later consumption.',
    kind: 'equipment',
    slot: 'cloak',
  },
  {
    id: 'senbei',
    name: 'Senbei',
    description: 'A cheap rice cracker from the ramen stand. Fills some hunger.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'ramen',
    name: 'Ramen',
    description: 'A steaming bowl of ramen. Fills hunger completely and gives a small speed boost.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'animal-bait',
    name: 'Animal Bait',
    description: 'A dense chunk of bait. Predators notice it before they notice you.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'oni-charm',
    name: 'Oni Charm',
    description: 'A one-use charm that calls rough help against nearby enemies.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'kitsune-charm',
    name: 'Kitsune Charm',
    description: 'A one-use charm that throws foxfire illusions across the room.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'samurai-token',
    name: 'Samurai Token',
    description: 'A one-use token promising one clean strike in a messy room.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'jizo-stone',
    name: 'Jizo Stone',
    description: 'A small guardian stone. It feels heavier when danger is near.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'raiju-bottle',
    name: 'Raiju Bottle',
    description: 'A storm trapped in glass. Open only when lightning would help.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'kappa-bowl',
    name: 'Kappa Bowl',
    description: 'A water charm that is happiest near shorelines and bad decisions.',
    kind: 'consumable',
    category: 'charm',
  },
  {
    id: 'katana-blueprint',
    name: 'Katana Blueprint',
    description: 'A recipe for a jade katana. Track it when you are ready to craft.',
    kind: 'consumable',
    category: 'recipe',
  },
  // Minecraft items
  {
    id: 'cobblestone',
    name: 'Cobblestone',
    description: 'A common building block for Minecraft mode.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'torch_item',
    name: 'Torch',
    description: 'Emits light. Useful for dark places.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'raw_beef',
    name: 'Raw Beef',
    description: 'A strip of raw cow meat. Edible, but risky.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'cooked_beef',
    name: 'Cooked Beef',
    description: 'A strip of grilled beef. Nourishing.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'bread',
    name: 'Bread',
    description: 'A loaf of bread. Filling and safe.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'stick',
    name: 'Stick',
    description: 'A small wooden rod. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'planks_item',
    name: 'Planks',
    description: 'Processed wood. Used in crafting.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    description: 'Refined iron. Essential for tools.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'coal',
    name: 'Coal',
    description: 'A black mineral. Used for fuel and torches.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    description: 'A precious gemstone. The hardest material.',
    kind: 'consumable',
    category: 'material',
  },
  {
    id: 'wooden_pickaxe',
    name: 'Wooden Pickaxe',
    description: 'A basic pickaxe for mining stone and ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
  },
  {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'Sturdier than wood. Mines iron ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
  },
  {
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    description: 'Solid iron. Mines diamond ore.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
  },
  {
    id: 'diamond_pickaxe',
    name: 'Diamond Pickaxe',
    description: 'Shines bright and mines anything.',
    kind: 'equipment',
    slot: 'gloves',
    category: 'material',
  },
  {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    description: 'A basic melee weapon for Minecraft combat.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
  },
  {
    id: 'stone_sword',
    name: 'Stone Sword',
    description: 'A sturdy blade for Minecraft combat.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A reliable iron blade.',
    kind: 'equipment',
    slot: 'weapon',
    category: 'material',
  },
  {
    id: 'rotten_flesh',
    name: 'Rotten Flesh',
    description: 'Decaying meat from undead. Edible, but not appetizing.',
    kind: 'consumable',
    category: 'food',
  },
  // ===== FISHING ITEMS =====
  {
    id: 'fishing-rod',
    name: 'Fishing Rod',
    description: 'A collapsible fishing pole. Equip it in your gloves slot to start fishing.',
    kind: 'equipment',
    slot: 'gloves',
    modifiers: {
      fishingEnabled: true,
    },
  },
  // Verdigris Basin
  {
    id: 'fish-minnow',
    name: 'Minnow',
    description: 'A tiny silver fish. Barely fights, barely matters.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-perch',
    name: 'Perch',
    description: 'A sturdy little fish with spikes and a grudge.',
    kind: 'consumable',
    category: 'food',
  },
  // Ember Waste
  {
    id: 'fish-desert-catfish',
    name: 'Desert Catfish',
    description: 'Barely alive, still thrashing. The desert\'s idea of a meal.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-fire-eel',
    name: 'Fire Eel',
    description: 'Warm to the touch. Some say it still sparkles.',
    kind: 'consumable',
    category: 'food',
  },
  // Moonlit Parish
  {
    id: 'fish-ice-perch',
    name: 'Ice Perch',
    description: 'Cold as regret. Crunches when you bite.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-frost-trout',
    name: 'Frost Trout',
    description: 'Shimmers with a cold light. Beautiful and unforgiving.',
    kind: 'consumable',
    category: 'food',
  },
  // Sable Depths
  {
    id: 'fish-deep-minnow',
    name: 'Deep Minnow',
    description: 'Smaller than it should be. Blind, but angry.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-abyss-catfish',
    name: 'Abyss Catfish',
    description: 'Whiskers like cable. Mouth like a vault.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-shadow-eel',
    name: 'Shadow Eel',
    description: 'You cannot see it, but you feel it pulling.',
    kind: 'consumable',
    category: 'food',
  },
  // Gloam Garden
  {
    id: 'fish-garden-carp',
    name: 'Garden Carp',
    description: 'Fat and patient. It knew you were coming.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-moon-perch',
    name: 'Moon Perch',
    description: 'Reflects moonlight even when the sky is gone.',
    kind: 'consumable',
    category: 'food',
  },
  // Elderwood Maze
  {
    id: 'fish-swamp-catfish',
    name: 'Swamp Catfish',
    description: 'Mud in its gills, mud in its eyes, mud in its soul.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-forest-eel',
    name: 'Forest Eel',
    description: 'Root-tangled and venomous. Do not let it touch you.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-kelp-serpent',
    name: 'Kelp Serpent',
    description: 'Long as a corridor. Hungrier than a promise.',
    kind: 'consumable',
    category: 'food',
  },
  // Sunken Ocean
  {
    id: 'fish-reef-fish',
    name: 'Reef Fish',
    description: 'Colorful, confused, and very willing to bite.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-ocean-bass',
    name: 'Ocean Bass',
    description: 'Heavy as a brick. Fast as a grudge.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-blue-marlin',
    name: 'Blue Marlin',
    description: 'A blade with fins. You respect it. It may respect you back.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-kraken-baitfish',
    name: 'Kraken Baitfish',
    description: 'Not the kraken itself. Just what the kraken wants for breakfast.',
    kind: 'consumable',
    category: 'food',
  },
  // Jade Peak Province
  {
    id: 'fish-koi',
    name: 'Koi',
    description: 'Painted by monks. Swum by pilgrims. Caught by you.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-golden-koi',
    name: 'Golden Koi',
    description: 'The color of a wish you did not make soon enough.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-dragon-carp',
    name: 'Dragon Carp',
    description: 'Old enough to remember the mountain as it was.',
    kind: 'consumable',
    category: 'food',
  },
  // Liberty Badlands
  {
    id: 'fish-prairie-minnow',
    name: 'Prairie Minnow',
    description: 'Tiny, tough, and absolutely unimpressed by you.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-badlands-bass',
    name: 'Badlands Bass',
    description: 'Built for dust and drought. Still fights.',
    kind: 'consumable',
    category: 'food',
  },
  {
    id: 'fish-jackalope-lure',
    name: 'Jackalope Lure',
    description: 'Part fish, part myth, all trouble.',
    kind: 'consumable',
    category: 'food',
  },
];

const ITEM_MAP = new Map<string, Item>(ITEMS.map((item) => [item.id, item]));
const CHEST_LOOT_ITEM_IDS = [
  'healing-potion',
  'senbei',
  'ramen',
  'animal-bait',
  'raw-meat',
  'cooked-meat',
  'fish-meat',
  'cooked-fish',
  'egg',
  'honey',
  'rope',
  'lead',
  'hide',
  'feather',
  'weapon-revolver',
  'boots-quick',
  'boots-heavy',
  'boots-swim-fins',
  'helm-seer',
  'ring-seismic',
  'gloves-mason',
  'cloak-veil',
  'belt-regenerator',
  'boots-geta',
  'cloak-furoshiki',
  'oni-charm',
  'kitsune-charm',
  'samurai-token',
  'jizo-stone',
  'raiju-bottle',
  'kappa-bowl',
] as const;
const CHEST_LOOT_EXCLUDED_IDS = new Set([
  'weapon-market-revolver',
  'boots-lead-flippers',
  'cloak-firebreak',
  'cloak-frostguard',
  'amulet-baby-bottle',
  'amulet-time-splinter',
  'deep-lying-bouquet',
  'ring-ledger',
  'helm-hazard-halo',
]);

export const CHEST_LOOT_ITEMS: readonly Item[] = CHEST_LOOT_ITEM_IDS.map((id) =>
  ITEM_MAP.get(id),
).filter((item): item is Item => Boolean(item) && !CHEST_LOOT_EXCLUDED_IDS.has(item.id));

export function getItem(id: string): Item | undefined {
  return ITEM_MAP.get(id);
}
