/**
 * Artifact Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const ARTIFACT_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'cobalt-greaves-1',
    name: 'Cobalt Greaves 1',
    slot: 'artifact',
    rarity: 'common',
    element: 'arc',
    power: 18,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-plate-1',
    name: 'Riven Plate 1',
    slot: 'artifact',
    rarity: 'rare',
    element: 'prismatic',
    power: 32,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-wraps-2',
    name: 'Iron Wraps 2',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'arc',
    power: 48,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-cowl-2',
    name: 'Warden Cowl 2',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 65,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-sigil-3',
    name: 'Ash Sigil 3',
    slot: 'artifact',
    rarity: 'mythic',
    element: 'arc',
    power: 86,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-greaves-3',
    name: 'Broken Greaves 3',
    slot: 'artifact',
    rarity: 'common',
    element: 'prismatic',
    power: 63,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-plate-4',
    name: 'Night Plate 4',
    slot: 'artifact',
    rarity: 'rare',
    element: 'arc',
    power: 77,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-wraps-4',
    name: 'Silent Wraps 4',
    slot: 'artifact',
    rarity: 'rare',
    element: 'prismatic',
    power: 16,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cowl-5',
    name: 'Astral Cowl 5',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'arc',
    power: 32,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-sigil-5',
    name: 'Scarlet Sigil 5',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 49,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-greaves-5',
    name: 'Quantum Greaves 5',
    slot: 'artifact',
    rarity: 'mythic',
    element: 'arc',
    power: 70,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-plate-6',
    name: 'Velvet Plate 6',
    slot: 'artifact',
    rarity: 'common',
    element: 'prismatic',
    power: 47,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-wraps-6',
    name: 'Echo Wraps 6',
    slot: 'artifact',
    rarity: 'rare',
    element: 'arc',
    power: 61,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-cowl-7',
    name: 'Glass Cowl 7',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'prismatic',
    power: 77,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-sigil-7',
    name: 'Radiant Sigil 7',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'arc',
    power: 94,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-greaves-8',
    name: 'Storm Greaves 8',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 33,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-plate-8',
    name: 'Prime Plate 8',
    slot: 'artifact',
    rarity: 'common',
    element: 'arc',
    power: 22,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-wraps-9',
    name: 'Dawn Wraps 9',
    slot: 'artifact',
    rarity: 'rare',
    element: 'prismatic',
    power: 36,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-cowl-9',
    name: 'Golden Cowl 9',
    slot: 'artifact',
    rarity: 'rare',
    element: 'arc',
    power: 45,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-sigil-9',
    name: 'Seraph Sigil 9',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'prismatic',
    power: 61,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-greaves-10',
    name: 'Cobalt Greaves 10',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'arc',
    power: 78,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-plate-10',
    name: 'Riven Plate 10',
    slot: 'artifact',
    rarity: 'mythic',
    element: 'prismatic',
    power: 99,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-wraps-11',
    name: 'Iron Wraps 11',
    slot: 'artifact',
    rarity: 'common',
    element: 'arc',
    power: 76,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-cowl-11',
    name: 'Warden Cowl 11',
    slot: 'artifact',
    rarity: 'rare',
    element: 'prismatic',
    power: 20,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-sigil-12',
    name: 'Ash Sigil 12',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'arc',
    power: 36,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-greaves-12',
    name: 'Broken Greaves 12',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 53,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-plate-13',
    name: 'Night Plate 13',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'arc',
    power: 62,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-wraps-13',
    name: 'Silent Wraps 13',
    slot: 'artifact',
    rarity: 'common',
    element: 'prismatic',
    power: 51,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cowl-14',
    name: 'Astral Cowl 14',
    slot: 'artifact',
    rarity: 'common',
    element: 'arc',
    power: 60,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-sigil-14',
    name: 'Scarlet Sigil 14',
    slot: 'artifact',
    rarity: 'rare',
    element: 'prismatic',
    power: 74,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-greaves-14',
    name: 'Quantum Greaves 14',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'arc',
    power: 90,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-plate-15',
    name: 'Velvet Plate 15',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 37,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-wraps-15',
    name: 'Echo Wraps 15',
    slot: 'artifact',
    rarity: 'mythic',
    element: 'arc',
    power: 58,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-cowl-16',
    name: 'Glass Cowl 16',
    slot: 'artifact',
    rarity: 'common',
    element: 'prismatic',
    power: 35,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-sigil-16',
    name: 'Radiant Sigil 16',
    slot: 'artifact',
    rarity: 'rare',
    element: 'arc',
    power: 49,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-greaves-17',
    name: 'Storm Greaves 17',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'prismatic',
    power: 65,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-plate-17',
    name: 'Prime Plate 17',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'arc',
    power: 74,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-wraps-18',
    name: 'Dawn Wraps 18',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'prismatic',
    power: 91,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-cowl-18',
    name: 'Golden Cowl 18',
    slot: 'artifact',
    rarity: 'common',
    element: 'arc',
    power: 10,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-sigil-18',
    name: 'Seraph Sigil 18',
    slot: 'artifact',
    rarity: 'common',
    element: 'prismatic',
    power: 19,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-greaves-19',
    name: 'Cobalt Greaves 19',
    slot: 'artifact',
    rarity: 'rare',
    element: 'arc',
    power: 33,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-plate-19',
    name: 'Riven Plate 19',
    slot: 'artifact',
    rarity: 'legendary',
    element: 'prismatic',
    power: 49,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-wraps-20',
    name: 'Iron Wraps 20',
    slot: 'artifact',
    rarity: 'exotic',
    element: 'arc',
    power: 66,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
