/**
 * Chest Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const CHEST_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'glass-cowl-1',
    name: 'Glass Cowl 1',
    slot: 'chest',
    rarity: 'common',
    element: 'prismatic',
    power: 15,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-sigil-1',
    name: 'Radiant Sigil 1',
    slot: 'chest',
    rarity: 'rare',
    element: 'arc',
    power: 29,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-greaves-2',
    name: 'Storm Greaves 2',
    slot: 'chest',
    rarity: 'legendary',
    element: 'prismatic',
    power: 45,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-plate-2',
    name: 'Prime Plate 2',
    slot: 'chest',
    rarity: 'legendary',
    element: 'arc',
    power: 54,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-wraps-3',
    name: 'Dawn Wraps 3',
    slot: 'chest',
    rarity: 'exotic',
    element: 'prismatic',
    power: 71,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-cowl-3',
    name: 'Golden Cowl 3',
    slot: 'chest',
    rarity: 'common',
    element: 'arc',
    power: 60,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-sigil-3',
    name: 'Seraph Sigil 3',
    slot: 'chest',
    rarity: 'common',
    element: 'prismatic',
    power: 69,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-greaves-4',
    name: 'Cobalt Greaves 4',
    slot: 'chest',
    rarity: 'rare',
    element: 'arc',
    power: 83,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-plate-4',
    name: 'Riven Plate 4',
    slot: 'chest',
    rarity: 'legendary',
    element: 'prismatic',
    power: 29,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-wraps-5',
    name: 'Iron Wraps 5',
    slot: 'chest',
    rarity: 'exotic',
    element: 'arc',
    power: 46,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-cowl-5',
    name: 'Warden Cowl 5',
    slot: 'chest',
    rarity: 'mythic',
    element: 'prismatic',
    power: 67,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-sigil-6',
    name: 'Ash Sigil 6',
    slot: 'chest',
    rarity: 'common',
    element: 'arc',
    power: 44,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-greaves-6',
    name: 'Broken Greaves 6',
    slot: 'chest',
    rarity: 'rare',
    element: 'prismatic',
    power: 58,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-plate-7',
    name: 'Night Plate 7',
    slot: 'chest',
    rarity: 'legendary',
    element: 'arc',
    power: 74,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-wraps-7',
    name: 'Silent Wraps 7',
    slot: 'chest',
    rarity: 'legendary',
    element: 'prismatic',
    power: 83,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cowl-8',
    name: 'Astral Cowl 8',
    slot: 'chest',
    rarity: 'exotic',
    element: 'arc',
    power: 30,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-sigil-8',
    name: 'Scarlet Sigil 8',
    slot: 'chest',
    rarity: 'mythic',
    element: 'prismatic',
    power: 51,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-greaves-8',
    name: 'Quantum Greaves 8',
    slot: 'chest',
    rarity: 'common',
    element: 'arc',
    power: 28,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-plate-9',
    name: 'Velvet Plate 9',
    slot: 'chest',
    rarity: 'rare',
    element: 'prismatic',
    power: 42,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-wraps-9',
    name: 'Echo Wraps 9',
    slot: 'chest',
    rarity: 'legendary',
    element: 'arc',
    power: 58,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-cowl-10',
    name: 'Glass Cowl 10',
    slot: 'chest',
    rarity: 'exotic',
    element: 'prismatic',
    power: 75,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-sigil-10',
    name: 'Radiant Sigil 10',
    slot: 'chest',
    rarity: 'mythic',
    element: 'arc',
    power: 96,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-greaves-11',
    name: 'Storm Greaves 11',
    slot: 'chest',
    rarity: 'common',
    element: 'prismatic',
    power: 73,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-plate-11',
    name: 'Prime Plate 11',
    slot: 'chest',
    rarity: 'rare',
    element: 'arc',
    power: 17,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-wraps-12',
    name: 'Dawn Wraps 12',
    slot: 'chest',
    rarity: 'rare',
    element: 'prismatic',
    power: 26,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-cowl-12',
    name: 'Golden Cowl 12',
    slot: 'chest',
    rarity: 'legendary',
    element: 'arc',
    power: 42,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-sigil-12',
    name: 'Seraph Sigil 12',
    slot: 'chest',
    rarity: 'exotic',
    element: 'prismatic',
    power: 59,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-greaves-13',
    name: 'Cobalt Greaves 13',
    slot: 'chest',
    rarity: 'mythic',
    element: 'arc',
    power: 80,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-plate-13',
    name: 'Riven Plate 13',
    slot: 'chest',
    rarity: 'common',
    element: 'prismatic',
    power: 57,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-wraps-14',
    name: 'Iron Wraps 14',
    slot: 'chest',
    rarity: 'rare',
    element: 'arc',
    power: 71,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-cowl-14',
    name: 'Warden Cowl 14',
    slot: 'chest',
    rarity: 'legendary',
    element: 'prismatic',
    power: 87,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-sigil-15',
    name: 'Ash Sigil 15',
    slot: 'chest',
    rarity: 'exotic',
    element: 'arc',
    power: 34,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-greaves-15',
    name: 'Broken Greaves 15',
    slot: 'chest',
    rarity: 'exotic',
    element: 'prismatic',
    power: 43,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-plate-16',
    name: 'Night Plate 16',
    slot: 'chest',
    rarity: 'common',
    element: 'arc',
    power: 32,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-wraps-16',
    name: 'Silent Wraps 16',
    slot: 'chest',
    rarity: 'rare',
    element: 'prismatic',
    power: 46,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cowl-17',
    name: 'Astral Cowl 17',
    slot: 'chest',
    rarity: 'rare',
    element: 'arc',
    power: 55,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-sigil-17',
    name: 'Scarlet Sigil 17',
    slot: 'chest',
    rarity: 'legendary',
    element: 'prismatic',
    power: 71,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-greaves-17',
    name: 'Quantum Greaves 17',
    slot: 'chest',
    rarity: 'exotic',
    element: 'arc',
    power: 88,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-plate-18',
    name: 'Velvet Plate 18',
    slot: 'chest',
    rarity: 'mythic',
    element: 'prismatic',
    power: 109,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-wraps-18',
    name: 'Echo Wraps 18',
    slot: 'chest',
    rarity: 'common',
    element: 'arc',
    power: 16,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-cowl-19',
    name: 'Glass Cowl 19',
    slot: 'chest',
    rarity: 'rare',
    element: 'prismatic',
    power: 30,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-sigil-19',
    name: 'Radiant Sigil 19',
    slot: 'chest',
    rarity: 'legendary',
    element: 'arc',
    power: 46,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-greaves-20',
    name: 'Storm Greaves 20',
    slot: 'chest',
    rarity: 'exotic',
    element: 'prismatic',
    power: 63,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
