/**
 * Class Item Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const CLASS_ITEM_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'velvet-vest-1',
    name: 'Velvet Vest 1',
    slot: 'classItem',
    rarity: 'common',
    element: 'void',
    power: 17,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-grips-1',
    name: 'Echo Grips 1',
    slot: 'classItem',
    rarity: 'rare',
    element: 'strand',
    power: 31,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-halo-2',
    name: 'Glass Halo 2',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'void',
    power: 47,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-bond-2',
    name: 'Radiant Bond 2',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'strand',
    power: 64,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-spurs-3',
    name: 'Storm Spurs 3',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'void',
    power: 73,
    intrinsic: 'Precision omen channel',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-vest-3',
    name: 'Prime Vest 3',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 62,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-grips-4',
    name: 'Dawn Grips 4',
    slot: 'classItem',
    rarity: 'rare',
    element: 'void',
    power: 76,
    intrinsic: 'Precision omen channel',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-halo-4',
    name: 'Golden Halo 4',
    slot: 'classItem',
    rarity: 'rare',
    element: 'strand',
    power: 15,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-bond-4',
    name: 'Seraph Bond 4',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'void',
    power: 31,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-spurs-5',
    name: 'Cobalt Spurs 5',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'strand',
    power: 48,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-vest-5',
    name: 'Riven Vest 5',
    slot: 'classItem',
    rarity: 'mythic',
    element: 'void',
    power: 69,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-grips-6',
    name: 'Iron Grips 6',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 46,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-halo-6',
    name: 'Warden Halo 6',
    slot: 'classItem',
    rarity: 'rare',
    element: 'void',
    power: 60,
    intrinsic: 'Precision omen channel',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-bond-7',
    name: 'Ash Bond 7',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'strand',
    power: 76,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-spurs-7',
    name: 'Broken Spurs 7',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'void',
    power: 93,
    intrinsic: 'Precision omen channel',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-vest-8',
    name: 'Night Vest 8',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'strand',
    power: 32,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-grips-8',
    name: 'Silent Grips 8',
    slot: 'classItem',
    rarity: 'common',
    element: 'void',
    power: 21,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-halo-9',
    name: 'Astral Halo 9',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 30,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-bond-9',
    name: 'Scarlet Bond 9',
    slot: 'classItem',
    rarity: 'rare',
    element: 'void',
    power: 44,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-spurs-9',
    name: 'Quantum Spurs 9',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'strand',
    power: 60,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-vest-10',
    name: 'Velvet Vest 10',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'void',
    power: 77,
    intrinsic: 'Precision omen channel',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-grips-10',
    name: 'Echo Grips 10',
    slot: 'classItem',
    rarity: 'mythic',
    element: 'strand',
    power: 98,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-halo-11',
    name: 'Glass Halo 11',
    slot: 'classItem',
    rarity: 'common',
    element: 'void',
    power: 75,
    intrinsic: 'Precision omen channel',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-bond-11',
    name: 'Radiant Bond 11',
    slot: 'classItem',
    rarity: 'rare',
    element: 'strand',
    power: 19,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-spurs-12',
    name: 'Storm Spurs 12',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'void',
    power: 35,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-vest-12',
    name: 'Prime Vest 12',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'strand',
    power: 44,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-grips-13',
    name: 'Dawn Grips 13',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'void',
    power: 61,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-halo-13',
    name: 'Golden Halo 13',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 50,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-bond-13',
    name: 'Seraph Bond 13',
    slot: 'classItem',
    rarity: 'common',
    element: 'void',
    power: 59,
    intrinsic: 'Precision omen channel',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-spurs-14',
    name: 'Cobalt Spurs 14',
    slot: 'classItem',
    rarity: 'rare',
    element: 'strand',
    power: 73,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-vest-14',
    name: 'Riven Vest 14',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'void',
    power: 89,
    intrinsic: 'Precision omen channel',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-grips-15',
    name: 'Iron Grips 15',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'strand',
    power: 36,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-halo-15',
    name: 'Warden Halo 15',
    slot: 'classItem',
    rarity: 'mythic',
    element: 'void',
    power: 57,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-bond-16',
    name: 'Ash Bond 16',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 34,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-spurs-16',
    name: 'Broken Spurs 16',
    slot: 'classItem',
    rarity: 'rare',
    element: 'void',
    power: 48,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-vest-17',
    name: 'Night Vest 17',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'strand',
    power: 64,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-grips-17',
    name: 'Silent Grips 17',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'void',
    power: 73,
    intrinsic: 'Precision omen channel',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-halo-18',
    name: 'Astral Halo 18',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'strand',
    power: 90,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-bond-18',
    name: 'Scarlet Bond 18',
    slot: 'classItem',
    rarity: 'mythic',
    element: 'void',
    power: 111,
    intrinsic: 'Precision omen channel',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-spurs-18',
    name: 'Quantum Spurs 18',
    slot: 'classItem',
    rarity: 'common',
    element: 'strand',
    power: 18,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-vest-19',
    name: 'Velvet Vest 19',
    slot: 'classItem',
    rarity: 'rare',
    element: 'void',
    power: 32,
    intrinsic: 'Precision omen channel',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-grips-19',
    name: 'Echo Grips 19',
    slot: 'classItem',
    rarity: 'legendary',
    element: 'strand',
    power: 48,
    intrinsic: 'Wave-forged hunger engine',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-halo-20',
    name: 'Glass Halo 20',
    slot: 'classItem',
    rarity: 'exotic',
    element: 'void',
    power: 65,
    intrinsic: 'Precision omen channel',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
