/**
 * Heavy Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const HEAVY_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'night-mandate-1',
    name: 'Night Mandate 1',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 12,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-needle-1',
    name: 'Silent Needle 1',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 26,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cipher-2',
    name: 'Astral Cipher 2',
    slot: 'heavy',
    rarity: 'rare',
    element: 'arc',
    power: 35,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-2',
    name: 'Scarlet Compass 2',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'prismatic',
    power: 51,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-accord-2',
    name: 'Quantum Accord 2',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'arc',
    power: 68,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-engine-3',
    name: 'Velvet Engine 3',
    slot: 'heavy',
    rarity: 'mythic',
    element: 'prismatic',
    power: 89,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-myth-3',
    name: 'Echo Myth 3',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 66,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-vow-4',
    name: 'Glass Vow 4',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 80,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-harbor-4',
    name: 'Radiant Harbor 4',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 26,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-refrain-5',
    name: 'Storm Refrain 5',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'prismatic',
    power: 43,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-crown-5',
    name: 'Prime Crown 5',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'arc',
    power: 52,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-lance-6',
    name: 'Dawn Lance 6',
    slot: 'heavy',
    rarity: 'common',
    element: 'prismatic',
    power: 41,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-edict-6',
    name: 'Golden Edict 6',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 50,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-key-6',
    name: 'Seraph Key 6',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 64,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-oracle-7',
    name: 'Cobalt Oracle 7',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 80,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-spiral-7',
    name: 'Riven Spiral 7',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'prismatic',
    power: 97,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-parable-8',
    name: 'Iron Parable 8',
    slot: 'heavy',
    rarity: 'mythic',
    element: 'arc',
    power: 48,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-vector-8',
    name: 'Warden Vector 8',
    slot: 'heavy',
    rarity: 'common',
    element: 'prismatic',
    power: 25,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-signal-9',
    name: 'Ash Signal 9',
    slot: 'heavy',
    rarity: 'rare',
    element: 'arc',
    power: 39,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-lantern-9',
    name: 'Broken Lantern 9',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'prismatic',
    power: 55,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-mandate-10',
    name: 'Night Mandate 10',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 64,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-needle-10',
    name: 'Silent Needle 10',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'prismatic',
    power: 81,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cipher-11',
    name: 'Astral Cipher 11',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 70,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-11',
    name: 'Scarlet Compass 11',
    slot: 'heavy',
    rarity: 'common',
    element: 'prismatic',
    power: 79,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-accord-11',
    name: 'Quantum Accord 11',
    slot: 'heavy',
    rarity: 'rare',
    element: 'arc',
    power: 23,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-engine-12',
    name: 'Velvet Engine 12',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'prismatic',
    power: 39,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-myth-12',
    name: 'Echo Myth 12',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'arc',
    power: 56,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-vow-13',
    name: 'Glass Vow 13',
    slot: 'heavy',
    rarity: 'mythic',
    element: 'prismatic',
    power: 77,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-harbor-13',
    name: 'Radiant Harbor 13',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 54,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-refrain-14',
    name: 'Storm Refrain 14',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 68,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-crown-14',
    name: 'Prime Crown 14',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 84,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-lance-15',
    name: 'Dawn Lance 15',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'prismatic',
    power: 23,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-edict-15',
    name: 'Golden Edict 15',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'arc',
    power: 40,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-key-15',
    name: 'Seraph Key 15',
    slot: 'heavy',
    rarity: 'mythic',
    element: 'prismatic',
    power: 61,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-oracle-16',
    name: 'Cobalt Oracle 16',
    slot: 'heavy',
    rarity: 'common',
    element: 'arc',
    power: 38,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-spiral-16',
    name: 'Riven Spiral 16',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 52,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-parable-17',
    name: 'Iron Parable 17',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 68,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-vector-17',
    name: 'Warden Vector 17',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'prismatic',
    power: 85,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-signal-18',
    name: 'Ash Signal 18',
    slot: 'heavy',
    rarity: 'mythic',
    element: 'arc',
    power: 106,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-lantern-18',
    name: 'Broken Lantern 18',
    slot: 'heavy',
    rarity: 'common',
    element: 'prismatic',
    power: 13,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-mandate-19',
    name: 'Night Mandate 19',
    slot: 'heavy',
    rarity: 'rare',
    element: 'arc',
    power: 27,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-needle-19',
    name: 'Silent Needle 19',
    slot: 'heavy',
    rarity: 'rare',
    element: 'prismatic',
    power: 36,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cipher-20',
    name: 'Astral Cipher 20',
    slot: 'heavy',
    rarity: 'legendary',
    element: 'arc',
    power: 52,
    intrinsic: 'Rapid pilgrim matrix',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-20',
    name: 'Scarlet Compass 20',
    slot: 'heavy',
    rarity: 'exotic',
    element: 'prismatic',
    power: 69,
    intrinsic: 'Balanced serpent receiver',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
