/**
 * Helmet Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const HELMET_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'storm-treads-1',
    name: 'Storm Treads 1',
    slot: 'helmet',
    rarity: 'common',
    element: 'stasis',
    power: 13,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-harness-1',
    name: 'Prime Harness 1',
    slot: 'helmet',
    rarity: 'rare',
    element: 'solar',
    power: 27,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-sleeves-2',
    name: 'Dawn Sleeves 2',
    slot: 'helmet',
    rarity: 'rare',
    element: 'stasis',
    power: 36,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-mask-2',
    name: 'Golden Mask 2',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'solar',
    power: 52,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-mark-2',
    name: 'Seraph Mark 2',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'stasis',
    power: 69,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-treads-3',
    name: 'Cobalt Treads 3',
    slot: 'helmet',
    rarity: 'mythic',
    element: 'solar',
    power: 90,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-harness-3',
    name: 'Riven Harness 3',
    slot: 'helmet',
    rarity: 'common',
    element: 'stasis',
    power: 67,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-sleeves-4',
    name: 'Iron Sleeves 4',
    slot: 'helmet',
    rarity: 'rare',
    element: 'solar',
    power: 81,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-mask-4',
    name: 'Warden Mask 4',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'stasis',
    power: 27,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-mark-5',
    name: 'Ash Mark 5',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'solar',
    power: 44,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-treads-5',
    name: 'Broken Treads 5',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'stasis',
    power: 53,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-harness-6',
    name: 'Night Harness 6',
    slot: 'helmet',
    rarity: 'common',
    element: 'solar',
    power: 42,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-sleeves-6',
    name: 'Silent Sleeves 6',
    slot: 'helmet',
    rarity: 'rare',
    element: 'stasis',
    power: 56,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-mask-7',
    name: 'Astral Mask 7',
    slot: 'helmet',
    rarity: 'rare',
    element: 'solar',
    power: 65,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-mark-7',
    name: 'Scarlet Mark 7',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'stasis',
    power: 81,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-treads-7',
    name: 'Quantum Treads 7',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'solar',
    power: 98,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-harness-8',
    name: 'Velvet Harness 8',
    slot: 'helmet',
    rarity: 'mythic',
    element: 'stasis',
    power: 49,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-sleeves-8',
    name: 'Echo Sleeves 8',
    slot: 'helmet',
    rarity: 'common',
    element: 'solar',
    power: 26,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-mask-9',
    name: 'Glass Mask 9',
    slot: 'helmet',
    rarity: 'rare',
    element: 'stasis',
    power: 40,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-mark-9',
    name: 'Radiant Mark 9',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'solar',
    power: 56,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-treads-10',
    name: 'Storm Treads 10',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'stasis',
    power: 73,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-harness-10',
    name: 'Prime Harness 10',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'solar',
    power: 82,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-sleeves-11',
    name: 'Dawn Sleeves 11',
    slot: 'helmet',
    rarity: 'common',
    element: 'stasis',
    power: 71,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-mask-11',
    name: 'Golden Mask 11',
    slot: 'helmet',
    rarity: 'common',
    element: 'solar',
    power: 10,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-mark-11',
    name: 'Seraph Mark 11',
    slot: 'helmet',
    rarity: 'rare',
    element: 'stasis',
    power: 24,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-treads-12',
    name: 'Cobalt Treads 12',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'solar',
    power: 40,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-harness-12',
    name: 'Riven Harness 12',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'stasis',
    power: 57,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-sleeves-13',
    name: 'Iron Sleeves 13',
    slot: 'helmet',
    rarity: 'mythic',
    element: 'solar',
    power: 78,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-mask-13',
    name: 'Warden Mask 13',
    slot: 'helmet',
    rarity: 'common',
    element: 'stasis',
    power: 55,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-mark-14',
    name: 'Ash Mark 14',
    slot: 'helmet',
    rarity: 'rare',
    element: 'solar',
    power: 69,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-treads-14',
    name: 'Broken Treads 14',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'stasis',
    power: 85,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-harness-15',
    name: 'Night Harness 15',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'solar',
    power: 24,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-sleeves-15',
    name: 'Silent Sleeves 15',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'stasis',
    power: 41,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-mask-16',
    name: 'Astral Mask 16',
    slot: 'helmet',
    rarity: 'common',
    element: 'solar',
    power: 30,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-mark-16',
    name: 'Scarlet Mark 16',
    slot: 'helmet',
    rarity: 'common',
    element: 'stasis',
    power: 39,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-treads-16',
    name: 'Quantum Treads 16',
    slot: 'helmet',
    rarity: 'rare',
    element: 'solar',
    power: 53,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-harness-17',
    name: 'Velvet Harness 17',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'stasis',
    power: 69,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-sleeves-17',
    name: 'Echo Sleeves 17',
    slot: 'helmet',
    rarity: 'exotic',
    element: 'solar',
    power: 86,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-mask-18',
    name: 'Glass Mask 18',
    slot: 'helmet',
    rarity: 'mythic',
    element: 'stasis',
    power: 107,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
      'emberRelay11',
      'umbraLatch12',
      'stormVector13',
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-mark-18',
    name: 'Radiant Mark 18',
    slot: 'helmet',
    rarity: 'common',
    element: 'solar',
    power: 14,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-treads-19',
    name: 'Storm Treads 19',
    slot: 'helmet',
    rarity: 'rare',
    element: 'stasis',
    power: 28,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-harness-19',
    name: 'Prime Harness 19',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'solar',
    power: 44,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-sleeves-20',
    name: 'Dawn Sleeves 20',
    slot: 'helmet',
    rarity: 'legendary',
    element: 'stasis',
    power: 53,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
