/**
 * Kinetic Gear
 *
 * Per-slot shard of the Starforged gear table; starforgedGear.ts reassembles the
 * historical round-robin order (reward tables depend on array order).
 */
import type { StarforgedGearDefinition } from '../starforgedTypes.js';

export const KINETIC_GEAR: readonly StarforgedGearDefinition[] = [
  {
    id: 'astral-cipher-1',
    name: 'Astral Cipher 1',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 10,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
      'frostAnchor16',
      'threadBloom17',
      'spectrumFuse18',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-1',
    name: 'Scarlet Compass 1',
    slot: 'kinetic',
    rarity: 'common',
    element: 'stasis',
    power: 19,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
      'vanguardTempo01',
      'raidMender02',
      'serpentDoctrine03',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 0 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-accord-1',
    name: 'Quantum Accord 1',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'solar',
    power: 33,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
      'applePrimer06',
      'bossBreaker07',
      'roomRunner08',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 1 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-engine-2',
    name: 'Velvet Engine 2',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'stasis',
    power: 49,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
      'emberRelay12',
      'umbraLatch13',
      'stormVector14',
    ],
    setId: 'set-0',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-myth-2',
    name: 'Echo Myth 2',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'solar',
    power: 66,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
      'frostAnchor17',
      'threadBloom18',
      'spectrumFuse19',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 2 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-vow-3',
    name: 'Glass Vow 3',
    slot: 'kinetic',
    rarity: 'mythic',
    element: 'stasis',
    power: 87,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
      'vanguardTempo02',
      'raidMender03',
      'serpentDoctrine04',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 3 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-harbor-3',
    name: 'Radiant Harbor 3',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 64,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
      'applePrimer07',
      'bossBreaker08',
      'roomRunner09',
    ],
    setId: 'set-1',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-refrain-4',
    name: 'Storm Refrain 4',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 78,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
      'emberRelay13',
      'umbraLatch14',
      'stormVector15',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 4 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-crown-4',
    name: 'Prime Crown 4',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'solar',
    power: 24,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
      'frostAnchor18',
      'threadBloom19',
      'spectrumFuse00',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 5 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-lance-5',
    name: 'Dawn Lance 5',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'stasis',
    power: 33,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
      'vanguardTempo03',
      'raidMender04',
      'serpentDoctrine05',
    ],
    setId: 'set-2',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-edict-5',
    name: 'Golden Edict 5',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'solar',
    power: 50,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
      'applePrimer08',
      'bossBreaker09',
      'roomRunner10',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 6 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-key-5',
    name: 'Seraph Key 5',
    slot: 'kinetic',
    rarity: 'mythic',
    element: 'stasis',
    power: 71,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
      'emberRelay14',
      'umbraLatch15',
      'stormVector16',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 7 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-oracle-6',
    name: 'Cobalt Oracle 6',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 48,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
      'frostAnchor19',
      'threadBloom00',
      'spectrumFuse01',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 8 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-spiral-6',
    name: 'Riven Spiral 6',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 62,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
      'vanguardTempo04',
      'raidMender05',
      'serpentDoctrine06',
    ],
    setId: 'set-3',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-parable-7',
    name: 'Iron Parable 7',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'solar',
    power: 78,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
      'applePrimer09',
      'bossBreaker10',
      'roomRunner11',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 9 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-vector-7',
    name: 'Warden Vector 7',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'stasis',
    power: 95,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
      'emberRelay15',
      'umbraLatch16',
      'stormVector17',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 10 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-signal-8',
    name: 'Ash Signal 8',
    slot: 'kinetic',
    rarity: 'mythic',
    element: 'solar',
    power: 46,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
      'frostAnchor00',
      'threadBloom01',
      'spectrumFuse02',
    ],
    setId: 'set-4',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-lantern-8',
    name: 'Broken Lantern 8',
    slot: 'kinetic',
    rarity: 'common',
    element: 'stasis',
    power: 23,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
      'vanguardTempo05',
      'raidMender06',
      'serpentDoctrine07',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 11 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-mandate-9',
    name: 'Night Mandate 9',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'solar',
    power: 37,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
      'applePrimer10',
      'bossBreaker11',
      'roomRunner12',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 12 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-needle-9',
    name: 'Silent Needle 9',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 46,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
      'emberRelay16',
      'umbraLatch17',
      'stormVector18',
    ],
    setId: 'set-5',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cipher-10',
    name: 'Astral Cipher 10',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'solar',
    power: 62,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
      'frostAnchor01',
      'threadBloom02',
      'spectrumFuse03',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 13 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-10',
    name: 'Scarlet Compass 10',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'stasis',
    power: 79,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
      'vanguardTempo06',
      'raidMender07',
      'serpentDoctrine08',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 14 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-accord-10',
    name: 'Quantum Accord 10',
    slot: 'kinetic',
    rarity: 'mythic',
    element: 'solar',
    power: 100,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 4,
      resilience: 4,
      recovery: 4,
      discipline: 4,
      intellect: 4,
      strength: 4,
    },
    perkPool: [
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
      'applePrimer11',
      'bossBreaker12',
      'roomRunner13',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-engine-11',
    name: 'Velvet Engine 11',
    slot: 'kinetic',
    rarity: 'common',
    element: 'stasis',
    power: 77,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 9,
      resilience: 5,
      recovery: 23,
      discipline: 15,
      intellect: 11,
      strength: 25,
    },
    perkPool: [
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
      'emberRelay17',
      'umbraLatch18',
      'stormVector19',
    ],
    setId: 'set-6',
    lore: 'Recovered from timeline 15 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'echo-myth-11',
    name: 'Echo Myth 11',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'solar',
    power: 21,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 14,
      resilience: 6,
      recovery: 20,
      discipline: 4,
      intellect: 18,
      strength: 24,
    },
    perkPool: [
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
      'frostAnchor02',
      'threadBloom03',
      'spectrumFuse04',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 16 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'glass-vow-12',
    name: 'Glass Vow 12',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'stasis',
    power: 37,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 19,
      resilience: 7,
      recovery: 17,
      discipline: 15,
      intellect: 25,
      strength: 23,
    },
    perkPool: [
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
      'vanguardTempo07',
      'raidMender08',
      'serpentDoctrine09',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 17 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'radiant-harbor-12',
    name: 'Radiant Harbor 12',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'solar',
    power: 54,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 24,
      resilience: 8,
      recovery: 14,
      discipline: 4,
      intellect: 10,
      strength: 22,
    },
    perkPool: [
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
      'applePrimer12',
      'bossBreaker13',
      'roomRunner14',
    ],
    setId: 'set-7',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'storm-refrain-13',
    name: 'Storm Refrain 13',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'stasis',
    power: 63,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 7,
      resilience: 9,
      recovery: 11,
      discipline: 15,
      intellect: 17,
      strength: 21,
    },
    perkPool: [
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
      'emberRelay18',
      'umbraLatch19',
      'stormVector00',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 18 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'prime-crown-13',
    name: 'Prime Crown 13',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 52,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 12,
      resilience: 10,
      recovery: 8,
      discipline: 4,
      intellect: 24,
      strength: 20,
    },
    perkPool: [
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
      'frostAnchor03',
      'threadBloom04',
      'spectrumFuse05',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 19 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'dawn-lance-14',
    name: 'Dawn Lance 14',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 66,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 17,
      resilience: 11,
      recovery: 5,
      discipline: 15,
      intellect: 9,
      strength: 19,
    },
    perkPool: [
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
      'vanguardTempo08',
      'raidMender09',
      'serpentDoctrine10',
    ],
    setId: 'set-8',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'golden-edict-14',
    name: 'Golden Edict 14',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'solar',
    power: 75,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 22,
      resilience: 12,
      recovery: 24,
      discipline: 4,
      intellect: 16,
      strength: 18,
    },
    perkPool: [
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
      'applePrimer13',
      'bossBreaker14',
      'roomRunner15',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 20 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'seraph-key-14',
    name: 'Seraph Key 14',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'stasis',
    power: 91,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 5,
      resilience: 13,
      recovery: 21,
      discipline: 15,
      intellect: 23,
      strength: 17,
    },
    perkPool: [
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
      'emberRelay19',
      'umbraLatch00',
      'stormVector01',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 21 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'cobalt-oracle-15',
    name: 'Cobalt Oracle 15',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'solar',
    power: 38,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 10,
      resilience: 14,
      recovery: 18,
      discipline: 4,
      intellect: 8,
      strength: 16,
    },
    perkPool: [
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
      'frostAnchor04',
      'threadBloom05',
      'spectrumFuse06',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'riven-spiral-15',
    name: 'Riven Spiral 15',
    slot: 'kinetic',
    rarity: 'mythic',
    element: 'stasis',
    power: 59,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 15,
      resilience: 15,
      recovery: 15,
      discipline: 15,
      intellect: 15,
      strength: 15,
    },
    perkPool: [
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
      'vanguardTempo09',
      'raidMender10',
      'serpentDoctrine11',
    ],
    setId: 'set-9',
    lore: 'Recovered from timeline 22 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'iron-parable-16',
    name: 'Iron Parable 16',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 36,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 20,
      resilience: 16,
      recovery: 12,
      discipline: 4,
      intellect: 22,
      strength: 14,
    },
    perkPool: [
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
      'applePrimer14',
      'bossBreaker15',
      'roomRunner16',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 23 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'warden-vector-16',
    name: 'Warden Vector 16',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 50,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 25,
      resilience: 17,
      recovery: 9,
      discipline: 15,
      intellect: 7,
      strength: 13,
    },
    perkPool: [
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
      'emberRelay00',
      'umbraLatch01',
      'stormVector02',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'ash-signal-17',
    name: 'Ash Signal 17',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'solar',
    power: 66,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Crucible Quartermaster',
    stats: {
      mobility: 8,
      resilience: 18,
      recovery: 6,
      discipline: 4,
      intellect: 14,
      strength: 12,
    },
    perkPool: [
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
      'frostAnchor05',
      'threadBloom06',
      'spectrumFuse07',
    ],
    setId: 'set-10',
    lore: 'Recovered from timeline 24 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'broken-lantern-17',
    name: 'Broken Lantern 17',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'stasis',
    power: 83,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Deep Orbit Archive',
    stats: {
      mobility: 13,
      resilience: 19,
      recovery: 25,
      discipline: 15,
      intellect: 21,
      strength: 11,
    },
    perkPool: [
      'frostAnchor14',
      'threadBloom15',
      'spectrumFuse16',
      'vanguardTempo17',
      'raidMender18',
      'serpentDoctrine19',
      'applePrimer00',
      'bossBreaker01',
      'roomRunner02',
      'emberRelay04',
      'umbraLatch05',
      'stormVector06',
      'frostAnchor07',
      'threadBloom08',
      'spectrumFuse09',
      'vanguardTempo10',
      'raidMender11',
      'serpentDoctrine12',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 25 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'night-mandate-18',
    name: 'Night Mandate 18',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'solar',
    power: 92,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Iron Pageant',
    stats: {
      mobility: 18,
      resilience: 20,
      recovery: 22,
      discipline: 4,
      intellect: 6,
      strength: 10,
    },
    perkPool: [
      'vanguardTempo19',
      'raidMender00',
      'serpentDoctrine01',
      'applePrimer02',
      'bossBreaker03',
      'roomRunner04',
      'emberRelay06',
      'umbraLatch07',
      'stormVector08',
      'frostAnchor09',
      'threadBloom10',
      'spectrumFuse11',
      'vanguardTempo12',
      'raidMender13',
      'serpentDoctrine14',
      'applePrimer15',
      'bossBreaker16',
      'roomRunner17',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 26 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'silent-needle-18',
    name: 'Silent Needle 18',
    slot: 'kinetic',
    rarity: 'common',
    element: 'stasis',
    power: 11,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Moonlit Parish Armory',
    stats: {
      mobility: 23,
      resilience: 21,
      recovery: 19,
      discipline: 15,
      intellect: 13,
      strength: 9,
    },
    perkPool: [
      'applePrimer04',
      'bossBreaker05',
      'roomRunner06',
      'emberRelay08',
      'umbraLatch09',
      'stormVector10',
      'frostAnchor11',
      'threadBloom12',
      'spectrumFuse13',
      'vanguardTempo14',
      'raidMender15',
      'serpentDoctrine16',
      'applePrimer17',
      'bossBreaker18',
      'roomRunner19',
      'emberRelay01',
      'umbraLatch02',
      'stormVector03',
    ],
    setId: 'set-11',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'astral-cipher-19',
    name: 'Astral Cipher 19',
    slot: 'kinetic',
    rarity: 'common',
    element: 'solar',
    power: 20,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Foundry of Last Dawn',
    stats: {
      mobility: 6,
      resilience: 22,
      recovery: 16,
      discipline: 4,
      intellect: 20,
      strength: 8,
    },
    perkPool: [
      'emberRelay10',
      'umbraLatch11',
      'stormVector12',
      'frostAnchor13',
      'threadBloom14',
      'spectrumFuse15',
      'vanguardTempo16',
      'raidMender17',
      'serpentDoctrine18',
      'applePrimer19',
      'bossBreaker00',
      'roomRunner01',
      'emberRelay03',
      'umbraLatch04',
      'stormVector05',
      'frostAnchor06',
      'threadBloom07',
      'spectrumFuse08',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 27 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'scarlet-compass-19',
    name: 'Scarlet Compass 19',
    slot: 'kinetic',
    rarity: 'rare',
    element: 'stasis',
    power: 34,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Vanguard Serpentworks',
    stats: {
      mobility: 11,
      resilience: 23,
      recovery: 13,
      discipline: 15,
      intellect: 5,
      strength: 7,
    },
    perkPool: [
      'frostAnchor15',
      'threadBloom16',
      'spectrumFuse17',
      'vanguardTempo18',
      'raidMender19',
      'serpentDoctrine00',
      'applePrimer01',
      'bossBreaker02',
      'roomRunner03',
      'emberRelay05',
      'umbraLatch06',
      'stormVector07',
      'frostAnchor08',
      'threadBloom09',
      'spectrumFuse10',
      'vanguardTempo11',
      'raidMender12',
      'serpentDoctrine13',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 28 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'quantum-accord-19',
    name: 'Quantum Accord 19',
    slot: 'kinetic',
    rarity: 'legendary',
    element: 'solar',
    power: 50,
    intrinsic: 'Adaptive coil frame',
    originTrait: 'Ninefold Loom',
    stats: {
      mobility: 16,
      resilience: 24,
      recovery: 10,
      discipline: 4,
      intellect: 12,
      strength: 6,
    },
    perkPool: [
      'vanguardTempo00',
      'raidMender01',
      'serpentDoctrine02',
      'applePrimer03',
      'bossBreaker04',
      'roomRunner05',
      'emberRelay07',
      'umbraLatch08',
      'stormVector09',
      'frostAnchor10',
      'threadBloom11',
      'spectrumFuse12',
      'vanguardTempo13',
      'raidMender14',
      'serpentDoctrine15',
      'applePrimer16',
      'bossBreaker17',
      'roomRunner18',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
  {
    id: 'velvet-engine-20',
    name: 'Velvet Engine 20',
    slot: 'kinetic',
    rarity: 'exotic',
    element: 'stasis',
    power: 67,
    intrinsic: 'High-impact shrine lattice',
    originTrait: 'Seasonal Relic Foundry',
    stats: {
      mobility: 21,
      resilience: 25,
      recovery: 7,
      discipline: 15,
      intellect: 19,
      strength: 5,
    },
    perkPool: [
      'applePrimer05',
      'bossBreaker06',
      'roomRunner07',
      'emberRelay09',
      'umbraLatch10',
      'stormVector11',
      'frostAnchor12',
      'threadBloom13',
      'spectrumFuse14',
      'vanguardTempo15',
      'raidMender16',
      'serpentDoctrine17',
      'applePrimer18',
      'bossBreaker19',
      'roomRunner00',
      'emberRelay02',
      'umbraLatch03',
      'stormVector04',
    ],
    setId: 'set-12',
    lore: 'Recovered from timeline 29 after a serpent fireteam bent the orchard into a battlefield.',
  },
];
